import { BrowserProps } from "../pages/browse";

export default [
  {
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    poster: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    posterHorizontal: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    voteAverage: 7.5,
    type: "movie",
    videoUrl: "_Z3QKkl1WyM",
    similar: [
      {
        id: 201003,
        title: "The Family and One More",
        overview:
          "The life of the family inordinate surveyor Carlos Alonso has undergone several changes over the course of the years: the birth of child number 16, little Maria, coincided with the death of the mother, who left behind a hollow refillable. The grandfather also died. The Godfather pastry married, and the boys have been growing rapidly ...",
        poster: "/8bz1FKL9bPbIvHBHl0DeudexUZN.jpg",
        posterHorizontal: "/4U353J7OxDEl9HxohOgJ63LSlH2.jpg",
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199374,
        title: "My Sister's Kids in Africa",
        overview:
          "This time our already familiar family moves to Africa in order to save endangered wildlife.",
        poster: "/rwr2WiwR4St2eq21NEixEV56RE0.jpg",
        posterHorizontal: "/e2P8nGCJRgi04UPR0hhcWhoB42H.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199420,
        title: "Pawn Shop Chronicles",
        overview:
          "The stories of a missing wife, a couple of meth heads and an Elvis impersonator are connected by the items found in a small town's pawn shop.",
        poster: "/1jQUcZ2uWUe2jIxa5efNuMhdhts.jpg",
        posterHorizontal: "/pt4QcQmVhi5bAyEJvk87E7W1kcQ.jpg",
        voteAverage: 5.76,
        type: "movie",
        videoUrl: "bMA0bukvXsI",
      },
      {
        id: 201937,
        title: "Prehysteria! 2",
        overview:
          'A rich boy desperate for attention makes friends with the dinosaurs of "Prehysteria!". Prehysteria! 2',
        poster: "/oFvNCkKjYfSSGOjaEerp4XjJrcI.jpg",
        posterHorizontal: "/4ZLYAgNd7SLJJ9ZAjxTAJnVTDU5.jpg",
        voteAverage: 4.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201938,
        title: "Prehysteria! 3",
        overview:
          "The dinosaurs help young Ella and her family save their mini-putt business.",
        poster: "/nBTW3ME6IQuzuq6puvOhN0IQpQn.jpg",
        posterHorizontal: "/sp0Eg1Sd48OVIhFm4TPrAZJxhsx.jpg",
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199960,
        title: "The Son of Tarzan",
        overview:
          "Tarzan's son Jack is kidnapped from England by his old enemy Paulovich. Jack escapes into the African jungle where he meets Meriem, a European girl held captive. Freeing her, he falls in love but she's sought by Paulovich. Then Tarzan arrives with Jane to save the day!",
        poster: "/6TJ78ttG3O7pNSN8xBmYBf4nIKm.jpg",
        posterHorizontal: "/vCnah8kXNogx3B9jtB59kMIum5W.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 646389,
    title: "Plane",
    overview:
      "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
    poster: "/2g9ZBjUfF1X53EinykJqiBieUaO.jpg",
    posterHorizontal: "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
    voteAverage: 6.7,
    type: "movie",
    videoUrl: "7-6_Ulo7mdk",
    similar: [
      {
        id: 72759,
        title: "Temptation Island",
        overview:
          'Four beauty pageant contestants, who are vying for the coveted title of "Miss Manila Sunshine", set sail on a yacht. They ended up stranded on a deserted island after their vessel got caught up on fire. Together with an attractive young man, a maid and the gay pageant director, the four ladies found life "anything but dull".',
        poster: "/cmCv8GHTdhsONPTjzYaqLDQavkA.jpg",
        posterHorizontal: "/d2cKE5H8pIL9KMwXTt73L8cCxR.jpg",
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "We8YW3QWHCU",
      },
      {
        id: 91065,
        title: "Invaders Of The Lost Gold",
        overview:
          "Japanese soldiers battle a tribe of cannibals while protecting a gold shipment.",
        poster: "/64hN5yvqquMbwTdc3FxHLtKqxsq.jpg",
        posterHorizontal: "/iJezspE8QFNVthlw3LL3GZjKb6y.jpg",
        voteAverage: 3.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 94781,
        title: "Yesterday Today Tomorrow",
        overview:
          "It’s a story of people and their secrets that tear them apart...The movie follows a surprising decision that each family member will make in the aftermath of a tragedy… life changing decisions that will either lead them to a future lasting happiness, or one full of despair.",
        poster: "/c8SMjS6N5IP2Gix8bKpS8ofXFIl.jpg",
        posterHorizontal: null,
        voteAverage: 4,
        type: "movie",
        videoUrl: "SRD_h9N-GG0",
      },
      {
        id: 85852,
        title: "Rock All Night",
        overview:
          "Cloud Nine, the local teen hangout, has been taken over by a pair of escaped killers, who hold the local teens hostage. The bartender realizes it's up to him to save the kids.",
        poster: "/4QKW2GKgGetQmA4Cye4WmUYZnR.jpg",
        posterHorizontal: "/vl2NHqV2YtQFY9nZDdzOqNxvXYd.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 84005,
        title: "Won't Last a Day Without You",
        overview:
          "George Harrison Apostol (Sarah Geronimo) or better known as DJ Heidee is fast becoming the most popular DJ in town with her segment Heartbreak Hotline. DJ Heidee gives love advice to those who are having trouble with their relationships. Most often than not, she advices her callers to break up with their partners instead of working things out first. One caller (Megan Young) complains about her playboy boyfriend Andrew Escalona (Gerald Anderson). When she breaks up with him on air, Andrew threathens to have DJ Heidee investigated and suspended by the KBP not unless she helps him win back his ex-girlfriend.",
        poster: "/vIWkASQZ0qBSDyu3BeXCrDuV6Cn.jpg",
        posterHorizontal: null,
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "rLoxFfx4QLo",
      },
      {
        id: 84006,
        title: "D' Anothers",
        overview:
          "The Resurreccion's ancestral mansion is believed to have a portal to the other world. Every quarter of a century, it must be opened by a chosen member of the clan, known as \"The One\", to enable stranded ghosts to cross over to the afterlife. With no surviving clan member opening the portal in the past 100 years, ghosts have overcrowded the now-abandoned mansion. Hesus Resurreccion is about to find out that he is The One but he is afraid of ghosts. When he inherits the mansion, he wants to sell it immediately but it isn't that easy since people believe the mansion is haunted. He totally freaks out when he learns that the people he sees in the mansion are all ghosts. Hesus has no choice but to fulfill his mission as The One. As he spends more time with the ghosts, he realizes that they are not scary at all and even enjoys their company. In the end Hesus got the key and opened the portal",
        poster: "/d18SSu7qAWyzcrt5x2xFr4QWmve.jpg",
        posterHorizontal: "/tCkqp4PxNXohhFoCc0erndYncdh.jpg",
        voteAverage: 7.2,
        type: "movie",
        videoUrl: "3IiSdd1_d4U",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/tGwO4xcBjhXC0p5qlkw37TrH6S6.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 72762,
        title: "Jack and the Beanstalk",
        overview:
          "A retelling of the popular fairy tale that mixes live action and animation.",
        poster: "/prD4GSmkzW8XbZKhZpW4wQ9dI3Q.jpg",
        posterHorizontal: "/qtMMIqLhk5SVJMRuoKgHcM6G3PC.jpg",
        voteAverage: 7.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 75098,
        title: "Lotte Reiniger: The Fairy Tale Films",
        overview:
          "Lotte Reiniger was one of the twentieth century’s major animation artists, pioneering a distinctive style of black and white silhouette animation in her interpretations of classic myths and fairy tales. Reiniger began her career in Germany, making The Adventures of Prince Achmed, one of the first and most ingenious full-length animated films in the history of cinema. After the war, she moved to Britain with her husband Carl Koch and made short films for the GPO and later, in collaboration with Primrose Productions, an extensive series of famous fairy tale short films. This is a DVD collection of her work.",
        poster: "/vsjDHSXs80FJGGUD7qzijMn7NSD.jpg",
        posterHorizontal: "/pz3TXUZOJkws4wp2weW1yo4zUeW.jpg",
        voteAverage: 9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80304,
        title: "Casa De Mi Padre",
        overview:
          "Scheming of a way to save their father's ranch, the Alvarez brothers find themselves in a war with Mexico's most feared drug lord.",
        poster: "/kVCc7xwTAlckBofazrwIz8x1TXC.jpg",
        posterHorizontal: "/bTy0LQEXValfIemrLvE5dMJobE4.jpg",
        voteAverage: 5.38,
        type: "movie",
        videoUrl: "01IYDy2Gdk4",
      },
      {
        id: 90512,
        title: "The Frog Princess",
        overview:
          "A prince discovers an enchanted beauty turned into a frog by Koschei the Immortal. After Koschei steals her again, the prince goes on a dangerous quest to free the land of the evil.",
        poster: "/qa6gtK1T1wMebluGMv5c7KANK90.jpg",
        posterHorizontal: "/3UaeEyh0yJEYGxtPqRu9TwaWz4i.jpg",
        voteAverage: 7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83811,
        title: "The Daydreamer",
        overview:
          "In this hybrid of live-action and stop-motion animation, a young Hans Christian Andersen goes in search of knowledge in the Garden of Paradise in order to make his studies easier. Each time he falls asleep, he experiences in his dreams the different characters he would later write about in fairy tales including The Little Mermaid, Thumbelina and The Emperor's New Clothes.",
        poster: "/k7RiyeB5NccB2NgXtVFJXFiwe6Z.jpg",
        posterHorizontal: "/1D05GkR8sJDzGuQirq26q1tIQgX.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 82990,
        title: "Paranormal Activity 4",
        overview:
          "It has been five years since the disappearance of Katie and Hunter, and a suburban family witness strange events in their neighborhood when a woman and a mysterious child move in.",
        poster: "/na5tAslm1kGNcft083AIXMTOsYR.jpg",
        posterHorizontal: "/eq68gWGBtumauGYFV1FCJ20kXFU.jpg",
        voteAverage: 5.418,
        type: "movie",
        videoUrl: "P1wbwf0wayk",
      },
    ],
  },
  {
    id: 758009,
    title: "Shotgun Wedding",
    overview:
      "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.",
    poster: "/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
    posterHorizontal: "/t72ZvOZwtvcjZivZCFtCtL8QWb0.jpg",
    voteAverage: 6.3,
    type: "movie",
    videoUrl: "U8gz0rUzTAY",
    similar: [
      {
        id: 197181,
        title: "Божественная комедия",
        overview: "",
        poster: "/ad1uR10A0Yqsyqp64h20ItE2kNx.jpg",
        posterHorizontal: null,
        voteAverage: 9.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201765,
        title: "Three Many Weddings",
        overview:
          "Ruth, a young researcher at a college, is invited to the weddings of three of her exes. She enlists the help of her assistant to find a companion for each wedding; will one of them turn out to be her soulmate?",
        poster: "/zLZT2B8ioGJyuU3UmCXiY0fa5Fd.jpg",
        posterHorizontal: "/ogKkr5YOyKB0gY5lNTB9Rx6ZI95.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201772,
        title: "Breakup at a Wedding",
        overview:
          "On the eve of their wedding, Alison gets cold feet and decides to break up with her fiancé Phil.  But rather than face the embarrassment of calling off the ceremony, Alison suggests to Phil that they proceed with a sham wedding. Phil is more than game to try, secretly hoping that a surprise gift he has for Alison will ultimately change her mind.  Yet once the guests begin to arrive, more complications ensue than either of them could have ever imagined - even if they did know their wedding was bullshit.",
        poster: "/8sjPLwmbDLtFIHKGaqxPMME44XY.jpg",
        posterHorizontal: "/oQIuXCjeIQS93gDX9aPKnk8l7YL.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "5mFs8FCp24Q",
      },
      {
        id: 201797,
        title: "Sábado",
        overview:
          '"Mother" stands out on the front of her black t-shirt, "Fucker" on the back. And as angrily as these words sound when combined into a curse, is how Antonia behaves. Because she is pregnant, and Victor, who slept with her, is getting married in a few hours to Blanca.',
        poster: "/gxabjkaOBjnj0F9D9SlXoYQgQVT.jpg",
        posterHorizontal: null,
        voteAverage: 5.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 205015,
        title: "Four Sisters and a Wedding",
        overview:
          "The children of the Salazar family have been pursuing separate lives in the recent years. After a few years of not being together as a whole family, they find themselves reuniting when CJ announces his plan to marry Princess, his girlfriend for three months. Much to their shock and dismay, CJ's sisters come together for the wedding and have agreed to dissuade him from marrying his fiancée.",
        poster: "/b9EiKeCdwzwdOFQ0W1RiXGMuZHJ.jpg",
        posterHorizontal: "/xuTjXyYQwYRoCNXUsiikrxdU6rX.jpg",
        voteAverage: 6.844,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 203845,
        title: "Navajo Trail Raiders",
        overview:
          "Outlaw gangs are plundering the freight lines that bring supplies into Yellow Creek. The only thing that will save the town is the insurance money on the freight, but the outlaws are looking to steal that also. Lane comes to town as the best man for the wedding of Tom and Judy, but it will be up to him to find the outlaw boss.",
        poster: "/1KkbdNnNOTbcQlm0qVfLLPFpq2W.jpg",
        posterHorizontal: "/bjWhe8bwpPk8TzLKLdalEzYsmom.jpg",
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 536554,
    title: "M3GAN",
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    poster: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
    posterHorizontal: "/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg",
    voteAverage: 7.5,
    type: "movie",
    videoUrl: "OoDHM_A1axc",
    similar: [
      {
        id: 94005,
        title: "No Place To Hide",
        overview:
          "Detective Joe Garvey is called in to a mysterious case: a ballerina has been slayed on stage during a performance, it seems she didn't even fight. At her house Garvey finds her 14 years old precocious sister Tinsel. She's not very cooperative, so he arranges to have her sent to the orphanage -- until she's attacked too. He takes her under his wings, and soon both get the attention of a secret organization.",
        poster: "/xsgAsIvzNk761Xdyijiem6LlWl8.jpg",
        posterHorizontal: "/hPjfe7sgEeK6qagrl4Ldhaa3spf.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "0xN2dVE9yfs",
      },
      {
        id: 84711,
        title: "The Jungle Captive",
        overview:
          "Once again Paula the ape woman is brought back to life, this time by a mad doctor and his disfigured assistant, who also kidnaps a nurse in order to have a female blood donor.",
        poster: "/ixraVEU6w5UgdKoVI8X1hwkbAZ6.jpg",
        posterHorizontal: "/whqoDd8o8VyE33qrR5C3GQrDBBx.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "9RoJUlmnXlM",
      },
      {
        id: 81789,
        title: "Sor Ye-yé",
        overview:
          "Maria is a young orphan who lives with her wealthy aunt. Maria sings in a cocktail bar with his friends, who form a rock band, and enjoy the night with them. One of his friends, Ernesto, is in love with her, though she does not seem to feel the same about him. In fact, multiple existential doubts and feel a strange emptiness in his life suddenly drive to enter a convent as a novice, breaking Ernestos' heart. However, with her cheerlul character, open and rebellious, not appear to conform to life in the cloister, and especially have problems with the novices director , who often punished for trying to take the right path. In the convent, which also functions as children's hospital, she meets a doctor with which it takes quite right for the contrast between his two characters, but his way with love and mutual respect.",
        poster: "/pZ3Sx7xzZ9TnVtcVW6lp7pNKj0m.jpg",
        posterHorizontal: null,
        voteAverage: 4.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 92951,
        title: "The Girl in the Rumor",
        overview:
          'A story of two sisters, the older being more traditional, the younger a "moga" ("modern girl"). Their widowed father runs the family sake shop, but is running into financial trouble, causing him to tamper with his stock; Meanwhile, his long-time mistress yearns for something more serious. Amidst this, the older sister is introduced to a well-off suitor: A university boy, much more intrigued by the less traditional little sister. A doddering grandfather, an officious uncle and busybody neighbors also don\'t make the lives of the hardworking members of the family any easier.',
        poster: "/1Q8AAbQB640F4Optl436wcNo3Xn.jpg",
        posterHorizontal: null,
        voteAverage: 5.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 84946,
        title: "Diary for My Children",
        overview:
          "A semi-autobiographical story of a young woman's life in Budapest under Stalin.",
        poster: "/hK9ji8IfBxkp3N34ohbsWhbvbff.jpg",
        posterHorizontal: "/4poVDneChHbxPKTJAxAPKzsxiUw.jpg",
        voteAverage: 6.8,
        type: "movie",
        videoUrl: "E5XBbh2L-MA",
      },
      {
        id: 84996,
        title: "Scream for Help",
        overview:
          "A teenaged girl discovers that her stepfather is trying to murder her and her mother, but when she tells people, no one will believe her.",
        poster: "/lIbWP5dxPJ7rRolg4pNZ617QlHz.jpg",
        posterHorizontal: "/2DFh4bJCdb1XaAhg4RvnIgU1q47.jpg",
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "lOS7CZqSxkE",
      },
    ],
  },
  {
    id: 843794,
    title: "JUNG_E",
    overview:
      "On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.",
    poster: "/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg",
    posterHorizontal: "/qHdPNd1cUaSNYLLNgt1Pv3LVd0T.jpg",
    voteAverage: 6.3,
    type: "movie",
    videoUrl: "v_Jc1MYFv5g",
    similar: [
      {
        id: 104281,
        title: "Cobra Thunderbolt",
        overview:
          "The daughter of a brilliant Thai army colonel, who invented the machine battle Cobra Thunderbolt, takes on the lao-army to rescue his kidnapped father.",
        poster: "/xr5cjxwKBzcrzS2aagLRETfUJ4N.jpg",
        posterHorizontal: "/k9WKfSTVVOrVXajvE6UjXlZGs3s.jpg",
        voteAverage: 4.8,
        type: "movie",
        videoUrl: "oZBFPwD2kmc",
      },
      {
        id: 81778,
        title: "Sabotage",
        overview:
          "Former special services agent plays an intricate game of chess involving several federal agencies. Queen takes pawn.",
        poster: "/8nZPFmLjiuHxEnOZIcZG8z2rpeR.jpg",
        posterHorizontal: "/wb2S8el2WbCuMjN0DJjfmFLkx4z.jpg",
        voteAverage: 5.6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 81796,
        title: "Lockout",
        overview:
          "Set in the near future, Lockout follows a falsely convicted ex-government agent , whose one chance at obtaining freedom lies in the dangerous mission of rescuing the President's daughter from rioting convicts at an outer space maximum security prison.",
        poster: "/i5QfNIcg6hc327IWUerea0EczP4.jpg",
        posterHorizontal: "/vee4TWQX9MPywfU2QifDhKd7Wpl.jpg",
        voteAverage: 5.903,
        type: "movie",
        videoUrl: "BQ4hZqrIM9w",
      },
      {
        id: 81861,
        title: "The Ultimate Weapon",
        overview:
          "Mercenaries, Ben & Vince, are assigned to destroy a stolen military arms cache held by a group of terrorists.",
        poster: "/irLwtIARtLqnWbtOZifsqAJWFQo.jpg",
        posterHorizontal: "/spRlUOlQkkOT89JfvZbwxcdCVDp.jpg",
        voteAverage: 3.8,
        type: "movie",
        videoUrl: "qPTbFTNf2LI",
      },
      {
        id: 97561,
        title: "Noon Sunday",
        overview:
          "Two mercenaries are hired to commit a political assassination.",
        poster: "/yBg46XBPnEMwAT2mEH91xJUAPT3.jpg",
        posterHorizontal: null,
        voteAverage: 2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 107319,
        title: "Wheels of Fire",
        overview:
          "The Future is now. There are no rules and no place to hide from the deadly Highway Warriors who ravage the roads in machines of destruction.",
        poster: "/c0fx4ZIu4lTSCPZSDC0HobcV2zA.jpg",
        posterHorizontal: "/mxxXWiNfUJDg2LczfSTJssuZDGk.jpg",
        voteAverage: 4,
        type: "movie",
        videoUrl: "ADfLrdNe8_4",
      },
    ],
  },
  {
    id: 842544,
    title: "Transfusion",
    overview:
      "Ryan Logan, a former Special Forces operative, is battling to cope with life after the loss of his wife.  He is thrusted into the criminal underworld to keep his only son from being taken from him.",
    poster: "/bxh5xCCW9Ynfg6EZJWUkc1zqTnr.jpg",
    posterHorizontal: "/a4I481szRmycyreQTLrRe4f4YJe.jpg",
    voteAverage: 6.7,
    type: "movie",
    videoUrl: "pA6CGAwVq-Q",
    similar: [
      {
        id: 104281,
        title: "Cobra Thunderbolt",
        overview:
          "The daughter of a brilliant Thai army colonel, who invented the machine battle Cobra Thunderbolt, takes on the lao-army to rescue his kidnapped father.",
        poster: "/xr5cjxwKBzcrzS2aagLRETfUJ4N.jpg",
        posterHorizontal: "/k9WKfSTVVOrVXajvE6UjXlZGs3s.jpg",
        voteAverage: 4.8,
        type: "movie",
        videoUrl: "oZBFPwD2kmc",
      },
      {
        id: 104308,
        title: "The Spider Labyrinth",
        overview:
          "A young professor travels to Budapest to locate a lost colleague. Once there, he gets tangled up in a supernatural mystery.",
        poster: "/AbkpVmqWQcbifw0Push788KGI45.jpg",
        posterHorizontal: "/rXJG45RN9sPd3AcRHb1nofjJYzf.jpg",
        voteAverage: 6.4,
        type: "movie",
        videoUrl: "O0Coq2XrwmE",
      },
      {
        id: 89652,
        title: "Colt 38 Special Squad",
        overview:
          'The city of Turin is in the grip of a brutal crime boss known as "the Marsellaise," and plenty of cops have good cause to want him dead — none more than Inspector Vanni, whose wife was murdered by the ruthless gangster. Having exhausted every other avenue, Vanni forms a crack squad of motorcycle-riding, Colt .38-toting elite officers, tasked with meting out justice on the margins of the law. But when the Marsellaise launches a bombing campaign designed to extort a vast ransom from the city\'s authorities, Vanni finds himself in a race against time to exact his revenge and avert disaster.',
        poster: "/lbWogWBxlyem3O4g0Htjvpq7bNB.jpg",
        posterHorizontal: "/uffcfiv78G3Tv81uy4I09hXkmu0.jpg",
        voteAverage: 6.6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 97630,
        title: "Zero Dark Thirty",
        overview:
          "A chronicle of the decade-long hunt for al-Qaeda terrorist leader Osama bin Laden after the September 2001 attacks, and his death at the hands of the Navy S.E.A.L. Team 6 in May, 2011.",
        poster: "/coeTvXKAYZlrcIfsCfYV5Hw1npu.jpg",
        posterHorizontal: "/9d2RSOBmA5k6sDQoOkuBxJ9Gf7h.jpg",
        voteAverage: 6.978,
        type: "movie",
        videoUrl: "k7R2uVZYebE",
      },
      {
        id: 95728,
        title: "The Floating Landscape",
        overview:
          "Maan has recently lost her lover, Sam, a painter who died tragically of an incurable disease. Before his death, he was remembering a beautiful landscape from the days when he was still a boy living in Qingdao in China. Maan goes to Qingdao to find this landscape. There, she meets Lit (Liu Ye), a postman who will help her to find that place. A relationship grows between Maan and Lit but she can't forget the love she had for Sam.",
        poster: "/zCKaHGHw6Ct1joTZhnnLrBMOtlm.jpg",
        posterHorizontal: "/tK22RcmNdoB44nXMQus16Rxliz1.jpg",
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 72051,
        title: "Garv: Pride and Honour",
        overview:
          "About to retire, police inspector Samar Singh changes his mind when he discovers that a recently elected official has ties with the underworld.",
        poster: "/9lqPTKndjMWfPmBRyH8rWw7bH5I.jpg",
        posterHorizontal: "/44kkKYMQJKCyuLQJQpvUvVes8KT.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "j5qWTLYwmxU",
      },
    ],
  },
  {
    id: 1035806,
    title: "Detective Knight: Independence",
    overview:
      "Detective James Knight 's last-minute assignment to the Independence Day shift turns into a race to stop an unbalanced ambulance EMT from imperiling the city's festivities. The misguided vigilante, playing cop with a stolen gun and uniform, has a bank vault full of reasons to put on his own fireworks show... one that will strike dangerously close to Knight's home.",
    poster: "/jrPKVQGjc3YZXm07OYMriIB47HM.jpg",
    posterHorizontal: "/tCpMRsHlfR6CcqJYA3kJMS3YApt.jpg",
    voteAverage: 6.4,
    type: "movie",
    videoUrl: "zt-hyQE-sIA",
    similar: [
      {
        id: 86254,
        title: "Crash Landing",
        overview:
          "When a hostage situation arises on-board a private plane with the daughter of a billionaire on-board. Major John Masters (Sabato Jr.) teams up with Captain Williams (Michael Paré) to stop the terrorist and land the plane.",
        poster: "/vnrnYwiG5nug6BUqBVW5VymhPnU.jpg",
        posterHorizontal: "/4HcAW2XZ11HtE5lBZFZGbrBB96n.jpg",
        voteAverage: 4.9,
        type: "movie",
        videoUrl: "rR5RU9wcHhM",
      },
      {
        id: 103152,
        title: "Yoyes",
        overview:
          "Yoyes, the first woman to hold responsibility positions within ETA, returns from exile in Mexico and try to rebuild her life. But her return is not easy.",
        poster: "/7XVKCW77LyxTseGX3nYB3U3Dnto.jpg",
        posterHorizontal: "/rZDhhUYBqwLKmMG4LpkPs3nyDhZ.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 88456,
        title: "Disaster on the Coastliner",
        overview:
          "A deranged engineer, bent on revenge for the deaths of his wife and daughter, sets two passenger trains on a collision course, and con-man Robert Fuller puts his life on the line to ward off the crash.",
        poster: "/iKAGXYhII54TzjNBER3KbJBW5RB.jpg",
        posterHorizontal: "/6chUzVWjq4D6EOUIQbMC6KQuSiV.jpg",
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "-FIHo2WFnoQ",
      },
      {
        id: 74636,
        title: "The 9/11 Chronicles Part One: Truth Rising",
        overview:
          "The documentary provides an in-depth look at the plight of 9/11 first responders, many afflicted with serious health problems from the toxicity of Ground Zero. Truth Rising reveals and challenges the astounding arrogance and negligence of the government in regard to the heroic efforts of first responders, police, and fire-fighters. Truth Rising indicts the administration of Rudy Giuliani and that of the EPA and Christine Todd Whitman, who proclaimed the air in lower Manhattan was safe to breathe, contrary to numerous warnings to the contrary.",
        poster: "/tJ3pXxITmKY7yH468sUdI2PZGaX.jpg",
        posterHorizontal: null,
        voteAverage: 0.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 87581,
        title: "Blink of an Eye",
        overview:
          "An agent with psychic powers comes to the rescue of the kidnapped daughter of the CIA director.",
        poster: "/b12K1VGnTWxBCg2UeR1U68NM5EI.jpg",
        posterHorizontal: null,
        voteAverage: 1,
        type: "movie",
        videoUrl: "p8Co26l_rkU",
      },
      {
        id: 83224,
        title: "Todos estamos invitados",
        overview:
          'Spain. The Basque Country. Sometime in the 90s. Josu Jon, a young member of a terrorist organization, has suffered an almost complete memory loss after being wounded in a shooting with the Spanish police. As he awaits for his trial, his condition is being treated at the prison hospital. Other inmates belonging to the same organization try to make him remember how brave a "gudari" -a Basque soldier- he is and how he must go back to the armed fight for the independence of their country as soon as he gets out of prison. Meanwhile, Xabier, a college professor who has been death-threatened by the terrorists due to his political views on the Basque situation, is having an affair with Francesca, a young psychologist who happens to end up trying to help Josu Jon recover his memory. A warm feeling of mutual affection grows between her and her patient. At a point, it doesn\'t seem to be clear whether Josu Jon really wants to recover his memory or rather forget forever who he actually is.',
        poster: "/by2RjlxgcNFasIr5TbkCNIy5BA2.jpg",
        posterHorizontal: null,
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 76600,
    title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    posterHorizontal: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    voteAverage: 7.7,
    type: "movie",
    videoUrl: "o5F8MOz_IDw",
    similar: [
      {
        id: 104281,
        title: "Cobra Thunderbolt",
        overview:
          "The daughter of a brilliant Thai army colonel, who invented the machine battle Cobra Thunderbolt, takes on the lao-army to rescue his kidnapped father.",
        poster: "/xr5cjxwKBzcrzS2aagLRETfUJ4N.jpg",
        posterHorizontal: "/k9WKfSTVVOrVXajvE6UjXlZGs3s.jpg",
        voteAverage: 4.8,
        type: "movie",
        videoUrl: "oZBFPwD2kmc",
      },
      {
        id: 104308,
        title: "The Spider Labyrinth",
        overview:
          "A young professor travels to Budapest to locate a lost colleague. Once there, he gets tangled up in a supernatural mystery.",
        poster: "/AbkpVmqWQcbifw0Push788KGI45.jpg",
        posterHorizontal: "/rXJG45RN9sPd3AcRHb1nofjJYzf.jpg",
        voteAverage: 6.4,
        type: "movie",
        videoUrl: "O0Coq2XrwmE",
      },
      {
        id: 89661,
        title: "This Was Pancho Villa: Third chapter",
        overview:
          "The third and final chapter of director Ismael Rodríguez's series about Pancho Villa. Several stories about the life and death of the famous mexican revolutionary general.",
        poster: "/b4qVNHxefBEmwZccubxQKojlcpT.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 84642,
        title: "Wedding in White",
        overview:
          "A young girl's brother comes home from the army, and brings an army buddy with him. The three of them go out that night to celebrate, and after much drinking has been done, the brother's friend rapes the sister. After the two men have gone back, the girl finds that she's pregnant--and discovers that her parents don't blame the soldier, but blame her.",
        poster: "/y4GffwB2qRH1eofrgk9nWhZQudG.jpg",
        posterHorizontal: "/fk6u4yxN5kWGRv1W9NwqfS10Ti7.jpg",
        voteAverage: 6.7,
        type: "movie",
        videoUrl: "JWV3mYDQM7k",
      },
      {
        id: 84710,
        title: "Jungle Woman",
        overview:
          "Paula, the ape woman, has survived the ending of CAPTIVE WILD WOMAN and is running around a creepy old sanitarium run by the kindly Dr. Fletcher, reverting to her true gorilla form every once in a while to kill somebody.",
        poster: "/4XzmpTp38x52hRx76IA1YIaMfUX.jpg",
        posterHorizontal: "/67lBq3XTsMq2r5HyeIM6PzCBUvH.jpg",
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 97576,
        title: "The Midnight Parasites",
        overview:
          "A night when parasites of various green forms devour humans. A cruel food chain that never ceases, and an eternal repetition of life and death. A grotesque and strange parable drawn by Yoji Kuri. Isao Tomita's synthesizer music echoes quietly and eerily.",
        poster: "/AveOMtt5VK7ydSBdv2wayRxFErP.jpg",
        posterHorizontal: "/9QCAQvTS2bf9agaLnmaZikIKNCZ.jpg",
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 996727,
    title: "The Price We Pay",
    overview:
      "After a pawn shop robbery goes askew, two criminals take refuge at a remote farmhouse to try to let the heat die down, but find something much more menacing.",
    poster: "/8fwJt0qZieQ7dKaiiqehObWpXYT.jpg",
    posterHorizontal: "/f9PSbuMeBS5CuHEOVyymg5lcq8J.jpg",
    voteAverage: 6.1,
    type: "movie",
    videoUrl: "aIPbV97Gn8Q",
    similar: [
      {
        id: 192899,
        title: "The Sign of Four",
        overview:
          "Sherlock Holmes and Dr. Watson try to track down the Great Mogul, the second-largest diamond in the world.",
        poster: "/yU0yVIswpZLPCPFigM2aRvKsTwj.jpg",
        posterHorizontal: "/eDtxOLU7a5LzLF5HbmmPPwOdgza.jpg",
        voteAverage: 6.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 191005,
        title: "Committed",
        overview:
          'Dr. Dupont arrives at a mental facility to apply for a staff position. World famous Dr. Quilly interviews her, and has her sign papers. She is thrilled to get the job, and is shown her room. However, confusion with her room being on the same floor as the patients\' soon turns to panic as she is told that she is a "guest"- not a doctor, and the papers she signed were not job forms, but commitment papers.',
        poster: "/nt2Ibz3I0X03JGy63LPayANWVvR.jpg",
        posterHorizontal: "/mp6Jg9gIVEwvpMYeQq4koVGZfXH.jpg",
        voteAverage: 7.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 207644,
        title: "Contagious",
        overview:
          "When shrimp from Mexico, tainted with Cholera, is served to people on a plane bound for LA, an outbreak ensues. A doctor sets out to find the source and contain it before it turns into an epidemic. And if things weren't bad enough, a drug mule from the plane, who was smuggling cocaine in his stomach, infects the drugs, which will be on the streets soon. And to top things off, her husband who is on a camping trip with their two children is sick but did not show any symptoms until they were isolated from the rest of the world. Can she get to them in time?",
        poster: "/p69EnT4snGbOYFg8iZJ9HGxKBDx.jpg",
        posterHorizontal: null,
        voteAverage: 4.6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 2887,
        title: "And the Band Played On",
        overview:
          "The story of the discovery of the AIDS epidemic and the political infighting of the scientific community hampering the early fight with it.",
        poster: "/4fyZ6SZaZuerfZWaIp0niFW7Yar.jpg",
        posterHorizontal: "/9EjHUb6xNrHUsjxMu16p8KmR7Cy.jpg",
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "PaHUzy-A05U",
      },
      {
        id: 1362,
        title: "The Hobbit",
        overview:
          "Bilbo Baggins the Hobbit was just minding his own business, when his occasional visitor Gandalf the Wizard drops in one night. One by one, a whole group of dwarves drop in, and before he knows it, Bilbo has joined their quest to reclaim their kingdom, taken from them by the evil dragon Smaug. The only problem is that Gandalf has told the dwarves that Bilbo is an expert burglar, but he isn't...",
        poster: "/2ohvyMPhvjftLrM6S6Ljr6QrL0u.jpg",
        posterHorizontal: "/qNVf39jp9fZSLd1bWMYjOrrEkI2.jpg",
        voteAverage: 6.278,
        type: "movie",
        videoUrl: "f_JMOPCo31M",
      },
      {
        id: 15759,
        title: "Skylark",
        overview:
          "Jacob's farm is in trouble from a severe drought. Jacob and Sarah begin to wonder if Sarah can stay, and what will happen to Jacob if she and the children have to leave the farm.",
        poster: "/jVOPrMs9lK3nYFyL3Tj15vjOyhP.jpg",
        posterHorizontal: "/zYX8Jz6cKf73KPJTqhMgHih9CdB.jpg",
        voteAverage: 7.5,
        type: "movie",
        videoUrl: "icfLagn6EPk",
      },
    ],
  },
  {
    id: 1003580,
    title: "Legion of Super-Heroes",
    overview:
      "Kara, devastated by the loss of Krypton, struggles to adjust to her new life on Earth. Her cousin, Superman, mentors her and suggests she leave their space-time to attend the Legion Academy in the 31st century, where she makes new friends and a new enemy: Brainiac 5. Meanwhile, she must contend with a mysterious group called the Dark Circle as it searches for a powerful weapon held in the Academy’s vault.",
    poster: "/3whQLi8RI7h2h2Si2KTDFJxfEcR.jpg",
    posterHorizontal: "/jhi3K0rN46SSu9wEu6zYVCOeVtH.jpg",
    voteAverage: 6.5,
    type: "movie",
    videoUrl: "DKNjOwuBDbo",
    similar: [
      {
        id: 2395,
        title: "Astérix at the Olympic Games",
        overview:
          "Astérix and Obélix have to win the Olympic Games in order to help their friend Alafolix marry Princess Irina. Brutus uses every trick in the book to have his own team win the game, and get rid of his father Julius Caesar in the process.",
        poster: "/eNB2SrqmTJLByRDq3akDzA6Z9rC.jpg",
        posterHorizontal: "/2PuEmuXQF3XQZp8Ki2mGJXUGEOd.jpg",
        voteAverage: 5.185,
        type: "movie",
        videoUrl: "I4IwYe5N1o0",
      },
      {
        id: 103675,
        title: "Model by Day",
        overview:
          "Lady X is a woman who works during the day as a model but turns into a fighter for justice at night with the help of her karate master Chang.",
        poster: "/tljlsTmZhf6uHSuhH4gIvvCp4gg.jpg",
        posterHorizontal: "/gadF96nDIadabPpCMN2wIBAJLKj.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "mYCtQrsBgZk",
      },
      {
        id: 103782,
        title: "Snoopy: The Musical",
        overview:
          'The animated adaption of the second stage musical based on the "Peanuts" comics strip, focusing on Snoopy.',
        poster: "/2yWCJkXkd9NWs68aYUiyf9ppiFJ.jpg",
        posterHorizontal: null,
        voteAverage: 6.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 94636,
        title: "Harold Teen",
        overview:
          "A young reporter pines for his high-school sweetheart, but she's preoccupied with appearing in their small town's community musical show. This 1934 comedy, with numerous songs, was inspired by the popular Depression-era comic strip of the same title. With Hal Le Roy, Rochelle Hudson, Guy Kibbee, Hugh Herbert,Douglass Dumbrille and Patricia Ellis.",
        poster: "/evRe6iGmQukpuigTKTHVACLINZI.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 93560,
        title: "Batman and Robin",
        overview:
          "This 15-chapter serial pits Batman and Robin against The Wizard, who uses a device that allows him to control machinery to hold the city hostage.",
        poster: "/qTB6FB1zwW9dvtpKp5qZB7tl7BA.jpg",
        posterHorizontal: "/jO1VKpa6JDh6pV7MLKWh7zfvuNm.jpg",
        voteAverage: 5.679,
        type: "movie",
        videoUrl: "qMEVLZkVdCM",
      },
      {
        id: 85251,
        title: "Lastikman",
        overview:
          "Young Hilario was nearby a rubber tree when it was struck by a meteorite. This incident gave Hilario the powers of elasticity and morphing. To honor his dead parents he vowed to use his powers for good. Hilario grows up and becomes Professor Larry, a teacher in Physics. He transforms into the superhero Lastikman to protect people from injustice and oppression.",
        poster: "/3LJqUdddv393Pre13TIASzsogUr.jpg",
        posterHorizontal: null,
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 436270,
    title: "Black Adam",
    overview:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    poster: "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    posterHorizontal: "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    voteAverage: 7.2,
    type: "movie",
    videoUrl: "mkomfZHG5q4",
    similar: [
      {
        id: 72828,
        title: "Demon Spies",
        overview:
          "Deep in the mountains of feudal Japan, a group of children endure cruel and unorthodox training in order to become the Shogunate's most secret and deadly weapons - the Demon Spies! Their true identities are hidden - even from each other. Behind their demon masks, they are educated in the deadly arts of infiltration, espionage, assassination - and seduction! If they survive to become strong enough to kill their teachers, they will become - the Demon Spies! Sent on a suicide mission to uncover a deadly conspiracy, five inexperienced Demon Spies must infiltrate a powerful fief, discover the location of its secret arsenal, and destroy it. But Lord Shogen, the Demon Hunter, plans to brutally interrogate, ingeniously torture, and cruelly execute - the Demon Spies!",
        poster: "/gvFdVDigHlK4hXK9OkVEQXB1hpz.jpg",
        posterHorizontal: null,
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "5UObf8-RtTk",
      },
      {
        id: 72857,
        title: "Le Grand Chef 2: Kimchi Battle",
        overview:
          '"Le Grand Chef 2" begins with the Korean president visiting the Japanese Prime Minister and becoming involved in a heated debate over the origins of kimchi. The Japanese Prime Minister makes the bold claim that kimchi is an original Japanese dish which sets off the Korean president. Upon the Korean\'s president return home he sets upon a globalization plan for kimchi, which includes a nationwide "Kimchi Contest". Then, a lady named Jang-eun (Kim Jung-Eun) and her step-brother Sung-Chan (Jin Goo) compete in the Kimchi dish contest, with both siblings using their mother\'s kimchi recipe.',
        poster: "/l7ZrseQFMeBDNvsQn6LL5EF3R6F.jpg",
        posterHorizontal: "/AjYf2DUOA9vhSZZ5GTRatPCuOwN.jpg",
        voteAverage: 6.3,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80280,
        title: "[REC]³ Genesis",
        overview:
          "A pair of newlyweds must fight to survive when their wedding reception descends into chaos and carnage when their guests become infected by a virus that turns them into hungry zombies.",
        poster: "/tI1534q0Up7PBcLdXdFerLmIXn3.jpg",
        posterHorizontal: "/seixi70Y9P9uB1u5sYpptGDZVe8.jpg",
        voteAverage: 5.227,
        type: "movie",
        videoUrl: "NQckiIgNezw",
      },
      {
        id: 80304,
        title: "Casa De Mi Padre",
        overview:
          "Scheming of a way to save their father's ranch, the Alvarez brothers find themselves in a war with Mexico's most feared drug lord.",
        poster: "/kVCc7xwTAlckBofazrwIz8x1TXC.jpg",
        posterHorizontal: "/bTy0LQEXValfIemrLvE5dMJobE4.jpg",
        voteAverage: 5.38,
        type: "movie",
        videoUrl: "01IYDy2Gdk4",
      },
      {
        id: 80387,
        title: "Carol Channing: Larger Than Life",
        overview:
          "If Carol Channing didn't exist, no one could have made her up. One in a billion, Carol , at 89, remains an unstoppable, megawatt dynamo. Broadway diva extraordinaire is just the icing. Carol Channing hovered at the pinnacle of the entertainment world from the late-1950's through the 1960's and beyond, living life sensationally large. As Carol has observed, '...if you're lucky enough to have two hit shows, the world passes through your dressing room'. At 89, she remains irrepressible.",
        poster: "/qW1NG3KjNVAkPezdCXFHAI0cleP.jpg",
        posterHorizontal: null,
        voteAverage: 7.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80624,
        title: "The Godsend",
        overview:
          "An English family of six takes in a pregnant woman who disappears shortly after giving birth. They raise the baby girl as their own, but over the years the strange deaths of their children make them consider whether the little girl is more than she appears.",
        poster: "/hOTrOQ8pXTQhydtEDyRFI9Dn3w4.jpg",
        posterHorizontal: "/mLdkXarWPOV1wVbea2n4294rfve.jpg",
        voteAverage: 5.4,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 846433,
    title: "The Enforcer",
    overview:
      "A noir thriller set in Miami, the film follows an enforcer who discovers his femme fatale boss has branched out into cyber sex trafficking, putting a young runaway he’s befriended at risk. He sacrifices everything to save the young girl from the deadly organization he’s spent his life building.",
    poster: "/pXC8JJbfnRWtbD8i2yKFqqWEO4X.jpg",
    posterHorizontal: "/Aqldsq65Nj1KAkQD2MzkZsAk5N5.jpg",
    voteAverage: 7.3,
    type: "movie",
    videoUrl: "XmpK_5EOuGc",
    similar: null,
  },
  {
    id: 1013870,
    title: "Kids vs. Aliens",
    overview:
      "All Gary wants is to make awesome home movies with his best buds. All his older sister Samantha wants is to hang with the cool kids. When their parents head out of town one Halloween weekend, an all-time rager of a teen house party turns to terror when aliens attack, forcing the siblings to band together to survive the night.",
    poster: "/wQ53sO5n9LCFbssV3oQ4CuajL1L.jpg",
    posterHorizontal: "/cU7itLM8qmwMiaNnWsJPQLKe79j.jpg",
    voteAverage: 6.1,
    type: "movie",
    videoUrl: "3F_feNb4oYQ",
    similar: [
      {
        id: 72824,
        title: "Star Knight",
        overview:
          "A medieval alchemist (Klaus Kinski), knight (Harvey Keitel) and priest (Fernando Rey) mistake a flying-saucer alien for a dragon.",
        poster: "/4adApBaaSL047itQmqaDKhkidZq.jpg",
        posterHorizontal: "/vB4Sf9x8roCQvlW6TljjmWPW9Z.jpg",
        voteAverage: 4.2,
        type: "movie",
        videoUrl: "l4bpQWYkWA4",
      },
      {
        id: 80274,
        title: "Ender's Game",
        overview:
          "Based on the classic novel by Orson Scott Card, Ender's Game is the story of the Earth's most gifted children training to defend their homeplanet in the space wars of the future.",
        poster: "/hEioY3LlqBwvIpZeZuR1BMaAgv1.jpg",
        posterHorizontal: "/qGqlWb5izTPtFngBWdbJAEmninR.jpg",
        voteAverage: 6.585,
        type: "movie",
        videoUrl: "KecVAykkfCM",
      },
      {
        id: 80339,
        title: "Star Pilot",
        overview:
          "Aliens from the constellation Hydra crash-land on the island of Sardinia. A prominent scientist, his daughter, several young technicians, and a pair of Oriental spies are taken hostage by the beings so they can use them to repair their spaceship's broken engine. With that done, they take off towards their home planet, taking the earthlings with them. However, the humans attempt to mutiny against their captors, inadvertently sending their tiny spaceship hurtling into the infinite beyond...",
        poster: "/dGeSyK0F0tHcWDaRJ3Ipr7Gek9P.jpg",
        posterHorizontal: "/ot1YoSZeo7ejHlvvbkVDfl9UzbM.jpg",
        voteAverage: 4.3,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80583,
        title: "Alien Armageddon",
        overview:
          "For years, UFO sightings have been documented around the world. What were once mere sightings have now become brutal attacks of epic proportions. As the human race faces total annihilation with every major city destroyed only Los Angeles remains. Left with the task of saving humanity from extinction, a group of cowboys is the world s last stand in this Alien Armageddon.",
        poster: "/fpU1zag0F9RwMTeGG8NWPRqu8CG.jpg",
        posterHorizontal: "/cJPaIwNp6Ha00eRmMNbY2gIqZvd.jpg",
        voteAverage: 2.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 85865,
        title: "Alien Factor 2: The Alien Rampage",
        overview:
          "A small town is sealed in a electric forcefield by a blood thirsty rampaging killer cyborg alien and it's up to some towns folk and the sheriff's dept to stop it!",
        poster: "/7QA916c106tsEQ0gUSrNOBTMEvv.jpg",
        posterHorizontal: null,
        voteAverage: 3.9,
        type: "movie",
        videoUrl: "gSyAS2Da3GQ",
      },
      {
        id: 81244,
        title: "Alien Nation: The Enemy Within",
        overview:
          "When detectives Sikes and Francisco are presented with the mysterious death of an Eeno, Matt is stupefied to discover that George rudely snubs the case. He, like most newcomers, reviles the outcast Eenos. As the case unfolds, George has to reassess his prejudices, and George's family help save the city from an alien threat originating in an Eeno waste disposal facility.",
        poster: "/nCFxZcuTpeRC6n8fR2aPqU9KvJ.jpg",
        posterHorizontal: null,
        voteAverage: 5.9,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 653851,
    title: "Devotion",
    overview:
      "The harrowing true story of two elite US Navy fighter pilots during the Korean War. Their heroic sacrifices would ultimately make them the Navy's most celebrated wingmen.",
    poster: "/26yQPXymbWeCLKwcmyL8dRjAzth.jpg",
    posterHorizontal: "/5pMy5LF2JAleBNBtuzizfCMWM7k.jpg",
    voteAverage: 7.5,
    type: "movie",
    videoUrl: "nIvBBd8pU1s",
    similar: [
      {
        id: 80304,
        title: "Casa De Mi Padre",
        overview:
          "Scheming of a way to save their father's ranch, the Alvarez brothers find themselves in a war with Mexico's most feared drug lord.",
        poster: "/kVCc7xwTAlckBofazrwIz8x1TXC.jpg",
        posterHorizontal: "/bTy0LQEXValfIemrLvE5dMJobE4.jpg",
        voteAverage: 5.38,
        type: "movie",
        videoUrl: "01IYDy2Gdk4",
      },
      {
        id: 80387,
        title: "Carol Channing: Larger Than Life",
        overview:
          "If Carol Channing didn't exist, no one could have made her up. One in a billion, Carol , at 89, remains an unstoppable, megawatt dynamo. Broadway diva extraordinaire is just the icing. Carol Channing hovered at the pinnacle of the entertainment world from the late-1950's through the 1960's and beyond, living life sensationally large. As Carol has observed, '...if you're lucky enough to have two hit shows, the world passes through your dressing room'. At 89, she remains irrepressible.",
        poster: "/qW1NG3KjNVAkPezdCXFHAI0cleP.jpg",
        posterHorizontal: null,
        voteAverage: 7.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83542,
        title: "Cloud Atlas",
        overview:
          "A set of six nested stories spanning time between the 19th century and a distant post-apocalyptic future. Cloud Atlas explores how the actions and consequences of individual lives impact one another throughout the past, the present and the future. Action, mystery and romance weave through the story as one soul is shaped from a killer into a hero and a single act of kindness ripples across centuries to inspire a revolution in the distant future.  Based on the award winning novel by David Mitchell. Directed by Tom Tykwer and the Wachowskis.",
        poster: "/ereKZnGS7sVoPvu7lhZL2B4ZYFq.jpg",
        posterHorizontal: "/knY4ttZI6K4aiMyQ0kTekLHP2cc.jpg",
        voteAverage: 6.869,
        type: "movie",
        videoUrl: "ByehYal_cCs",
      },
      {
        id: 85841,
        title: "The Glory Brigade",
        overview:
          "During the Korean War Lt. Sam Pryor volunteers his platoon to escort Greek troops to perform a reconnaissance mission behind Communist lines. Due to his Greek heritage Pryor is initially proud to accompany the Greek contingent but his feelings change to scorn and mistrust when what he believes is cowardice shown by the Greek soldiers and their leaders results in the near annihiliation of his own platoon. An uneasy alliance is maintained between the US and Greek troops as the enemy's true objective is learned.",
        poster: "/jlGujx3EjvgKB4BWYulgnwYantJ.jpg",
        posterHorizontal: "/jF5HycY9A9Evj5Ds2AHZ9RXAQBr.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 82990,
        title: "Paranormal Activity 4",
        overview:
          "It has been five years since the disappearance of Katie and Hunter, and a suburban family witness strange events in their neighborhood when a woman and a mysterious child move in.",
        poster: "/na5tAslm1kGNcft083AIXMTOsYR.jpg",
        posterHorizontal: "/eq68gWGBtumauGYFV1FCJ20kXFU.jpg",
        voteAverage: 5.418,
        type: "movie",
        videoUrl: "P1wbwf0wayk",
      },
      {
        id: 81188,
        title: "Rise of the Guardians",
        overview:
          "When an evil spirit known as Pitch lays down the gauntlet to take over the world, the immortal Guardians must join forces for the first time to protect the hopes, beliefs and imagination of children all over the world.",
        poster: "/sW4qOa9yF0Ikg7lppncQ0n5UhKX.jpg",
        posterHorizontal: "/46IGtYNjpIvQYRIQlb2X493Wh8x.jpg",
        voteAverage: 7.359,
        type: "movie",
        videoUrl: "aPLiBxhoug0",
      },
    ],
  },
  {
    id: 788752,
    title: "Viking Wolf",
    overview:
      "After witnessing a grotesque murder at a party in her new town, a teenager starts having strange visions and bizarre desires.",
    poster: "/9CxWs95VQWlOAdgE0iadrz3RPwH.jpg",
    posterHorizontal: "/1pDYetDF3r9V7ZB5SeyoPcUkBiB.jpg",
    voteAverage: 5.6,
    type: "movie",
    videoUrl: "6sxnOLRGkhw",
    similar: [
      {
        id: 199450,
        title: "An Inlet of Muddy Water",
        overview:
          "Three short tales from stories by Ichiyo Higuchi. In one, a young woman is degraded by her family after an arranged marriage. Another deals with the troubles heaped upon a young servant by her family and the wealthy people who employ her. The final story tells of a prostitute and her hopes of finding a new, respectable life.",
        poster: "/7zUFTSQqxMLHfdEZNqYMWuqJZnu.jpg",
        posterHorizontal: null,
        voteAverage: 5.4,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 224350,
        title: "Twisted Tales",
        overview:
          'Horror anthology that takes on three stories. The first one entitled "Nothing But The Truth" deals with a compulsive liar and how his exaggerations get the better of him. Next is "The Shooting" about a man and how he is haunted by the spirit of his recently deceased abusive older brother. Finally, "Hungry Like A... Bat?" has a man who is trying to cope with being part human, part vampire, and part werewolf.',
        poster: "/bncxspfqCdS6wMMTV5ZovZ6wbiZ.jpg",
        posterHorizontal: null,
        voteAverage: 3.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 227257,
        title: "Monster High: Fright On!",
        overview:
          "See what happens when the student bodies of an all-vampire school and an all-werewolf school integrate with Monster High.",
        poster: "/69AyLiBvC65GoEDCLFGWDxtnLQu.jpg",
        posterHorizontal: "/esANMfH96Np2Aisrl42EgmPoYlH.jpg",
        voteAverage: 6.3,
        type: "movie",
        videoUrl: "9CW1Ih4Ej3A",
      },
      {
        id: 202386,
        title: "Badarna",
        overview:
          "It's a hot summer day in Näsviken, a small northern community on the verge of extinction, in structural change Sweden. The summer tourists gives some extra income but ironmonger Berglund can not keep the range of temporary guests require. Bud, whose wife Minni sunk into alcoholism due to her man's lack of interest. Bud consoles himself with a strong, viable woman with uncomplicated erotic habits.",
        poster: "/m8PHpXWalwaGLxXrdbw6f7ixhnR.jpg",
        posterHorizontal: "/aUMMaD2lMhX4oBxFHORVAdaMMfa.jpg",
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 205587,
        title: "The Judge",
        overview:
          "A successful lawyer returns to his hometown for his mother's funeral only to discover that his estranged father, the town's judge, is suspected of murder.",
        poster: "/tefUxj4Gg9hgQNgfEYd7kJQrIlD.jpg",
        posterHorizontal: "/9W02KZYKLoINpqpJ2yv8ATxR1AK.jpg",
        voteAverage: 7.308,
        type: "movie",
        videoUrl: "ZBvK6ni97W8",
      },
      {
        id: 203014,
        title: "The Day of the Wolves",
        overview:
          'A group of six thieves selected from different areas are sent a letter that promises them a minimum of $50,000 and includes a plane ticket. The letter instructs them to grow a beard. After being given a blindfolded ride from the airport, they arrive at a ghost town and meet with the boss (Number #1, Jan Murray). All of the "Wolves" are assigned a number, wear identical overalls and instructed never to take off the gloves that they are given. They are only to address eachother by their numbers; in that way, if one is caught, he can\'t rat-out the others. Number #1 reveals to them that they will take over a town, and clean it out. Using the ghost town for training, they develop their tactics to fleece the town.',
        poster: "/sPO4R6fZgBWlL9ZIeCRw7rWprmO.jpg",
        posterHorizontal: "/dJjEyJutYsHyqYaTmgW6Z1xLfqQ.jpg",
        voteAverage: 6.6,
        type: "movie",
        videoUrl: "9HBxYWBP9k8",
      },
    ],
  },
  {
    id: 931954,
    title: "Venus",
    overview:
      "Lucía, a club dancer on the run, takes refuge in a sinister building on the outskirts of Madrid where her sister Rocío lives with her daughter Alba.",
    poster: "/go41vTWzN5B17keXyBOYgc7kbyh.jpg",
    posterHorizontal: "/3LsHvo8VTSrcN7nZSy3jyNYGdCW.jpg",
    voteAverage: 6,
    type: "movie",
    videoUrl: "OhpYCMN2QsA",
    similar: [
      {
        id: 200085,
        title: "The Flu",
        overview:
          "A case of the flu quickly morphs into a pandemic. As the death toll mounts and the living panic, the government plans extreme measures to contain it.",
        poster: "/mvTXhTddHIZbOU9pmrcPODI1kRx.jpg",
        posterHorizontal: "/uFwnUQ3ZwE5EbBEDBzs1bRPlOx8.jpg",
        voteAverage: 7.526,
        type: "movie",
        videoUrl: "1BvKZMg2LjU",
      },
      {
        id: 204349,
        title: "Contracted",
        overview:
          "After being drugged and raped at a party, a young woman contracts what she thinks is an STD, but it's actually something much worse.",
        poster: "/fHtkFCkut6Qt8pfUBSpEKmK1fRT.jpg",
        posterHorizontal: "/9ZU024IGapsV7Rle7haBIZy6eBh.jpg",
        voteAverage: 5.333,
        type: "movie",
        videoUrl: "_t_uncP2XGE",
      },
      {
        id: 201272,
        title: "Lucrezia Giovane",
        overview:
          "In the early 16th century Italy is ruled by the powerful Borgia family, led by Cesare Borgia and his sister Lucrezia. In a ruthless power play, Cesare plots to have his sister’s husband murdered.",
        poster: "/lwxreMXyZaYiWruZeucyvPtvQ7I.jpg",
        posterHorizontal: null,
        voteAverage: 4.3,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 205556,
        title: "Fort Defiance",
        overview:
          "It's just after the Civil War and Ben Shelby arrives looking for Johnny Tallon whom he plans to kill. Shelby was the only survivor of a battle due to the cowardice of Tallon. Thinking Tallon dead, another man who lost a brother at the same battle arrives to kill Tallon's blind brother. Tallon arrives to find Shelby and his brother fleeing. Then they are attacked by Indians and Shelby and Tallon must now fight together postponing the inevitable showdown.",
        poster: "/cH7g9dHPXQ0j1rrxlXmqAtOUTBr.jpg",
        posterHorizontal: "/1OsSQChyyYJT40YqafaMnJ3vp8w.jpg",
        voteAverage: 6.3,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 192690,
        title: "Act Naturally",
        overview:
          "When two estranged stepsisters inherit their father's nudist colony, getting back to nature has never been so completely unnatural.",
        poster: "/j9CMa4v0cwSIHgSco7NtHK3TmaK.jpg",
        posterHorizontal: "/e38eIcSAoGVetxxaOHPP2ygJaf1.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "501j9bhlF5w",
      },
      {
        id: 209256,
        title: "Cuento de verano",
        overview:
          "After four years of living together, Léa dumps Mario. He is going to have to spend the loneliest summer of his life locked up in his Madrid apartment, with multiple broken bones. But this summer promises to be a journey in search of happiness, without leaving the downtown district. This trip will change the life of Mario, Chica, a mysterious young woman who appears on his doorstep, and Olmo the young and sassy neighbor, in love with Mario.",
        poster: "/bsvIprbRj1u05ll0csYrf8YwpWb.jpg",
        posterHorizontal: null,
        voteAverage: 3.3,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 542196,
    title: "Wolf Hound",
    overview:
      'Inspired by the real-life German special operations unit KG 200 that shot down, repaired, and flew Allied aircraft as Trojan horses, "Wolf Hound" takes place in 1944 German-occupied France and follows the daring exploits of Jewish-American fighter pilot Captain David Holden. Ambushed behind enemy lines, Holden must rescue a captured B-17 Flying Fortress crew, evade a ruthless enemy stalking him at every turn, and foil a plot that could completely alter the outcome of World War II.',
    poster: "/gHC0eFvXXNokP3sSNCTG2uks87R.jpg",
    posterHorizontal: "/vLPSvAt1CnfmDCeqG3zkFh0s6S4.jpg",
    voteAverage: 6.7,
    type: "movie",
    videoUrl: "Ld9joQp2aeU",
    similar: [
      {
        id: 199441,
        title: "The Bread of Love",
        overview:
          'Four Swedish volunteer soldiers are trapped in Russia. In front of them lies the front with enemy outposts and patrols, behind them the enemy minefields. Hope to return to their own lines decreases each day. Corpses of fallen, "dead of cold and hard as iron", forms the macabre landmarks in the winter landscape. Nearby is a burnt Russian village.',
        poster: null,
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 204345,
        title: "The Tango of Our Childhood",
        overview:
          "This is a story about the fate of a broken family, about the uncertainty of Ruben, who left his family, about attempts to return father, and about a series of funny, but also sad events that bring this dead-end story to a conclusion.",
        poster: "/wytKt4qV18BTLDbv7VsfqfBzWie.jpg",
        posterHorizontal: "/luHWRor3YWTwWym4rtIc7ymWXCy.jpg",
        voteAverage: 9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 204415,
        title: "The Fall of Italy",
        overview:
          "The setting is the islands off the Dalmatian coast of Yugoslavia, during WW II. The islands are controlled by occupying Italian forces, and a resistence movement of Communists is dedicated to sabotaging and ending the occupation. When a wealthy young man joins the resistence, he falls in love with a woman who turns out to be a spy for the Italians. As a result of his liaison and her activity, they are both executed by a Communist comrade - a previous friend. The comrade is dedicated to the hard-line policies of the resistence, until he himself falls in love with the daughter of a bourgeois landowner on the island - a landowner who has collaborated with the Italians. Neither the Italian occupying army (one officer is shown in an attempted rape scene) nor the resistence fighters are stereotyped forces for good or evil, but all are equally subject to the dehumanizing effects of war.",
        poster: "/nKTgzrydHPNkadZZgsD67fRbLBH.jpg",
        posterHorizontal: "/rH1iIRMIVPuC4IaZ6YZNb3tEBOJ.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 227306,
        title: "Unbroken",
        overview:
          "A chronicle of the life of Louis Zamperini, an Olympic runner who was taken prisoner by Japanese forces during World War II.",
        poster: "/djETrCXW11Fb5hEl7vvc3bfs3oc.jpg",
        posterHorizontal: "/aEpiew7x4CKpz5uZhfLGjaQ5Mkt.jpg",
        voteAverage: 7.443,
        type: "movie",
        videoUrl: "rGlsxVfCSyQ",
      },
      {
        id: 202432,
        title: "The Last Act",
        overview:
          "Albin Skoda embodies a frantic Adolf Hitler in his last days, scrambling to keep the Third Reich alive as morale within the bunker wanes and Berlin is encircled by enemy troops. Based on Michael A. Musmanno's book Ten Days to Die, Oscar Werner costars as fictional Nazi Hauptmann Wüst, a disillusioned middleman.",
        poster: "/yCSof65Utc8acwJqx4scJl8SUoW.jpg",
        posterHorizontal: "/ltCsAyevKrzwaWF36KbZHXzsO6p.jpg",
        voteAverage: 8.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 202433,
        title: "The Battle of the Eagles",
        overview:
          "The first Yugoslav Partisan air force unit. Loosely based on historical facts.",
        poster: "/nOIkyCkpaq967MIKWS9frbKoR5x.jpg",
        posterHorizontal: "/9Vle7Yr6xh1DWOzTf6y1hSuih4q.jpg",
        voteAverage: 6.2,
        type: "movie",
        videoUrl: "9cNPq_RM2ps",
      },
    ],
  },
] as BrowserProps["popularMoviesSimilar"];
