import { BrowserProps } from "pages/browse";

export default [
  {
    id: 100088,
    title: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    posterHorizontal: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    voteAverage: 8.8,
    type: "tv",
    videoUrl: "uLtkt8BonwM",
    similar: [
      {
        id: 19,
        title: "Planet of the Apes",
        overview:
          "Two astronauts and a sympathetic chimp friend are fugitives in a future Earth dominated by a civilization of humanoid apes. \n\nBased on the 1968 Planet of the Apes film and its sequels, which were inspired by the novel of the same name by Pierre Boulle.",
        poster: "/zxo5Vrd0oXgm9ZCz4r7Q3L8veWg.jpg",
        posterHorizontal: "/JrBiUtR2CwxZR5GMK5Z9dU7Wr4.jpg",
        voteAverage: 6.929,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 44,
        title: "Adventures of Sonic the Hedgehog",
        overview:
          "Follow the adventures of Sonic the Hedgehog, and his sidekick Tails, as they attempt to stop Dr. Robotnik and his array of robots from taking over the planet Mobius.",
        poster: "/xjhZhermBwZtWiPA7xT7Rli2tmD.jpg",
        posterHorizontal: "/da5qFYz4JT1d4kTwbU1Gf15TRBD.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "yTc5HNKNKBY",
      },
      {
        id: 547,
        title: "Medical Investigation",
        overview:
          'Medical Investigation was an American medical drama television series that began September 9, 2004, on NBC. It ran for 20 one-hour episodes before being cancelled in 2005. The series was co-produced by Paramount Network Television and NBC Universal Television Studio The former controls North American distribution rights, while the latter distributes outside North America.\n\nThe series featured the cases of an elite team of medical experts of the National Institutes of Health who investigate unusual public-health crises, such as sudden outbreaks of serious and mysterious diseases. In actuality, medical investigative duties in the United States are normally the responsibility of the Centers for Disease Control and Prevention and local health departments, while the NIH is primarily a disease-research and -theory organization.\n\nThe series existed in the same television universe as Third Watch and, by extension ER. A special two-part crossover event aired on February 18, 2005, establishing the television-universe connection by featuring the Third Watch and Medical Investigation teams working together in MI\'s Episode 17: "Half Life" and Third Watch\'s Episode 16 of the sixth season: "In the Family Way". The story was about a series of Marburg virus cases in New York.',
        poster: "/3bTy80VccV3suS9ywXryGakdG5y.jpg",
        posterHorizontal: null,
        voteAverage: 6.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 574,
        title: "Thunderstone",
        overview:
          "The year is 2020. Fifteen-year-old Noah lives with his family in the futuristic underground community of North Col. The world above is a frozen wasteland after a massive comet strike destroyed all other life in the world including the animals. One night, he accidentally time travels to the future and finds himself trapped in the year 2085 in a desolate desert place called Haven with a group of children, the Nomads, led by Arushka.",
        poster: "/QjNZcyIxRVTvx2vhsfP3rMcp1o.jpg",
        posterHorizontal: "/gXZtfUyhp68COVoPVCqc2Pa1nQB.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1571,
        title: "The Legend of Zelda",
        overview:
          "The young adventurer Link and Princess Zelda protect Hyrule from the forces of Ganon, an evil wizard who desires the kingdom's treasured Triforce of Wisdom.",
        poster: "/oddre5aHiXSMnTMtMBPyv12rjbC.jpg",
        posterHorizontal: "/gyZRUabOxDnf2XKeCg4S8KGNmRl.jpg",
        voteAverage: 5.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1402,
        title: "The Walking Dead",
        overview:
          "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
        poster: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
        posterHorizontal: "/zaulpwl355dlKkvtAiSBE5LaoWA.jpg",
        voteAverage: 8.113,
        type: "tv",
        videoUrl: "BXqUmob-nfg",
      },
    ],
  },
  {
    id: 130542,
    title: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    poster: "/7wuKrFvbX7kAIF0ctotARsqayPo.jpg",
    posterHorizontal: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    voteAverage: 4.8,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 120056,
        title: "Where Have You Been?",
        overview:
          "Widower Ramzi is going to marry Nisrine who is a lot younger than him. This shocks his son Jad and his girlfriend Sila as well as the entire family, who will do their best to get rid of Nisrine and keep her way from the family.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "zA-Qph3zPb4",
      },
      {
        id: 120089,
        title: "SPY x FAMILY",
        overview:
          "World peace is at stake and secret agent Twilight must undergo his most difficult mission yet—pretend to be a family man. Posing as a loving husband and father, he’ll infiltrate an elite school to get close to a high-profile politician. He has the perfect cover, except his wife’s a deadly assassin and neither knows each other’s identity. But someone does, his adopted daughter who’s a telepath!",
        poster: "/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
        posterHorizontal: "/yreuPT1RYFvWkQ3gjnjRP8vAq3o.jpg",
        voteAverage: 8.664,
        type: "tv",
        videoUrl: "JP6vBnazpWI",
      },
      {
        id: 123130,
        title: "The Sweet Burden",
        overview: "",
        poster: "/1j3UqshFRPPM8yzTSLasoGKMThU.jpg",
        posterHorizontal: "/uiLy8vAISWoYBNKVLxKVIRbChk6.jpg",
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 123616,
        title: "Home Sweet Home",
        overview: "",
        poster: "/29g7e8DDv6syloP1iCEn6LAkRp6.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 123698,
        title: "Generation Slash",
        overview:
          'Chan Zhan Tung, was originally the owner of the "All-Knowing Detective Agency". The company subsequently changed hands, and Cheung Lok Hang seized all rights. Lee Jin Hiu  then joined the company. Chan Ka Hei, Cheung Lok Hang, and Lee Jin Hiu later changed the position of the detective agency from a detective agency that purely collects evidence for customers to "Unlimited Generation Slash".',
        poster: "/qot5ClGAOB3HfotS8xcXqK9fKQq.jpg",
        posterHorizontal: "/nhFJOJn9ymSueDXDVJALuBwANOC.jpg",
        voteAverage: 0,
        type: "tv",
        videoUrl: "PL0vWiVF1xU",
      },
      {
        id: 129473,
        title: "Young Lady and Gentleman",
        overview:
          "Lee Young Kook is a widower with three children. He still hasn’t gotten over the death of his wife. He decides to hire Park Dan Dan as a live-in tutor for his kids and he becomes attracted to her. Meanwhile, Park Dan Dan has bright and positive personality despite her harsh situation.",
        poster: "/vyahc0o4Xfbw0pZdz5QiqXxDRNH.jpg",
        posterHorizontal: "/2x29EaZfUq6wym6KGATKTBC7LuX.jpg",
        voteAverage: 8.1,
        type: "tv",
        videoUrl: "kmskxT5j8Pk",
      },
    ],
  },
  {
    id: 197109,
    title: "Yeh Rishta Kya Kehlata Hai",
    overview:
      "A personal tragedy creates a rift in Abhimanyu and Akshara's marital life. Years later, when destiny offers a second chance, will the duo embrace love?",
    poster: "/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg",
    posterHorizontal: "/igmqMTV2Ukf5Id4WwQi7MUAJQAX.jpg",
    voteAverage: 4.5,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 1922,
        title: "All in the Family",
        overview:
          "Archie Bunker, a working class bigot, constantly squabbles with his family over the important issues of the day.",
        poster: "/s2Y9QWyuyjRP78DZsatknEjn0iN.jpg",
        posterHorizontal: "/qP6w5T2aMTTkIW5qFqziWhgYlPu.jpg",
        voteAverage: 7.8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 877,
        title: "Caprica",
        overview:
          "Set 58 years before Battlestar Galactica, Caprica follows two rival families - the Graystones and the Adamas - as they grow, compete, and thrive in the vibrant world of the peaceful 12 Colonies, living in a society close to our own. Entangled in the burgeoning technology of artificial intelligence and robotics that will eventually lead to the creation of the Cylons, the two houses go toe-to-toe, blending action with corporate conspiracy and sexual politics.",
        poster: "/wGCdHYsx0aY5Z5236XTC6JQMpNn.jpg",
        posterHorizontal: "/1KUT5MsvWCKapd1TLVzf3xnpCev.jpg",
        voteAverage: 6.915,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1274,
        title: "Six Feet Under",
        overview:
          "A darkly comic look at members of a dysfunctional L.A. family that run a funeral business. \n\nWhen death is your business, what is your life? For the Fisher family, the world outside of their family-owned funeral home continues to be at least as challenging as--and far less predictable than--the one inside.",
        poster: "/rpLte0UpxHNVx4ppTwTqFhT0ACn.jpg",
        posterHorizontal: "/x2b9PSCBX9u46nA7ZNZQiDwTcfc.jpg",
        voteAverage: 8.101,
        type: "tv",
        videoUrl: "E3gYi-KvKug",
      },
      {
        id: 2432,
        title: "Taken",
        overview:
          "The show takes place from 1944 to 2002 and follows the lives of three families: the Crawfords, who seek to cover up the Roswell crash and the existence of aliens; the Keys, who are subject to frequent experimentation by the aliens; and the Clarkes, who sheltered one of the surviving aliens from the crash.",
        poster: "/dFMBPZvgbvhnpCW8YfYakNB2xrT.jpg",
        posterHorizontal: "/85VdFnoD33M9H2QW43QVOnpnKxU.jpg",
        voteAverage: 7.518,
        type: "tv",
        videoUrl: "ury6T7Ajuho",
      },
      {
        id: 3469,
        title: "Minder",
        overview:
          "This comedy drama series featured Terry McCann, a former boxer with a conviction for G.B.H., and Arthur Daley, a second-hand car dealer with an eye for a nice little earner. Alongside his many business ventures, Arthur would regularly hire Terry out as a minder or bodyguard, later replaced by nephew, Ray Daley.",
        poster: "/4s9hiyQvTaMe1bK91HRCTgDTAoF.jpg",
        posterHorizontal: "/gZeLjJnY8lpRUgi4RffcULZ6R4O.jpg",
        voteAverage: 7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3333,
        title: "Steptoe and Son",
        overview:
          "Steptoe and Son is a British sitcom written by Ray Galton and Alan Simpson about a father and son played by Wilfred Brambell and Harry H. Corbett who deal in selling used items. They live on Oil Drum Lane, a fictional street in Shepherd's Bush, London. Four series were broadcast by the BBC from 1962 to 1965, followed by a second run from 1970 to 1974. Its theme tune, \"Old Ned\", was composed by Ron Grainer. The series was voted 15th in a 2004 BBC poll to find Britain's Best Sitcom. It was remade in the US as Sanford and Son, in Sweden as Albert & Herbert and in the Netherlands as Stiefbeen en zoon. In 1972 a movie adaptation of the series, Steptoe and Son, was released in cinemas, with a second Steptoe and Son Ride Again in 1973.",
        poster: "/hhpwjPICU1wcUegTFvRCCF9UpKA.jpg",
        posterHorizontal: "/wCI7tLrSpA6bOSwIPt19DGN21ap.jpg",
        voteAverage: 7.7,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 153870,
    title: "Shark Tank India",
    overview:
      "Aspiring entrepreneurs from India pitch their business models to a panel of investors and persuade them to invest money in their idea.",
    poster: "/kDZhUEwqWrRkG6W2Y0WIYTstb0K.jpg",
    posterHorizontal: "/tLL91JBiCCvBF7oKSN6dFR7yd8c.jpg",
    voteAverage: 7.2,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 2571,
        title: "Cutting It",
        overview:
          "Allie Henshall and Gavin Ferraday are partners in love and business. They own Henshall Ferraday hair salon, where Allie's sisters Darcey and Sydney work alongside them. As Allie and Gavin consider taking over a vacant property across the road, they are rocked by the news that a rival hairdresser has bought it. To make matters worse, Allie discovers that the new salon, Blade Runner, is run by her ex, Finn, and his wife, Mia Bevan. Finn fathered the child Allie claimed to have aborted. He left her when he found out she was pregnant, but he's back in town to try and woo Allie.",
        poster: "/kgJZ03CYjCAzyGl9kT6q5lkcyAJ.jpg",
        posterHorizontal: "/yIOahUpWj5Rfv7PhyL4aaUxpHXy.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2910,
        title: "Big Shots",
        overview:
          "Four friends are at the top of their game...until the women in their lives enter the room. Lines between boardroom and bedroom blur when these competitive but dysfunctional CEOs take refuge in their friendship, discussing business, confiding secrets, seeking advice and supporting each other through life's surprising twists and turns.",
        poster: "/ztJVBy8C5afXpSh6sdzxIcnHuix.jpg",
        posterHorizontal: "/qCe5K80okyUZFYso6WR0e3xSHXd.jpg",
        voteAverage: 7.4,
        type: "tv",
        videoUrl: "cUZWg3jXlIk",
      },
      {
        id: 3333,
        title: "Steptoe and Son",
        overview:
          "Steptoe and Son is a British sitcom written by Ray Galton and Alan Simpson about a father and son played by Wilfred Brambell and Harry H. Corbett who deal in selling used items. They live on Oil Drum Lane, a fictional street in Shepherd's Bush, London. Four series were broadcast by the BBC from 1962 to 1965, followed by a second run from 1970 to 1974. Its theme tune, \"Old Ned\", was composed by Ron Grainer. The series was voted 15th in a 2004 BBC poll to find Britain's Best Sitcom. It was remade in the US as Sanford and Son, in Sweden as Albert & Herbert and in the Netherlands as Stiefbeen en zoon. In 1972 a movie adaptation of the series, Steptoe and Son, was released in cinemas, with a second Steptoe and Son Ride Again in 1973.",
        poster: "/hhpwjPICU1wcUegTFvRCCF9UpKA.jpg",
        posterHorizontal: "/wCI7tLrSpA6bOSwIPt19DGN21ap.jpg",
        voteAverage: 7.7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5655,
        title: "Badger or Bust",
        overview:
          "Ex-Apprentice star Ruth Badger troubleshoots struggling companies and turns around their sales team.",
        poster: "/rCk4XakxL2UdUQKyYjHzigGOKik.jpg",
        posterHorizontal: "/jdW4kSlspkZ5VzOmVIjYAB8GXJH.jpg",
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 7750,
        title: "Tabatha Takes Over",
        overview:
          "The straight-talking, perfectly coifed Tabatha Coffey lends her sound advice and styling expertise to help desperate salon owners turn their struggling businesses around.",
        poster: "/d2OaqyIYRUxPeHEftnXh7IfbAiY.jpg",
        posterHorizontal: "/ngVGfMk4KLuLf3x0ITvpnS7WpXf.jpg",
        voteAverage: 6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 12453,
        title: "Desmond's",
        overview:
          "Desmond's was a British television situation comedy broadcast by Channel 4 from 1989 to 1994. With 71 episodes, Desmond's became Channel 4's longest-running sitcom. The first series was shot in 1988, with the first episode broadcast in January 1989. The show was made in and set in Peckham, London, England and featured a predominantly Black British Guyanese cast.\n\nConceived and co-written by Trix Worrell, and produced by Charlie Hanson and Humphrey Barclay, this series starred Norman Beaton as barber Desmond Ambrose. Desmond's shop was a gathering place for an assortment of local characters.",
        poster: "/h36V4F5FltqnMY2P9eRng3cm6yM.jpg",
        posterHorizontal: "/uEuf5siLk2tlxx3tfjYZvvrqL9W.jpg",
        voteAverage: 7,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 204095,
    title: "Mar do Sertão",
    overview: "",
    poster: "/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg",
    posterHorizontal: "/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg",
    voteAverage: 4.3,
    type: "tv",
    videoUrl: "no-url",
    similar: null,
  },
  {
    id: 113218,
    title: "Imlie",
    overview:
      "All Imlie wanted was to create a name for herself in the city. But upon her arrival, she finds herself caught in the middle of Aditya and Malini's love story.",
    poster: "/brajFHvqeitbp7ifevWpFpirS4S.jpg",
    posterHorizontal: "/ymkFaEO0UdYXKIgcWZ23TlYIRD9.jpg",
    voteAverage: 5.7,
    type: "tv",
    videoUrl: "zHuYR95l770",
    similar: [
      {
        id: 1892,
        title: "The Fresh Prince of Bel-Air",
        overview:
          "Will, a street-smart teenager, moves from the tough streets of West Philly to posh Bel-Air to live with his Uncle Philip, Aunt Vivian, his cousins — spoiled Hilary, preppy Carlton and young Ashley — and their sophisticated British butler, Geoffrey. Though Will’s antics and upbringing contrast greatly with the upper-class lifestyle of his extended relatives, he soon finds himself right at home as a loved part of the family.",
        poster: "/2xjqlhBLfwVgmqM7EGfxRpNGm3E.jpg",
        posterHorizontal: "/5HgdSUIGeHQ4osZVACxB4Of2M7e.jpg",
        voteAverage: 7.969,
        type: "tv",
        videoUrl: "_u6vYpbfCmQ",
      },
      {
        id: 2352,
        title: "The Nanny",
        overview:
          "Fran, fresh out of her job as a bridal consultant in her boyfriend’s shop, first appears on the doorstep of Broadway producer Maxwell Sheffield peddling cosmetics, and quickly stumbled upon the opportunity to become The Nanny for his three children. But soon Fran, with her offbeat nurturing and no-nonsense honesty, touches Maxwell as well as the kids.",
        poster: "/ArcJvQ27Bhn5FiyfAphS2eNEMhb.jpg",
        posterHorizontal: "/eSMHmpK5KrAuvy6dwK0df7Nbi3m.jpg",
        voteAverage: 8.144,
        type: "tv",
        videoUrl: "OHK-1WTRQAM",
      },
      {
        id: 966,
        title: "Hollyoaks",
        overview:
          "The daily soap that follows the loves, lives and misdemeanours of a group of people living in the Chester village of Hollyoaks where anything could, and frequently does, happen...",
        poster: "/5sbMgcbpzZn8aKETeanrKDANzdM.jpg",
        posterHorizontal: "/r8CGqB8IJNbA1IruHWquS7YttNB.jpg",
        voteAverage: 5.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 52,
        title: "That '70s Show",
        overview:
          "Crank up the 8-track and flash back to a time when platform shoes and puka shells were all the rage in this hilarious retro-sitcom. For Eric, Kelso, Jackie, Hyde, Donna and Fez, a group of high school teens who spend most of their time hanging out in Eric’s basement, life in the ‘70s isn’t always so groovy. But between trying to figure out the meaning of life, avoiding their parents, and dealing with out-of-control hormones, they’ve learned one thing for sure: they’ll always get by with a little help from their friends.",
        poster: "/laEZvTqM80UaplUaDSCCbWhlyEV.jpg",
        posterHorizontal: "/3zRUiH8erHIgNUBTj05JT00HwsS.jpg",
        voteAverage: 7.971,
        type: "tv",
        videoUrl: "b1za7d3KvHw",
      },
      {
        id: 1566,
        title: "All of Us",
        overview:
          "Robert James, an entertainment reporter for a local Los Angeles television station, is handsome, smart and thoroughly modern in his thinking. Recently divorced from the somewhat self-absorbed Neesee, the mother of their endearing 6-year-old son, Robert refuses to buy into the old stereotype that being divorced means you can't get along with the ex.",
        poster: "/fQKE9RE2U0EWiFT8f3FVaowokyk.jpg",
        posterHorizontal: "/l6RgKNzSlGQmCNDDqshk5qszQlA.jpg",
        voteAverage: 7.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1638,
        title: "Providence",
        overview: "Providence is an American television drama series.",
        poster: "/720tV0QbG7s4EKxfcBRXMURPgBA.jpg",
        posterHorizontal: null,
        voteAverage: 6.6,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 209117,
    title: "Never Give Up",
    overview: "",
    poster: "/zU0MgcYQuMvB4bAqcqi7gDcWQKm.jpg",
    posterHorizontal: "/fMG9ta3iXZDxDInCcrEbcMkkARc.jpg",
    voteAverage: 6,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 3207,
        title: "American Heiress",
        overview:
          "American Heiress is a telenovela which debuted on March 13, 2007 at 8 p.m. ET/7 p.m. CT on the American television network MyNetworkTV. This romantic melodrama tells the story of a roughneck pilot and a pampered heiress who survive a plane crash. The show was produced by Twentieth Television, based on the 2004 TV Azteca series La Heredera.\n\nHeiress was the last series produced for MyNetworkTV's original all-telenovela format. When the network dropped the serial after the July 18, 2007 broadcast, most episodes were left unaired. 20th Century Fox Home Entertainment has not announced plans to release this series on DVD and/or Blu-ray. All 65 episodes aired overseas.",
        poster: "/9bel6c4661LLb4SyZTNZvCzi1ZQ.jpg",
        posterHorizontal: null,
        voteAverage: 7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3241,
        title: "Suppli",
        overview:
          "Minami is a 27-year-old female office worker in an advertisement agency. Though she has a boyfriend, she spends the majority of her time working and appears to feel ambivalent about the relationship at best. When the boyfriend finally breaks up with her, it's the push she needs to start a social life with her co-workers. In-office romances soon follow. Much of the story is told through Minami's thoughts, which are full of self-doubt.",
        poster: "/tS5X6AolvRL2Xw8A9aPoiTT99gN.jpg",
        posterHorizontal: null,
        voteAverage: 7.7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3926,
        title: "Hello! My Lady",
        overview:
          "Hello! Miss is a 2007 South Korean television series starring Lee Da-hae, Lee Ji-hoon, Ha Seok-jin and Yeon Mi-joo. Based on Lee Ji-wan's novel Five Kimchi Mandu, the series aired on KBS2 from March 19 to May 8, 2007 on Mondays and Tuesdays at 21:55 for 16 episodes.",
        poster: "/lSq14QU6DELAA2Fu6j8uumdKgNV.jpg",
        posterHorizontal: "/nbaafJzSNFnBCsdlvq1CT0uVpKc.jpg",
        voteAverage: 8.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4184,
        title: "Deceptions",
        overview:
          "La Usurpadora is a Mexican romantic drama telenovela produced by Salvador Mejia Alejandre and originally broadcast on Canal de las Estrellas from February 9 to July 24, 1998. It starred Gabriela Spanic and Fernando Colunga, and was based on La Intrusa, a novela originally broadcast in Venezuela which was its self a remake of Radio Caracas Television's 1971 telenovela La Usurpadora, which was starred by Marina Baura and Raúl Amundaray. This was one of the last telenovelas to feature Libertad Lamarque, who here portrayed the character of Abuela Piedad Bracho. The show's premise revolves around a pair of twin sisters who were separated when they were young, and as adults the younger sister is forced to act as a \"replacement\" for her wealthy twin who wants to temporarily leave her husband and his family to enjoy a life of luxury with multiple lovers. The telenovela had huge success in Mexico and has been exported and ported to various languages across the world.",
        poster: "/1JKCAbqIFUf5aQ1R9vfrsiIJCFf.jpg",
        posterHorizontal: "/7isN2RSPLTQ2yquIemmiuTf7fql.jpg",
        voteAverage: 7.438,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3500,
        title: "RBD: The Family",
        overview: "About the fictional lives of the Mexican group RBD.",
        poster: "/wqijX0thOJo6LPKHx4unhHP2kcX.jpg",
        posterHorizontal: "/8Hw535C9ILNl2gWLiNU2onvn9YH.jpg",
        voteAverage: 5.9,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3897,
        title: "El Pantera",
        overview:
          "El Pantera is a Mexican television series released by Canal 5. It is based on a comic book of the same name. It narrates the life of Gervasio, a young man who fights crime in Mexico City. The title role is performed by Luis Roberto Guzmán.\n\nThe series started airing on May 2007, and is filmed in Mexico City under the direction of producers Rodolfo de Anda and Alexis Ayala. It currently airs its third season Mondays on Canal 5 at 10:00pm and on cable TV channel Galavisión Tuesdays at 21:30pm.\n\nThe character of El Pantera was created in the 70's by the writer Daniel Muñoz and artist Juan Alba for Mundo Vid. A novel called El Pantera, or La Noche del Pantera was written by Muñoz in the 90's, followed by El Misterio de la Amenaza Negra.",
        poster: "/dhD7HAC5xH8OZkjMjwtglSrjikt.jpg",
        posterHorizontal: "/4HyIANr1H8P7mSmGupOVcKAjOK2.jpg",
        voteAverage: 8.4,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 206706,
    title: "Soar High!",
    overview:
      "Iwakura Mai lives with her parents Kota and Megumi and older brother Haruto. Her father Kota runs a small factory in Higashi Osaka, a district that is known for its craftsmen. Mai is shy and withdrawn. But when she visits her grandmother Shoko who lives on Nagasaki’s Goto Islands which has a rich natural environment, she is entranced by the Baramon kites that catch the wind and soar high in the sky. Wanting to fly high in the sky like these kites, Mai’s longing swells into a dream to become a pilot. Even though she works hard, the path to getting there is tougher than she had imagined. As Mai deepens her ties with the people living in her two hometowns of Higashi Osaka and Goto, her dream eventually takes a new form. She gathers enthusiastic friends to build a small electric plane that can fly to and from the islands. Her dream becomes a wing that carries everyone’s dreams and takes off.",
    poster: "/9eeqetibf0GeXEDpC4vYnU324v8.jpg",
    posterHorizontal: "/fNe1mUuB7fqd4owhgUXkwSNmd9q.jpg",
    voteAverage: 5,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 5299,
        title: "Life Goes On",
        overview:
          "Life Goes On is a television series that aired on ABC from September 12, 1989, to May 23, 1993. The show centers on the Thatcher family living in suburban Chicago: Drew, his wife Elizabeth, and their children Paige, Rebecca, and Charles, who is known as Corky. Life Goes On was the first television series to have a major character with Down syndrome.",
        poster: "/6a27QlSY2oC87OGX48lUp0J9SiK.jpg",
        posterHorizontal: "/3jIJiFydvdMnjTmjgYJpUax93QV.jpg",
        voteAverage: 6.8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4550,
        title: "7th Heaven",
        overview:
          "Reverend Eric Camden and his wife Annie have always had their hands full caring for seven children, not to mention the friends, sweethearts and spouses that continually come and go in the Camden household.",
        poster: "/s6mkZKanKim3VGUIxR2gGGf9jn0.jpg",
        posterHorizontal: "/poaxhWMnvrMeEmG6j3wLWNhZvJj.jpg",
        voteAverage: 6.497,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4330,
        title: "Millennium",
        overview:
          "A retired FBI serial-profiler joins the mysterious Millennium Group, a team of underground ex-law enforcement experts dedicated to fighting against the ever-growing forces of evil and darkness in the world.",
        poster: "/qi69yoYHNL30Mznult8mQc2dngu.jpg",
        posterHorizontal: "/7cmCid1B70AwhbdPpKvSVxAyqll.jpg",
        voteAverage: 7.741,
        type: "tv",
        videoUrl: "PglmFXc5ETw",
      },
      {
        id: 5187,
        title: "That's Life",
        overview:
          "That's Life is an American comedy-drama series created by Diane Ruggiero, that was broadcast on CBS from October 1, 2000 to January 26, 2002.",
        poster: "/2wWwNQXPVamIPxbMBJbG6g4QIgq.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5891,
        title: "Bastard Boys",
        overview:
          "Bastard Boys is an Australian television miniseries broadcast on the ABC in 2007. It tells the story of the 1998 Australian waterfront dispute. The script, published by Currency Press, won the 2007 Queensland Premier's Literary Award for Best Television Script.",
        poster: "/sRzD9MycG1FXX2ieTdQIdkfPyPb.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1920,
        title: "Twin Peaks",
        overview:
          "The body of Laura Palmer is washed up on a beach near the small Washington state town of Twin Peaks. FBI Special Agent Dale Cooper is called in to investigate her strange demise only to uncover a web of mystery that ultimately leads him deep into the heart of the surrounding woodland and his very own soul.",
        poster: "/lA9CNSdo50iQPZ8A2fyVpMvJZAf.jpg",
        posterHorizontal: "/j5w04XEuFv85N3RIovXBJIHxjSb.jpg",
        voteAverage: 8.287,
        type: "tv",
        videoUrl: "q040A3z1W08",
      },
    ],
  },
  {
    id: 208249,
    title: "Game of Witches",
    overview:
      "Yu Kyung is a successful woman who is proficient enough to become an executive director of Chunha Group when she started as a secretary. She recently found out her daughter is alive, so she plans to get her back and take her revenge. Meanwhile, Hye Soo is a strong girl who faces challenges head-on. She has a daughter with Ji Ho, and she would do anything for her. However, she gets tragically betrayed by Ji Ho, the love of her life, over power and money. How will those two mothers end their fierce revenge?",
    poster: "/9bTjPzX48VZGalKEBI6tiknUyLI.jpg",
    posterHorizontal: "/wdtM9fguzCuDVvpR1BvRw3AEmPG.jpg",
    voteAverage: 6,
    type: "tv",
    videoUrl: "1k03CJTrOLg",
    similar: [
      {
        id: 4453,
        title: "The Hogan Family",
        overview:
          "The Hogan Family is an American television situation comedy that aired on NBC from March 1, 1986 to May 7, 1990, and on CBS from September 15, 1990 until July 20, 1991. It was produced by Miller-Boyett Productions, along with Tal Productions, Inc., and in association with Lorimar Productions, Lorimar-Telepictures and Lorimar Television.\n\nThe show was originally titled Valerie and starred Valerie Harper as a mother trying to juggle her career with raising her three sons by her often-absent airline-pilot husband. Harper was written out of the series after the second season because of a dispute with the show's producers. Sandy Duncan joined the cast as the boys' aunt, who moved in and became their surrogate mom. During the show's third season, the series was known as Valerie's Family: The Hogans, then simply as The Hogan Family.",
        poster: "/2deFhQTN01DGG2ys9tNmRRB4SsY.jpg",
        posterHorizontal: "/aNVkp97dJDYkscOIK1PxVb5NEL0.jpg",
        voteAverage: 7.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 33847,
        title: "The Talk",
        overview:
          "A panel of well-known news and entertainment personalities discussing current events, pop culture, contemporary issues, family, celebrity and the trending topics of the day.",
        poster: "/wHMDZ3nVHCYGnxeoRZrPI0N9SSt.jpg",
        posterHorizontal: "/gLPMlQiHISZG7aajzmZSJN6oM7G.jpg",
        voteAverage: 2.7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 34633,
        title: "Mother",
        overview:
          "Yasuko Matsuyuki plays the part of Nao Suzuhara, an elementary school teacher. When she realizes that one of the female students is receiving abuse from her mother, Nao's maternal instincts kick in, and she impulsively decides to bring the girl into her own care. Serving as a substitute mother, Nao takes the child on a trip from Hokkaido to Tokyo, and the two experience various events together along the way.",
        poster: "/jJzMl1jW1WC8WOPTpiFc9KDGgcE.jpg",
        posterHorizontal: "/m4UjSDLVUH8j500rj532DSQqDWF.jpg",
        voteAverage: 9.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 9789,
        title: "The Mommies",
        overview:
          "The Mommies is an American sitcom that aired on NBC from September 1993 to June 1995. Produced by Paramount Television, the series ran for two seasons with a total of 38 episodes.",
        poster: "/40k5Kb3nkUxhiLE74al0kP2NUrW.jpg",
        posterHorizontal: null,
        voteAverage: 7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 8186,
        title: "In the Motherhood",
        overview:
          "Rosemary, Jane and Emily try to juggle motherhood, work, friendships and love lives in an overly complicated modern world.",
        poster: "/h9nmn8EG26Xl3GmDKc9olQtPKsK.jpg",
        posterHorizontal: "/hXQZdXHwuZ2XJOef3XHtUGe5yit.jpg",
        voteAverage: 0,
        type: "tv",
        videoUrl: "aE2f8jXEWbY",
      },
      {
        id: 7419,
        title: "Rita Rocks",
        overview:
          "Rita Rocks is a Lifetime original sitcom that ran from October 20, 2008 to December 7, 2009. It is the network's first original comedy in over a decade. The series debuted alongside re-runs of Reba as part of a new comedy hour for Tuesday nights, which later changed to Monday nights. The show stars Nicole Sullivan as Rita, Tisha Campbell-Martin, Richard Ruccolo, Raviv Ullman, and Kelly Gould.\n\nOn January 11, 2010, Lifetime cancelled the series after two seasons due to low ratings.",
        poster: "/w2RWvuyv06aLQ5iGSlmIgvynEA7.jpg",
        posterHorizontal: null,
        voteAverage: 5.7,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 210734,
    title: "Leandro Díaz",
    overview: "",
    poster: "/d6voDsM0it0GPnhfzXiHWLaX0ff.jpg",
    posterHorizontal: "/7fuUHCDYB59uZzTQK3BYFCf9387.jpg",
    voteAverage: 4.5,
    type: "tv",
    videoUrl: "no-url",
    similar: null,
  },
  {
    id: 209326,
    title: "Rajjo",
    overview: "",
    poster: "/rdNwXdMDVDvjOlcXCPOR3m9t43r.jpg",
    posterHorizontal: "/1aQ0ETcIXFeC0uGcK7NvTg90zWi.jpg",
    voteAverage: 5.1,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 5187,
        title: "That's Life",
        overview:
          "That's Life is an American comedy-drama series created by Diane Ruggiero, that was broadcast on CBS from October 1, 2000 to January 26, 2002.",
        poster: "/2wWwNQXPVamIPxbMBJbG6g4QIgq.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5299,
        title: "Life Goes On",
        overview:
          "Life Goes On is a television series that aired on ABC from September 12, 1989, to May 23, 1993. The show centers on the Thatcher family living in suburban Chicago: Drew, his wife Elizabeth, and their children Paige, Rebecca, and Charles, who is known as Corky. Life Goes On was the first television series to have a major character with Down syndrome.",
        poster: "/6a27QlSY2oC87OGX48lUp0J9SiK.jpg",
        posterHorizontal: "/3jIJiFydvdMnjTmjgYJpUax93QV.jpg",
        voteAverage: 6.8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 11577,
        title: "The Big Valley",
        overview:
          "The Big Valley is an American western television series which ran on ABC from September 15, 1965, to May 19, 1969. The show stars Barbara Stanwyck, as the widow of a wealthy nineteenth century California rancher. It was created by A.I. Bezzerides and Louis F. Edelman, and produced by Levy-Gardner-Laven for Four Star Television.",
        poster: "/5J323H8Dl0dX6IEsMXhaxcLIQW5.jpg",
        posterHorizontal: "/v57TanoRlAwBye6UOF1s6O7GFDf.jpg",
        voteAverage: 5.833,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 15428,
        title: "Shararat - Thoda Jaadu, Thodi Nazaakat",
        overview:
          "The story revolves around how different people in the family adjust to the magical powers of naani and her daughters, who use their magical powers for their needs.",
        poster: "/qpOmGsDpU25UQZlACpvzm19DNng.jpg",
        posterHorizontal: "/hAfCSfQfhUxSQCKDq4Ieody5whv.jpg",
        voteAverage: 6.2,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 7097,
        title: "United States of Tara",
        overview:
          'Tara\'s multiple personalities include "T" the wild-child teenager, "Buck" the rough and tumble biker dude, and "Alice" the type-A homemaker. But with a family that loves her just the way she is, Tara never gives up hope that someday she can just be herself.',
        poster: "/vKqCZytdJePDTp0GFLDa1XqT2MW.jpg",
        posterHorizontal: "/2tdnW8Z6rW5kFqI8rwEH2acONm6.jpg",
        voteAverage: 7.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 21762,
        title: "Parenthood",
        overview:
          "The trials and tribulations of the very large, colorful and imperfect Braverman family.",
        poster: "/9KjKLJrrUI1sU9bNsQaQ5H8kTyY.jpg",
        posterHorizontal: "/72zLfNDaL8JpfLDwmQ2b8DPbeHc.jpg",
        voteAverage: 7.305,
        type: "tv",
        videoUrl: "o_cblVvo5bg",
      },
    ],
  },
  {
    id: 209807,
    title: "Mi Secreto",
    overview: "",
    poster: "/v4lRzvk5eTtSStoRoihd6KsWfVh.jpg",
    posterHorizontal: "/oQAx23ylC3iU0yDVwv95Z9QPsDE.jpg",
    voteAverage: 7.7,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 3500,
        title: "RBD: The Family",
        overview: "About the fictional lives of the Mexican group RBD.",
        poster: "/wqijX0thOJo6LPKHx4unhHP2kcX.jpg",
        posterHorizontal: "/8Hw535C9ILNl2gWLiNU2onvn9YH.jpg",
        voteAverage: 5.9,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 6759,
        title: "La mujer de Judas",
        overview:
          "La Mujer de Judas or The Wife of Judas is a telenovela produced by RCTV in Venezuela in 2002. Astrid Carolina Herrera, Chantal Baudaux, Juan Carlos Garcia are playing the main characters and it was directed and created by Martin Hahn. It consists of 126 episodes.",
        poster: "/iLbgzLsKfG3eeKR8vPM3lMz89b7.jpg",
        posterHorizontal: "/9KfxXF1dHIjOTYc3B4bRHdEKaWY.jpg",
        voteAverage: 8.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 7859,
        title: "The Face of Analia",
        overview:
          "El Rostro de Analía is a Spanish-language telenovela produced by the American-based television network Telemundo. It stars Elizabeth Gutiérrez, Martin Karpan, Maritza Rodríguez and Gabriel Porras, with the special appearance of Gaby Espino.",
        poster: "/mQJmZpHjKTsqt64PPGucObvU1gy.jpg",
        posterHorizontal: "/hQov6yy9ZHnM138UzJPvg9O018X.jpg",
        voteAverage: 4.315,
        type: "tv",
        videoUrl: "N6d09vspz-E",
      },
      {
        id: 7448,
        title: "A Favorita",
        overview:
          "Donatela and Flora, two friends who became rivals. One of them committed a homicide and pretends to be innocent. There are two versions for the same story. Who, after all, is telling the truth? Donatela or Flora?",
        poster: "/19aeBWMyI8nZczAAbcF1oMUZLMk.jpg",
        posterHorizontal: "/jVFbvke5EMr8FKVyaiHPCuLQJbw.jpg",
        voteAverage: 7.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 7458,
        title: "The Cartel",
        overview:
          "The Cartel follows ten friends, all of them members of a dangerous drug cartel, whose ambition for power and money will cause them to eventually kill each other. For it is an undeniable truth that, in this business, you always lose.",
        poster: "/cSvzG2B2uafu5BoP5nt0OvrVrQG.jpg",
        posterHorizontal: "/4jTSmEGdZ77A2dP6Y08gwo52LuF.jpg",
        voteAverage: 7.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 7495,
        title: "La Marca del Deseo",
        overview:
          "La Marca Del Deseo is a Colombian telenovela that has aired on Telefutura and RCN TV.",
        poster: "/hxA4uJbpaGPvZcUyXRTtax63yTv.jpg",
        posterHorizontal: null,
        voteAverage: 9,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 210506,
    title: "Sangue Oculto",
    overview: "",
    poster: "/myCEG6C5Nk181jXzBek5MQEXpM2.jpg",
    posterHorizontal: "/o5GsA1G5YEruuUNOYvWjlArIC37.jpg",
    voteAverage: 5.1,
    type: "tv",
    videoUrl: "no-url",
    similar: null,
  },
  {
    id: 68683,
    title: "Echte verhalen: De buurtpolitie",
    overview: "",
    poster: "/hFcluhACmpObsa5syJO0x6mQRio.jpg",
    posterHorizontal: "/t0tazKR9QaFT8W1Xf1XZTaHoD5u.jpg",
    voteAverage: 8,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 1411,
        title: "Person of Interest",
        overview:
          'John Reese, former CIA paramilitary operative, is presumed dead and teams up with reclusive billionaire Finch to prevent violent crimes in New York City by initiating their own type of justice. With the special training that Reese has had in Covert Operations and Finch\'s genius software inventing mind, the two are a perfect match for the job that they have to complete. With the help of surveillance equipment, they work "outside the law" and get the right criminal behind bars. ',
        poster: "/f8aIvYk5h7Z8EP3dinCmVgQFYow.jpg",
        posterHorizontal: "/3sCIyApg6jDoiTRwrNHHETRLQ8F.jpg",
        voteAverage: 8.076,
        type: "tv",
        videoUrl: "_xAK3ueOJxE",
      },
      {
        id: 1419,
        title: "Castle",
        overview:
          'After a serial killer imitates the plots of his novels, successful mystery novelist Richard "Rick" Castle receives permission from the Mayor of New York City to tag along with an NYPD homicide investigation team for research purposes.',
        poster: "/diXBeMzvfJb2iJg3G0kCUaMCzEc.jpg",
        posterHorizontal: "/A7r4EHJVQRmT6qzKQvIEMLAKdrM.jpg",
        voteAverage: 8.017,
        type: "tv",
        videoUrl: "xjrObBtzGYg",
      },
      {
        id: 1426,
        title: "Luther",
        overview:
          "A dark psychological crime drama starring Idris Elba as Luther, a man struggling with his own terrible demons, who might be as dangerous as the depraved murderers he hunts.",
        poster: "/hDxOMX8zzH1FiqKWVBzNaYGBkle.jpg",
        posterHorizontal: "/A2qdFRq9oJDC5E7fbgSS4POUMDF.jpg",
        voteAverage: 7.84,
        type: "tv",
        videoUrl: "vTZvxT03y1U",
      },
      {
        id: 1431,
        title: "CSI: Crime Scene Investigation",
        overview:
          "A Las Vegas team of forensic investigators are trained to solve criminal cases by scouring the crime scene, collecting irrefutable evidence and finding the missing pieces that solve the mystery.",
        poster: "/9XecVOLLkbGBNnpF2PvP8vQBmww.jpg",
        posterHorizontal: "/cvlLBcQWpO9X21jDHhgPJnE2aVq.jpg",
        voteAverage: 7.652,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1438,
        title: "The Wire",
        overview:
          "Told from the points of view of both the Baltimore homicide and narcotics detectives and their targets, the series captures a universe in which the national war on drugs has become a permanent, self-sustaining bureaucracy, and distinctions between good and evil are routinely obliterated.",
        poster: "/4lbclFySvugI51fwsyxBTOm4DqK.jpg",
        posterHorizontal: "/oggnxmvofLtGQvXsO9bAFyCj3p6.jpg",
        voteAverage: 8.499,
        type: "tv",
        videoUrl: "uDcQbk78CSw",
      },
      {
        id: 1447,
        title: "Psych",
        overview:
          "Thanks to his police officer father's efforts, Shawn Spencer spent his childhood developing a keen eye for detail (and a lasting dislike of his dad). Years later, Shawn's frequent tips to the police lead to him being falsely accused of a crime he solved. Now, Shawn has no choice but to use his abilities to perpetuate his cover story: psychic crime-solving powers, all the while dragging his best friend, his dad, and the police along for the ride.",
        poster: "/fDI15gTVbtW5Sbv5QenqecRxWKJ.jpg",
        posterHorizontal: "/zHA6kd8INvqMfGR9vDrn1GATKxs.jpg",
        voteAverage: 7.863,
        type: "tv",
        videoUrl: "pYvy-N8lNGQ",
      },
    ],
  },
  {
    id: 211239,
    title: "The Love in Your Eyes",
    overview:
      "Depicts the second love of a rogue daughter-in-law who appears in a 30-year-old gomtang restaurant, and a confident single mother Young Ih who says anything no matter what.\n\nJang Kyung Joon, who has the charm of a black-and-white man. Even though he shows the coolness of self-restraint from a large company that doesn't show his emotions easily, he shows both sides of being friendly in front of Lee Young Ih. Lee Young Ih, a single mother of steel mentality and a daughter-in-law with a bad attitude. She is sometimes angry, but she is a colorful charmer full of justice. Kim Hae Mi, her mother's daughter who has both her work and love in her hands, and Jang Kyung Joon's fiancée. It forms a tense rivalry with Bae Nouri. Jang Se Joon, the half-brother of Jang Kyung Joon, who has a friendly personality.",
    poster: "/gJnVJ3l4p1GDvGpwFedXhAJG3qE.jpg",
    posterHorizontal: "/jLH03sLbkAGxrThdW6b2lrwwE4X.jpg",
    voteAverage: 4.5,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 11769,
        title: "Godiva's",
        overview:
          "Godiva's is a Canadian television comedy-drama series, which debuted on Bravo! and Citytv in 2005; each episode is one hour in length. It completed a successful two-season run in 2006, but though the show received rave reviews, it was cancelled by CHUM broadcasting. There are currently attempts at getting a third season made.\n\nThe series was created by Michael MacLennan with Julia Keatley of Keatley Entertainment. The series was nominated for numerous Gemini Awards including Best Series. It was celebrated for its intelligent, fast-paced depiction of young Canadians in the restaurant industry.",
        poster: "/c0tItFgS59vpGPXsI0Rn1lYngJ7.jpg",
        posterHorizontal: "/nlZCYRvc71g4Xfugh7NWXrBzF2K.jpg",
        voteAverage: 4.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 13094,
        title: "Robin's Nest",
        overview:
          "Robin's Nest is a British sitcom starring Richard O'Sullivan as Robin Tripp, one of the lead characters in the sitcom, Man About The House, which had ended on 7 April 1976. It aired for six series from 11 January 1977 to 31 March 1981, and co-starred Tessa Wyatt as Robin's girlfriend - and later wife - Vicky, and Tony Britton as her father. It was made by Thames Television and aired on ITV.",
        poster: "/vwL2f49jhU6K9DDEU53OhKycXZK.jpg",
        posterHorizontal: "/uFgBpKn7AYuZ9b1dkQUJGMOAlKW.jpg",
        voteAverage: 6.8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 14548,
        title: "The Restaurant",
        overview:
          "Nine couples compete for the opportunity to go into business with chef Raymond Blanc.",
        poster: "/oz6yvC0Fo3eJbJSbX3bPRtRakJ9.jpg",
        posterHorizontal: "/pdORkQix45J5H3Nn3WtpAKG9EEX.jpg",
        voteAverage: 8.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 7449,
        title: "Raw",
        overview:
          "The lives and loves of the young staff who work in a successful Dublin restaurant and the intense friendships and bitter rivalries that blossom in the heat of the kitchen.",
        poster: "/tfPUfZLiS3SwoYhQJ184AM53ye.jpg",
        posterHorizontal: "/ierSDVmlEojEcqRso75ilywri2H.jpg",
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 8210,
        title: "Sweet Relationship",
        overview:
          "Sweet Relationship is a Taiwanese drama starring Vic Chou of F4, Alan Kuo, Megan Lai and Patty Hou. It is based on a Japanese josei manga Oishii Kankei by Satoru Makimura. It was produced by Comic Ritz International Production with Chai Zhi Ping as producer and directed by Chu Yu-ning.\n\nThe series was first boardcasted in Taiwan on free-to-air Chinese Television System from 16 September 2007 to 27 January 2008, every Sunday from 22:00 to 23:30 and cable TV Gala Television Variety Show/CH 28 from 22 September 2007 to 2 February 2008, every Saturday at 21:00. It only received moderate rating despite the promising cast as well as story. The average rating of the drama after the final episode was 1.50.",
        poster: "/4mpTViIPzJCbc4N5E9a0iagjiEA.jpg",
        posterHorizontal: "/e5dsuhP5w2Cwdn3zVbO8a5a9WkW.jpg",
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 22231,
        title: "The Dumplings",
        overview:
          "The Dumplings is an American television series starring James Coco and Geraldine Brooks that aired on NBC from January 28 to March 31, 1976.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 5,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 213017,
    title: "Lo Zoo di 105",
    overview: "",
    poster: "/6KL71OV5wHQGk5KZMP3qp7Mj5HA.jpg",
    posterHorizontal: null,
    voteAverage: 0,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 211098,
        title: "Zen émission",
        overview: "",
        poster: "/ofGVEyvKbGewSK571LM3rEcB6bb.jpg",
        posterHorizontal: "/4i8DOVCl5QGqL7pddejvC3yzACh.jpg",
        voteAverage: 10,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 204810,
        title: "Guanabis",
        overview: "",
        poster: "/9ufJlP3Ri3Tpebp2rmVYVC2ySTx.jpg",
        posterHorizontal: "/ozCo2tgYbXL5wjomH3RpfuiuoDK.jpg",
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 211174,
    title: "Vengeance of the Bride",
    overview:
      "The story of a woman who becomes the daughter-in-law of an enemy for desperate revenge.",
    poster: "/aHUyK2XA76mn9GM36wu2rRKvwB5.jpg",
    posterHorizontal: "/5gGfJIMB2ynRzERryQo8hTcdQXi.jpg",
    voteAverage: 5.3,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 20885,
        title: "Quatro por Quatro",
        overview:
          "A traffic accident causes four women's destinies to intertwine. In the series, the four enter a pact of revenge against the men who hit them and caused them to suffer. Auxiliadora struggled to help her husband Alcebíades prosper, but when he leaves her for a younger woman, is thrown out of the house. The shy Tatiana was engaged to Fortunato, who failed to show up at their wedding. The Babalu hurricane caught mechanic Raí in bed with another woman. Abigail, a preppy psychologist who is struggling in a failing marriage, decides superficially to continue it but revolts against her husband, Gustavo, who humiliates her in public at a congress. Gustavo has custody of Ângela, a girl who longs to know her true father, Bruno. Her mother died in the childbirth, traumatizing him.",
        poster: "/7QT75QY2ee26aDkgyoQW2Z2MfGg.jpg",
        posterHorizontal: "/Aa5UufGHmnxExspbocOWTW9IETN.jpg",
        voteAverage: 10,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 20714,
        title: "Don Amor",
        overview:
          "A group of young Chileans travel to Puerto Rico where they will live an experience that will change their lives forever.",
        poster: "/ti9Q7MAcIRJSe4Ny9BbTY6fncqn.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 26725,
        title: "If Tomorrow Comes",
        overview:
          "Tracy Whitney was in love, pregnant and engaged to marry into one of America's best family. And then, with one phone call, she lost everything. After 5 years of unjust imprisonment, Tracy emerges from prison a new woman. Cunning. Ruthless. Determined to survive. But there is one man as formidable as she is. As their paths crisscross, they eventually become daredevil partners in an adventure that climaxes their criminal careers.",
        poster: "/oOU7ifPTMpSjXAld5ZWWdSk7QSs.jpg",
        posterHorizontal: "/yJ6pEVYsf1UyYHHxPt64EFo40Lb.jpg",
        voteAverage: 7.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 27493,
        title: "Kita Yoshio's Tomorrow",
        overview:
          "Can a coward commit suicide?\n\nMeet Kita Yoshio, a very unlucky man who has chosen his close friend's death anniversary as his suicide date, which is 11 days away. The number 11 has been quite significant throughout his life: he was born on November 11th; his roll call number at school was #11; and 11 years ago, he and his wife, Mizuho, went through a divorce. Debt-laden and feeling unneeded to the world, he sells off all his belongings and plans for his death date. However, on the 1st day, he meets Yashiro Heita as well as numerous other characters who will cause him to experience the most eventful 11 days of his life.",
        poster: "/A4CQKt8OWjcyXFtmh4DjlI3eUm.jpg",
        posterHorizontal: "/g6ELIWmdAS36JtyMyhGwy4aedH6.jpg",
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 27540,
        title: "Number Six",
        overview: "",
        poster: "/6J1fWYIahgpPM1oezrT4us4oJyX.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 21667,
        title: "¿Dónde está Elisa?",
        overview:
          "A teenager's disappearance causes her family's world to turn upside down. In the police quest to find her, all her relatives will become suspects of her kidnapping.",
        poster: "/muVJNZUhAcngtbGqPglyachX6Ea.jpg",
        posterHorizontal: "/cnGM2EDLuyXeLFRLHGrZMSlDdUP.jpg",
        voteAverage: 7.2,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 211128,
    title: "The Iron Heart",
    overview:
      "An undercover agent goes on a dangerous mission to bring down a crime ring. Fueled by a bitter and painful past, he along with his allies faces the grueling task that will challenge his resolve and strength.",
    poster: "/91V6NI1JXCTDhaSSkoY7T87hk09.jpg",
    posterHorizontal: "/kaZTbbwKLKZoKtOLjPr4GgnFAPn.jpg",
    voteAverage: 6.7,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 4357,
        title: "Mission: Impossible",
        overview:
          "Mission: Impossible is an American television series that was created and initially produced by Bruce Geller. It chronicles the missions of a team of secret government agents known as the Impossible Missions Force. In the first season, the team is led by Dan Briggs, played by Steven Hill; Jim Phelps, played by Peter Graves, takes charge for the remaining seasons. A hallmark of the series shows Briggs or Phelps receiving his instructions on a recording that then self-destructs, followed by the theme music composed by Lalo Schifrin.\n\nThe series aired on the CBS network from September 1966 to March 1973, then returned to television for two seasons on ABC, from 1988 to 1990, retaining only Graves in the cast. It later inspired a popular series of theatrical motion pictures starring Tom Cruise, beginning in 1996.",
        poster: "/oVhJQdIc0MpGEgrxGyjtu09ZVMr.jpg",
        posterHorizontal: "/tqb56e4o7AMzyXZJF086sgkeqcb.jpg",
        voteAverage: 7.656,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4455,
        title: "Get Smart",
        overview:
          "Get Smart is an American comedy television series that satirizes the secret agent genre. Created by Mel Brooks with Buck Henry, the show stars Don Adams, Barbara Feldon, and Edward Platt. Henry said they created the show by request of Daniel Melnick, who was a partner, along with Leonard Stern and David Susskind, of the show's production company, Talent Associates, to capitalize on \"the two biggest things in the entertainment world today\"—James Bond and Inspector Clouseau. Brooks said: \"It's an insane combination of James Bond and Mel Brooks comedy.\" This is the only Mel Brooks production to feature a laugh track.\n\nThe success of the show eventually spawned the follow-up films The Nude Bomb and Get Smart, Again!, as well as a 1995 revival series and a 2008 film remake. In 2010, TV Guide ranked Get Smart's opening title sequence at No. 2 on its list of TV's Top 10 Credits Sequences, as selected by readers.",
        poster: "/AqhPucVAvnocglq5WYXbh6t9wuE.jpg",
        posterHorizontal: "/6ahKNfvLGWYDlhUfSagJfClXkoi.jpg",
        voteAverage: 7.934,
        type: "tv",
        videoUrl: "oBPYdiVAkyA",
      },
      {
        id: 10929,
        title: "The Wild Wild West",
        overview:
          'The Wild Wild West is an American television series  Developed at a time when the television western was losing ground to the spy genre, this show was conceived by its creator, Michael Garrison, as "James Bond on horseback." Set during the administration of President Ulysses Grant, the series followed Secret Service agents James West and Artemus Gordon as they solved crimes, protected the President, and foiled the plans of megalomaniacal villains to take over all or part of the United States.\n\nThe show also featured a number of fantasy elements, such as the technologically advanced devices used by the agents and their adversaries. The combination of the Victorian era time-frame and the use of Verne-esque style technology have inspired some to give the show credit for the origins of the steam punk subculture.',
        poster: "/4LSZNCSxDodwCP8EsKRTgMDUKY4.jpg",
        posterHorizontal: "/o1pBD8ji4yp9VstUBf9dvAkURFq.jpg",
        voteAverage: 7.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 13289,
        title: "Under Cover",
        overview:
          "Under Cover is an American secret agent drama series that premiered on ABC on January 7, 1991. The series starred Anthony John Denison and Linda Purl as Dylan and Kate Del'Amico, a husband and wife who share the same day job—as spies for a fictional US intelligence agency.\n\nUnder Cover follows the couple's adventures as they attempt to balance the demands of a sometimes deadly profession while raising two children. The series co-starred John Rhys-Davies as Flynn, the team's gadget man who is also a deadly assassin.\n\nAlthough well received by critics and launched with a high-rated made-for-TV movie, Under Cover was adversely affected by the outbreak of the 1991 Persian Gulf War. A two-part episode had been produced involving the Del'Amicos infiltrating Iraq in the wake of its invasion of Kuwait, and culminated with an American military strike on the country. The night the first episode was scheduled to air, real-life hostilities erupted. The two-part storyline was postponed indefinitely and the series itself was effectively cancelled. Following the end of the war, the series resumed for several more episodes, but it was soon officially cancelled, though not before the pulled Iraq episode was finally broadcast. Several episodes have subsequently been edited together as TV-movies and syndicated.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 11609,
        title: "Secret Agent Man",
        overview:
          "Secret Agent Man is a spy-fi television series\n\nThe series starred Costas Mandylor as Monk, a gallivanting secret agent, who was one of a team of agents that included Holliday\n\nAll the lead characters share the last names of jazz musicians Thelonious Monk, Billie Holiday, Miles Davis, and Dave Brubeck.",
        poster: "/9GLoIwRI2lUs1DI478Sl8NNwQbn.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 12910,
        title: "DAG",
        overview:
          "DAG is an American sitcom that aired from November 2000 to May 2001 on NBC. It was named after its star, David Alan Grier, who stars as United States Secret Service agent Jerome Daggett. Daggett's name, in turn, is a back-formation. The show also stars Delta Burke as the First Lady of the United States of America.",
        poster: "/lGSG9MSSg37OArbla5gh2KFR4Ha.jpg",
        posterHorizontal: null,
        voteAverage: 7,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
] as BrowserProps["popularTvShowsSimilar"];
