import { BrowserProps } from "pages/browse";

export default [
  {
    id: 130392,
    title: "The D'Amelio Show",
    overview:
      "From relative obscurity and a seemingly normal life, to overnight success and thrust into the Hollywood limelight overnight, the D’Amelios are faced with new challenges and opportunities they could not have imagined.",
    poster: "/phv2Jc4H8cvRzvTKb9X1uKMboTu.jpg",
    posterHorizontal: "/99vBORZixICa32Pwdwj0lWcr8K.jpg",
    voteAverage: 9,
    type: "tv",
    videoUrl: "Oq10yNlr_pQ",
    similar: [
      {
        id: 1364,
        title: "Hilary Duff: This Is Now",
        overview:
          'Hilary Duff: This Is Now is a two-part MTV reality television series about singer Hilary Duff, broadcast in April 2007. It followed Duff during a promotional tour for her album Dignity in Spain, and her first performance of her single "With Love" in Europe. It showed Duff participating in photo shoots, her personal affairs, and interview segments. The first episode aired on April 3, and the second on April 9, 2007.\n\nThe show took two weeks to film, and an MTV crew followed Duff around, filming her preparations for the release of the Dignity album.',
        poster: null,
        posterHorizontal: null,
        voteAverage: 1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1489,
        title: "Jimmy Kimmel Live!",
        overview:
          "Jimmy Kimmel Live! is an American late-night talk show, created and hosted by Jimmy Kimmel and broadcast on ABC.",
        poster: "/2r1BVnc6LPATNBvGzpy7m1AFPpj.jpg",
        posterHorizontal: "/At7XQ83krOAmiLMPSkBAK07XERi.jpg",
        voteAverage: 5.612,
        type: "tv",
        videoUrl: "2kqZi3RoA5I",
      },
      {
        id: 2396,
        title: "Punk'd",
        overview:
          "Ashton Kutcher punks his unsuspecting A-list celebrity friends with over-the-top pranks.",
        poster: "/gQ0dy65kgMmmVTc5Ze596p2nQ3v.jpg",
        posterHorizontal: "/qzSEj8agQXM8Di7v2hn6Dm6b1MD.jpg",
        voteAverage: 5.137,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2125,
        title: "Time Trumpet",
        overview:
          "Set in the year 2031, this mockumentary looks back at events that ostensibly happened during the first 30 years of the 21st century. The series follows a format that co-creator Armando Iannucci previously used in his satirical year-in-review programme '2004: The Stupid Version'.",
        poster: "/gIEDfX4D8hfXor9w8o7fpaPD9VT.jpg",
        posterHorizontal: null,
        voteAverage: 7.6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1832,
        title: "The Lucy–Desi Comedy Hour",
        overview:
          'The Lucy–Desi Comedy Hour is a collection of thirteen one-hour specials airing occasionally from 1957 to 1960, and originally served as part of Westinghouse Desilu Playhouse. Its original network title was The Ford Lucille Ball-Desi Arnaz Show for the first season, and The Westinghouse Desilu Playhouse Presents The Lucille Ball-Desi Arnaz Show for the following seasons. It was the successor to the classic comedy, I Love Lucy, and featured the same major cast members. The production schedule avoided the grind of a regular weekly series.\n\nDesilu produced the show, which was mostly filmed at their Los Angeles studios with occasional on-location shoots at Lake Arrowhead, Las Vegas and Sun Valley, Idaho. CBS reran the show under the "Lucy-Desi" title during the summers of 1962-1967, after which it went into syndication.',
        poster: "/ha0aHNPgcke8V0kN3hAUQ3oKTDd.jpg",
        posterHorizontal: null,
        voteAverage: 8.7,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1834,
        title: "Friday Night with Jonathan Ross",
        overview:
          "Jonathan Ross's take on current topics of conversation, guest interviews and live music from both a guest music group and the house band.",
        poster: "/dweqcAMlpidmoJcLu4omwuwsnef.jpg",
        posterHorizontal: "/nABc2EP7CQWaODt8sJXmMfGs4v4.jpg",
        voteAverage: 6.2,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 1396,
    title: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    posterHorizontal: "/hwIAR9FDsKULo8efoOUuxsFtO2u.jpg",
    voteAverage: 8.9,
    type: "tv",
    videoUrl: "XZ8daibM3AE",
    similar: [
      {
        id: 5255,
        title: "Miss Guided",
        overview:
          "Having navigated the awkward and sometimes traumatic world of high school, Rebecca Freely returns to her alma mater as a guidance counselor, free of the insecurities and orthodontia of her school days. Amidst student behavioral problems and the persistent romantic advances of the male nurse, Gary, Rebecca is certain of one thing - she is interested in the hot auto-shop-turned-Spanish-teacher, Tim. However, much as in high school days of unexpected teenage angst, Lisa, a former cheerleader and nemesis of Rebecca's, returns as the new English teacher determined to make Rebecca relive her unpopular past, setting sights on Tim as well.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 7,
        type: "tv",
        videoUrl: "hKugP2McNGU",
      },
      {
        id: 4521,
        title: "Jake and the Fatman",
        overview:
          'Jake and the Fatman is a television crime drama starring William Conrad as prosecutor J. L. "Fatman" McCabe and Joe Penny as investigator Jake Styles.\n\nThe series ran on CBS for five seasons from 1987 to 1992. Diagnosis: Murder was a spin-off of this series.',
        poster: "/3WBkepiTwgemGDZadyJTV5SmS4l.jpg",
        posterHorizontal: "/cOQ6JtfJs4JLQU30gr9Ix2O3XtI.jpg",
        voteAverage: 6.057,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4539,
        title: "Kingpin",
        overview:
          'Kingpin is an American crime drama television series which debuted on the NBC network in the U.S. and CTV in Canada on February 2, 2003 and lasted 6 episodes. NBC\'s answer to The Sopranos and also influenced by The Godfather, Macbeth and Traffik, the story was about a Mexican drug trafficker named Miguel Cadena and his family life. It was to be followed by a television series, but low ratings canceled those plans. Commercials for the mini-series on NBC featured the song "Más" by the Mexican band Kinky.',
        poster: "/gTIeheTQTnCfkqFA16Qhvagv7Qc.jpg",
        posterHorizontal: null,
        voteAverage: 6.9,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4624,
        title: "Roswell",
        overview:
          "Bizarre things start happening in the little New Mexico town where UFOs were spotted in 1947. Cut to 1999, when a cute high-school student saves the life of a teenage waitress. Surrounded by cliques of clever, angst-filled classmates, the two form a bond that threatens the survival of a secret universe involving superhuman powers, a yen for hot sauce and an alien gene pool.",
        poster: "/k1fHjj1TGPdP4tQfNlU74ibOmT4.jpg",
        posterHorizontal: "/mGu1GhnhhGO0vX5Z29bamDnLhMM.jpg",
        voteAverage: 7.82,
        type: "tv",
        videoUrl: "kxuJJA4HQRk",
      },
      {
        id: 4858,
        title: "Sea Patrol",
        overview:
          "Sea Patrol is an Australian television drama set on board HMAS Hammersley, a fictional patrol boat of the Royal Australian Navy. The series focuses on the ship and the lives of its crew members.",
        poster: "/k9S4rJIQiQlkbUaEhRCQ7p2NqET.jpg",
        posterHorizontal: "/fmTl7fSPUUn0yyO1XQtr17zcElF.jpg",
        voteAverage: 8.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4333,
        title: "The Saint",
        overview:
          "Simon Templar is The Saint, a handsome, sophisticated, debonair, modern-day Robin Hood who recovers ill-gotten wealth and redistributes it to those in need.",
        poster: "/aaqmfjvRZsxwwqbbVibPrlxfdIv.jpg",
        posterHorizontal: "/75ZH6Pd3ocOsJwKuWKWJPmdY2Gs.jpg",
        voteAverage: 7.234,
        type: "tv",
        videoUrl: "cFnJWWpkb7w",
      },
    ],
  },
  {
    id: 100088,
    title: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    posterHorizontal: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    voteAverage: 8.8,
    type: "tv",
    videoUrl: "uLtkt8BonwM",
    similar: [
      {
        id: 19,
        title: "Planet of the Apes",
        overview:
          "Two astronauts and a sympathetic chimp friend are fugitives in a future Earth dominated by a civilization of humanoid apes. \n\nBased on the 1968 Planet of the Apes film and its sequels, which were inspired by the novel of the same name by Pierre Boulle.",
        poster: "/zxo5Vrd0oXgm9ZCz4r7Q3L8veWg.jpg",
        posterHorizontal: "/JrBiUtR2CwxZR5GMK5Z9dU7Wr4.jpg",
        voteAverage: 6.929,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 44,
        title: "Adventures of Sonic the Hedgehog",
        overview:
          "Follow the adventures of Sonic the Hedgehog, and his sidekick Tails, as they attempt to stop Dr. Robotnik and his array of robots from taking over the planet Mobius.",
        poster: "/xjhZhermBwZtWiPA7xT7Rli2tmD.jpg",
        posterHorizontal: "/da5qFYz4JT1d4kTwbU1Gf15TRBD.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "yTc5HNKNKBY",
      },
      {
        id: 547,
        title: "Medical Investigation",
        overview:
          'Medical Investigation was an American medical drama television series that began September 9, 2004, on NBC. It ran for 20 one-hour episodes before being cancelled in 2005. The series was co-produced by Paramount Network Television and NBC Universal Television Studio The former controls North American distribution rights, while the latter distributes outside North America.\n\nThe series featured the cases of an elite team of medical experts of the National Institutes of Health who investigate unusual public-health crises, such as sudden outbreaks of serious and mysterious diseases. In actuality, medical investigative duties in the United States are normally the responsibility of the Centers for Disease Control and Prevention and local health departments, while the NIH is primarily a disease-research and -theory organization.\n\nThe series existed in the same television universe as Third Watch and, by extension ER. A special two-part crossover event aired on February 18, 2005, establishing the television-universe connection by featuring the Third Watch and Medical Investigation teams working together in MI\'s Episode 17: "Half Life" and Third Watch\'s Episode 16 of the sixth season: "In the Family Way". The story was about a series of Marburg virus cases in New York.',
        poster: "/3bTy80VccV3suS9ywXryGakdG5y.jpg",
        posterHorizontal: null,
        voteAverage: 6.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 574,
        title: "Thunderstone",
        overview:
          "The year is 2020. Fifteen-year-old Noah lives with his family in the futuristic underground community of North Col. The world above is a frozen wasteland after a massive comet strike destroyed all other life in the world including the animals. One night, he accidentally time travels to the future and finds himself trapped in the year 2085 in a desolate desert place called Haven with a group of children, the Nomads, led by Arushka.",
        poster: "/QjNZcyIxRVTvx2vhsfP3rMcp1o.jpg",
        posterHorizontal: "/gXZtfUyhp68COVoPVCqc2Pa1nQB.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1571,
        title: "The Legend of Zelda",
        overview:
          "The young adventurer Link and Princess Zelda protect Hyrule from the forces of Ganon, an evil wizard who desires the kingdom's treasured Triforce of Wisdom.",
        poster: "/oddre5aHiXSMnTMtMBPyv12rjbC.jpg",
        posterHorizontal: "/gyZRUabOxDnf2XKeCg4S8KGNmRl.jpg",
        voteAverage: 5.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1402,
        title: "The Walking Dead",
        overview:
          "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
        poster: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
        posterHorizontal: "/zaulpwl355dlKkvtAiSBE5LaoWA.jpg",
        voteAverage: 8.113,
        type: "tv",
        videoUrl: "BXqUmob-nfg",
      },
    ],
  },
  {
    id: 94605,
    title: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    posterHorizontal: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "3Svs_hl897c",
    similar: [
      {
        id: 20992,
        title: "Sonic Underground",
        overview:
          "Sonic, Sonia, and Manic are the children of Queen Aleena Hedgehog, the rightful ruler of Mobius, and are pursued relentlessly by Doctor Robotnik and his bumbling bounty hunters sidekicks, Sleet and Dingo. As infants, the siblings were separated and placed in hiding to fulfill a prophecy made by the Oracle of Delphius that the triplets would grow up to find their estranged mother, overthrow Robotnik, and take their places once more as Mobius' rightful rulers.",
        poster: "/rVjYevHn5RxkIkk4SwNnqIS8LJB.jpg",
        posterHorizontal: "/rMbHGg9J5jnhuIX0Lkv4r7yZ7QI.jpg",
        voteAverage: 6.953,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 19292,
        title: "Tooter Turtle",
        overview:
          'Tooter Turtle was a cartoon about a turtle that first appeared on TV in 1960, as a segment, along with The Hunter a detective dog, as part of the King Leonardo and His Short Subjects program. "Tooter Turtle" debuted on NBC, on Saturday, October 15, 1960, and ran for 39 original episodes through July 22, 1961. These episodes were later rerun as backups on other cartoon shows, but no more original episodes were made.',
        poster: "/qwcMhrjyZFw2W0E2OHsrlxjYqlL.jpg",
        posterHorizontal: "/sPaCuaNlIGKUOdEeFXKEL2dezWf.jpg",
        voteAverage: 5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 26732,
        title: "Super Mario World",
        overview:
          "Mario, Luigi, Yoshi and Princess Toadstool are on Dinosaur Island foiling the plans of King Koopa and his Koopa kids.",
        poster: "/482V5nBdZw3VmpnUDO4h0gH2sAK.jpg",
        posterHorizontal: "/mNhOTxhmr5JjvULZgt3Yh2FUjxH.jpg",
        voteAverage: 6.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 25364,
        title: "Bubsy",
        overview: "",
        poster: null,
        posterHorizontal: null,
        voteAverage: 3.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 25408,
        title: "F-Zero: GP Legend",
        overview:
          "Rick Wheeler was a police detective who got into a fatal car accident while pursuing the criminal Zoda. He was placed into artificial coldsleep for 150 years. Wheeler is brought back to life by Jody Summer and Dr. Stewart, who work with a group of good racers who try to keep prize money out of the hands of unsavory people like the Dark Million Organization run by Black Shadow and Deathborn.",
        poster: "/KpSzQXImvUwNUN9rxubgIkrOQZ.jpg",
        posterHorizontal: "/yGq0cawKci9MuVTI6rjXj66dWc1.jpg",
        voteAverage: 5.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 24709,
        title: "The Amazing World Of Kreskin",
        overview:
          "Kreskin, also known as The Amazing Kreskin, is an American mentalist who entertained studio audiences with this TV series from 1972 to 1975. It was broadcast throughout Canada on CTV and distributed in syndication in the US. The series was produced in Ottawa, Ontario at the CJOH-TV studios.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "UOcyrABr4ik",
      },
    ],
  },
  {
    id: 60625,
    title: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    posterHorizontal: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "BFTSrbB2wII",
    similar: [
      {
        id: 19253,
        title: "Mazinger Z",
        overview:
          "Mazinger Z, known briefly as Tranzor Z in the United States, is a Japanese super robot manga series written and illustrated by Go Nagai. The first manga version was serialized in Shueisha's Weekly Shōnen Jump from October 1972 to August 1973, and it later continued in Kodansha TV Magazine from October 1973 to September 1974. It was adapted into an anime television series which aired on Fuji TV from December 1972 to September 1974. A second manga series was released alongside the TV show, this one drawn by Gosaku Ota, which started and ended almost at the same time of the TV show. Mazinger Z has spawned several sequels and spinoff series, among them UFO Robot Grendizer and Mazinkaiser. It was a very popular cartoon in Mexico during the 1980s, where it was dubbed into Spanish directly from the Japanese version, keeping the Japanese character names and broadcasting all 92 episodes, unlike the version aired in the U.S.",
        poster: "/woGUtAdRwjzWgobGvF3ebW1WsKY.jpg",
        posterHorizontal: "/dxD7yCiBw3RqKAlK6935mZHPvIi.jpg",
        voteAverage: 7.809,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 20731,
        title: "Magic Grandad",
        overview:
          "Magic Grandad was an educational programme which originally aired on BBC Two under the title 'Switch On, Switch Off' during Schools section of 1993. The show saw 'Magic' Grandad take his young grandchildren back in time, many of the adventures are about comparing the past and the present and seeing how evidence of what happened in the olden days still survives.  \n\nThe show was said to make learning about history \"fun for youngsters\" and was aimed at children aged 5-7 years. The series was introduced to support the History National Curriculum at Key Stage 1. New seasons have been made periodically to support new areas of the infant history curriculum such as seaside holidays and toys. \n\nThe early season have a companion booklet of teacher's notes with descriptions of the episodes, various suggestions for follow-up work and photocopiable worksheets.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 20788,
        title: "Fresno",
        overview:
          "In Fresno, California, the once-wealthy Kensington family's raisin-growing empire has fallen on hard times. They are led by widowed matriarch Charlotte, who is locked in a deadly power struggle with rival raisin magnate Tyler Cane.",
        poster: "/fGZe30wn7ajjwVAPlz5jNYUc5BE.jpg",
        posterHorizontal: "/9hMXbF6i32rFKYyxmkuvJGsw98i.jpg",
        voteAverage: 9.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 25352,
        title: "Highcliffe Manor",
        overview:
          "Newly widowed Helen Blacke inherits the Blacke Foundation, a scientific research institute located in the Highcliffe Manor on an island off the Massachusetts coast and populated by mad scientists who want to get rid of her.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 27910,
        title: "Home Fires",
        overview: "Home Fires is an American sitcom",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 27453,
        title: "Bucky O'Hare and the Toad Wars!",
        overview:
          "Galactic hero Bucky O'Hare and his brave crew battle the evil toads bent on conquering the universe. A young boy genius from the human universe joins Bucky's crew.",
        poster: "/6uMfwciXLDVzcbW09PvyfYWRUGj.jpg",
        posterHorizontal: "/9Jfm09ZbMWNBhk7JRJjKKycB3Ud.jpg",
        voteAverage: 9.5,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 114410,
    title: "Chainsaw Man",
    overview:
      "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
    poster: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
    posterHorizontal: "/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "j9sSzNmB5po",
    similar: [
      {
        id: 1734,
        title: "Dante's Cove",
        overview:
          "A young gay couple must overcome dark, mystical forces conspiring against them, starting with a vengeful 19th century witch and her cheating warlock fiance.",
        poster: "/KtTEB48xXCaah50sja2Xw5Hdkk.jpg",
        posterHorizontal: "/zIhzcAicZUSP5CN1aAYVoC1FpY2.jpg",
        voteAverage: 6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1394,
        title: "Ninja Sentai Kakuranger",
        overview:
          "It's been a long time since the great war between the Three God Generals and the Youkais, an ancient race of monstrous spirits. Since then, imprisoned in a cave protected by the mystical Seal Door, their leader Daimaou and his Youkai army wait, planning for the day they can finally strike. That day has arrived and it is up to the Kakurangers, along with the Three God Generals, to defeat the Youkais, before Daimaou's villainy destroys Earth!",
        poster: "/zxInqzS33cyk9Af2m9ftfi6cMQS.jpg",
        posterHorizontal: "/s9WF0ySkO3RVIZIXb6NvAzrqy3w.jpg",
        voteAverage: 9.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1402,
        title: "The Walking Dead",
        overview:
          "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
        poster: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
        posterHorizontal: "/zaulpwl355dlKkvtAiSBE5LaoWA.jpg",
        voteAverage: 8.113,
        type: "tv",
        videoUrl: "BXqUmob-nfg",
      },
      {
        id: 1413,
        title: "American Horror Story",
        overview:
          "An anthology horror drama series centering on different characters and locations, including a house with a murderous past, an asylum, a witch coven, a freak show, a hotel, a farmhouse in Roanoke, a cult, the apocalypse and a summer camp.",
        poster: "/tiuzjuzalHj377XER1sfq7XQEIT.jpg",
        posterHorizontal: "/8kBhAP03JpPcTklJp5idCNJhRqE.jpg",
        voteAverage: 8.151,
        type: "tv",
        videoUrl: "-9KZr2Vn7CQ",
      },
      {
        id: 1429,
        title: "Attack on Titan",
        overview:
          "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
        poster: "/aiy35Evcofzl7hASZZvsFgltHTX.jpg",
        posterHorizontal: "/uACJw45EEkB5mfFw4SgMtgZgBBJ.jpg",
        voteAverage: 8.646,
        type: "tv",
        videoUrl: "bT9csxkth8g",
      },
      {
        id: 2260,
        title: "H2O: Just Add Water",
        overview:
          "H2O: Just Add Water revolves around three teenage girls facing everyday teen problems with an added twist: they cope with the burden of growing a giant fin and transforming into mermaids whenever they come in contact with water.",
        poster: "/jSnemLaRSsmsinVRHDJKRb6pviW.jpg",
        posterHorizontal: "/d5jeHsiD9IUa1QL2VSizsEwjiBe.jpg",
        voteAverage: 7.8,
        type: "tv",
        videoUrl: "wqHED34TcwU",
      },
    ],
  },
  {
    id: 85990,
    title: "Hitoribocchi no Marumaruseikatsu",
    overview:
      "Hitori Bocchi suffers from extreme social anxiety, she's not good at talking to people, takes pretty extreme actions, is surprisingly adept at avoiding people, her legs cramp when she overexerts herself, gets full of herself when alone, will vomit when exposed to extreme tension and often comes up with plans. Now she is entering middle school and her only friend, Yawara Kai, is attending a different school. This leaves Bocchi alone, surrounded by new classmates with whom she must make friends before Kai will talk to her again.",
    poster: "/btoTzCw3zmjRtB99g2M5Mw2GUQG.jpg",
    posterHorizontal: "/790rH1ByeDJg6VPwBFxdzxHRepI.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 2553,
        title: "Punky Brewster",
        overview:
          "An abandoned waif and her dog are taken in by a cranky apartment manager who becomes her guardian in this family-friendly sitcom.",
        poster: "/2ZVmXNThTccZ4rKUfe1C1QZDwTe.jpg",
        posterHorizontal: "/8Ke6OY1rpgy6cJnPVorUILQXNhx.jpg",
        voteAverage: 7.419,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2661,
        title: "Kamen Rider",
        overview:
          "Hongo Takeshi is a promising young man with a passion for motorcycle racing. However, his dreams are suddenly ruined when he gets kidnapped by Shocker, the evil secret organisation planning to dominate the world. After being remodeled into a cyborg, Takeshi escapes and swears to protect the world from the inhuman monsters.",
        poster: "/fIJNVBa6MJStPiOvhLV69nAdu0e.jpg",
        posterHorizontal: "/usLRh1bcbL0Q9X8zf6rL4OV1qrA.jpg",
        voteAverage: 5.9,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3570,
        title: "Sailor Moon",
        overview:
          'One day, Usagi Tsukino, clumsy 2nd-year middle school student (8th grader), stumbles upon a talking cat named Luna. Luna tells her that she is destined to be Sailor Moon, "champion of love and justice", and she must search for the fabled Moon Princess. Usagi finds friends that turn out to be destined senshi as well, and together they fight to save the world from the certain doom brought upon by the Dark Kingdom (Queen Beryl, the generals, Metallia).',
        poster: "/ylo2jRmsVCYAXcL1qX2U9GvxpZ7.jpg",
        posterHorizontal: "/nDDZ9yQoQpC9i3Q9W9EC7QdcPsX.jpg",
        voteAverage: 8.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3022,
        title: "Rugrats",
        overview:
          "Focuses on a group of toddlers, most prominently Tommy, Chuckie, Phil, Lil, and Angelica, and their day-to-day lives, usually involving common life experiences that become adventures in the babies' imaginations. Adults in the series are almost always unaware of what the children are up to; however, this only provides more room for the babies to explore and discover their surroundings.",
        poster: "/corsUEMQqLn9Ug392B1ek40gmqK.jpg",
        posterHorizontal: "/fKpfCR3l0WukHTkI6Z2ySX1if4P.jpg",
        voteAverage: 7.668,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 3149,
        title: "Noozles",
        overview:
          "Twelve-year-old Sandy goes on adventures with her koala friends Blinky and Pinky, who are from the extra-dimensional realm of Koalawalla Land.",
        poster: "/xupinZyowwuJmcRGybCZp0Twsv9.jpg",
        posterHorizontal: "/AaUlvm4mmafkclXPccYnPvSUFMF.jpg",
        voteAverage: 5.667,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1892,
        title: "The Fresh Prince of Bel-Air",
        overview:
          "Will, a street-smart teenager, moves from the tough streets of West Philly to posh Bel-Air to live with his Uncle Philip, Aunt Vivian, his cousins — spoiled Hilary, preppy Carlton and young Ashley — and their sophisticated British butler, Geoffrey. Though Will’s antics and upbringing contrast greatly with the upper-class lifestyle of his extended relatives, he soon finds himself right at home as a loved part of the family.",
        poster: "/2xjqlhBLfwVgmqM7EGfxRpNGm3E.jpg",
        posterHorizontal: "/5HgdSUIGeHQ4osZVACxB4Of2M7e.jpg",
        voteAverage: 7.969,
        type: "tv",
        videoUrl: "_u6vYpbfCmQ",
      },
    ],
  },
  {
    id: 37854,
    title: "One Piece",
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    poster: "/dum1wnm6kJOUos0XJqjB8s2UWi9.jpg",
    posterHorizontal: "/4Mt7WHox67uJ1yErwTBFcV8KWgG.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "S8_YwFLCh4U",
    similar: [
      {
        id: 5300,
        title: "Love Thy Neighbour",
        overview:
          "Love Thy Neighbour is a British sitcom, which was transmitted from 13 April 1972 until 22 January 1976, spanning seven series. The sitcom was produced by Thames Television for the ITV network. The principal cast included Jack Smethurst, Rudolph Walker, Nina Baden-Semper and Kate Williams. In 1973, the series was adapted into a film of the same name, and a later sequel series was set in Australia.",
        poster: "/slpzNSCLkjAceAtaG82Kpkby8LN.jpg",
        posterHorizontal: "/gZ7MQAxRVGLwLx99ytaCF6rNob7.jpg",
        voteAverage: 8.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5341,
        title: "Dogtanian and the Three Muskehounds",
        overview:
          "Dogtanian and the Three Muskehounds is an animated cartoon adaptation of the classic Alexandre Dumas story of d'Artagnan and The Three Musketeers. Most of the characters are anthropomorphizations of dogs, hence the title of the cartoon; although there are a few exceptions, most notably Dogtanian's two sidekicks Pip the mouse and Planchet the bear, among several others.",
        poster: "/ydPAimbFDUv7dbegtvUNsHVUPuZ.jpg",
        posterHorizontal: "/7VhSMvi8fs9lixvynlZ20XEBfWR.jpg",
        voteAverage: 7.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5371,
        title: "iCarly",
        overview:
          "Watch Carly, Sam, and Freddie, as they try to balance their everyday 8th grade lives with their newfound fame managing and starring in the most awesome show on the web.",
        poster: "/kP8Z51s9D8tiGnoRbL88db0e2jv.jpg",
        posterHorizontal: "/Acmi2eVIXff5fHG0XOFDGzhwqwr.jpg",
        voteAverage: 8.019,
        type: "tv",
        videoUrl: "UZPdQyXl-Lo",
      },
      {
        id: 4510,
        title: "Princess Gwenevere and the Jewel Riders",
        overview:
          "Princess Gwenevere and the Jewel Riders is an American fantasy themed cartoon television series produced by Bohbot Productions and Hasbro with association with Hong Ying Animation in 1995. Each episode was constructed as an animated minimusical, aimed at children aged four and older. Internationally syndicated by Bohbot Entertainment, the international version has the title character renamed to Starla.\n\nThere is a special emphasis on the \"power of friendship\", which enables the titular Jewel Riders, the three adolescent girl defenders of this enchanted kingdom, to overcome their adversaries. The show's action is set in the legendary island of Avalon, here portrayed as a fairy tale style utopia that keeps its magical energies in check with the aid of the seven royal Crown Jewels. The plot follows the quest of Avalon's young princess Gwenevere and her friends Fallon and Tamara to secure the scattered enchanted jewels, stop the evil Lady Kale from taking over the kingdom, restore harmony in magic and bring their mentor Merlin home. In the second season, the Jewel Riders receive more powers and new costumes; a new villain, Morgana, is also introduced in addition to the returning Kale, as is a new set of magical jewels to find. In the original version of the show, the title character has her name similar with Arthur's wife, Guinevere; other Arthurian characters in the show include Merlin and Lady of the Lake.",
        poster: "/aSoboTgKzRhwxSQCkpnrqTdFbBL.jpg",
        posterHorizontal: "/z9ibLzVbeOVb0ORKv5FxuKkzqXg.jpg",
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4545,
        title: "Blossom",
        overview:
          "Blossom is an American sitcom broadcast on NBC from January 3, 1991, to May 22, 1995. The series was created by Don Reo, and starred Mayim Bialik as Blossom Russo, a teenager living with her father and two brothers. It was produced by Reo's Impact Zone Productions in association with Witt/Thomas Productions and Touchstone Television.",
        poster: "/dAqJk0AEOzvMMKbqbQw4DmRaNk6.jpg",
        posterHorizontal: "/uyCMnDi5Je8shCIAmcWZwZzkPtD.jpg",
        voteAverage: 5.952,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4556,
        title: "Scrubs",
        overview:
          'In the unreal world of Sacred Heart Hospital, John "J.D." Dorian learns the ways of medicine, friendship and life.',
        poster: "/u1z05trCA7AuSuDhi365grwdos1.jpg",
        posterHorizontal: "/z6fUdAWIqSenjIYsPmRltaGHcTq.jpg",
        voteAverage: 8.03,
        type: "tv",
        videoUrl: "zOgb3KIJDY8",
      },
    ],
  },
  {
    id: 70785,
    title: "Anne with an E",
    overview:
      "A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.",
    poster: "/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg",
    posterHorizontal: "/70YdbMELM4b8x8VXjlubymb2bQ0.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 5256,
        title: "The Mists of Avalon",
        overview:
          "The Mists of Avalon is a 2001 miniseries based on the novel of the same name by Marion Zimmer Bradley. It was produced by American cable channel TNT and directed by Uli Edel.",
        poster: "/iVEbAgsYBVwKH8goTkUVd59fIWB.jpg",
        posterHorizontal: "/qJUYXYijCL9Q8QkFhjvVBj6dvcM.jpg",
        voteAverage: 6.897,
        type: "tv",
        videoUrl: "NYEvkSc3Nk4",
      },
      {
        id: 5292,
        title: "Behind the White Tower",
        overview:
          "Based on renowned Japanese novelist Yamazaki Toyoko's representative work Shiroi Kyotō, the drama brings viewers deep into the political inner workings of the medical field by taking a satirical look at malpractice and power plays at a university hospital, and contrasting the paths and personalities of two doctors.",
        poster: "/nhCqdwT7e2ZCobBBxUT4VeBioT6.jpg",
        posterHorizontal: "/uv2bfSX6vfRwWgxU2F3d6YBXH50.jpg",
        voteAverage: 9.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5300,
        title: "Love Thy Neighbour",
        overview:
          "Love Thy Neighbour is a British sitcom, which was transmitted from 13 April 1972 until 22 January 1976, spanning seven series. The sitcom was produced by Thames Television for the ITV network. The principal cast included Jack Smethurst, Rudolph Walker, Nina Baden-Semper and Kate Williams. In 1973, the series was adapted into a film of the same name, and a later sequel series was set in Australia.",
        poster: "/slpzNSCLkjAceAtaG82Kpkby8LN.jpg",
        posterHorizontal: "/gZ7MQAxRVGLwLx99ytaCF6rNob7.jpg",
        voteAverage: 8.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5314,
        title: "The Company",
        overview:
          "The Company tells the thrilling story of Cold War CIA agents imprisoned in double lives, fighting an amoral, elusive, formidable enemy – and each other – in an internecine battle within the Company itself.",
        poster: "/rxBchxWLVuqjG4kk1IhDAUMghr9.jpg",
        posterHorizontal: "/c8Ophy1jFWrEnQ2QLSZWdSGZxcn.jpg",
        voteAverage: 7.338,
        type: "tv",
        videoUrl: "xOQOfRXtu_4",
      },
      {
        id: 5315,
        title: "The New Adventures of Robin Hood",
        overview:
          "The New Adventures of Robin Hood is a 1997-1998 live action TV series on Turner Network Television. It was filmed in Vilnius, Lithuania and produced and distributed by Dune Productions, M6, and Warner Bros. International.\n\nThe tone of the series resembled its contemporaries Hercules: The Legendary Journeys and Xena: Warrior Princess. The premiere episode aired immediately after an episode of WCW Monday Nitro. A unique promotional effort took place between the two, with the Nitro main event -- Hulk Hogan vs The Giant—not beginning until two minutes before the show ended and then continuing and being broadcast in lieu of standard commercial breaks.",
        poster: "/t26XFa4fjm2T3By8ZO5Arlo8zt3.jpg",
        posterHorizontal: null,
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5371,
        title: "iCarly",
        overview:
          "Watch Carly, Sam, and Freddie, as they try to balance their everyday 8th grade lives with their newfound fame managing and starring in the most awesome show on the web.",
        poster: "/kP8Z51s9D8tiGnoRbL88db0e2jv.jpg",
        posterHorizontal: "/Acmi2eVIXff5fHG0XOFDGzhwqwr.jpg",
        voteAverage: 8.019,
        type: "tv",
        videoUrl: "UZPdQyXl-Lo",
      },
    ],
  },
  {
    id: 95557,
    title: "Invincible",
    overview:
      "Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.",
    poster: "/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg",
    posterHorizontal: "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "-bfAVpuko5o",
    similar: [
      {
        id: 5279,
        title: "Princess Hours",
        overview:
          "Chae Gyeong is an ordinary high school student. One day, she receives some unexpected news. Because of her grandfathers will, she must marry the unendurable Crown Prince Lee Shin who also attends her high school. Chae Gyeong resists the proposal but reluctantly marries him to help her debt-ridden family. As she struggles to adapt herself to the proper manners and royal duties of palace life and to her disagreeable husband, Lee Shin's sentimental cousin and second-in-line to the throne, Yul, steps into her life.  She feels like she can rely on Yul to help her, but finds it difficult not to worry about her haughty, cold-hearted husband. To help bridge this gap, the senior members of the royal family take some special measures to get them to spend the night together.",
        poster: "/7l2aN9cT7CZ8QPUKknlRsiTAx0k.jpg",
        posterHorizontal: "/aYagJuQhXpeuq9PEc5ktrk9eukc.jpg",
        voteAverage: 7.893,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5281,
        title: "Bakuryu Sentai Abaranger",
        overview:
          "The meteorite believed to have once killed off the dinosaurs actually rattled the Earth into two parallel universes — Another Earth and Dino Earth, where dinosaurs continued to thrive. Now they have evolved into the Saurians, a race of humanoid dinosaurs, and the Bakuryu , a race of mechanized dinosaurs. But the wall between our universes has been breached. The Evolians that have been at war with the Saurians and Bakuryu have invaded, and it's up to the Abarangers to protect the world!",
        poster: "/oKvauf15zNdThK2HqhG4cBe4b2C.jpg",
        posterHorizontal: "/yZgKd53zyzvC6gOXCfsDwyzO04K.jpg",
        voteAverage: 9,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5337,
        title: "Kagaku Sentai Dynaman",
        overview:
          "Five scientists are defenders of the Earth. They have great dreams and transform using the Dyna Brace.",
        poster: "/gxtbnj9KrOdR0WPLi24m4XjeeJ2.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5343,
        title: "Beakman's World",
        overview:
          "Beakman's World is an educational children's television show. The program is based on the Universal Press Syndicate syndicated comic strip You Can with Beakman and Jax created by Jok Church. The series premiered September 18, 1992 on The Learning Channel cable network and in national syndication.\n\nOn September 18, 1993 it moved from national syndication to CBS Saturday morning children’s lineup. At the peak of its popularity, it was seen in nearly 90 countries around the world. The series was canceled in 1998. Reruns returned to national syndication in September 2006, after which it was transferred to local stations such as KICU. The show debuted a year prior to Bill Nye the Science Guy, which covered similar topics. The show's host, Paul Zaloom, still performs as Beakman in live appearances around the globe.",
        poster: "/x6wXEkbyhwh98kFWPtfjn5EdVHu.jpg",
        posterHorizontal: "/kje9CsNClEI4MhmxmjPymWpRKto.jpg",
        voteAverage: 8.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5357,
        title: "Hyakujuu Sentai Gaoranger",
        overview:
          "Long ago, a great, destructive war between humans the Orgs was ended; the people of Earth were believed to be the victors. But now, 1,000 years later, the Orgs have returned. And five new warriors have been selected by the Power Animals to claim the responsibility of protecting humanity once again, by becoming Gaorangers!",
        poster: "/mDTG3RYT6LzNxuJypkG43ICyIEM.jpg",
        posterHorizontal: "/wEJcMbUxNdKq5lo23ZIjqZZs6C0.jpg",
        voteAverage: 8.8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4515,
        title: "Lois & Clark: The New Adventures of Superman",
        overview:
          "A much more lavish version of the popular Superman television series which had first aired forty years earlier, Lois & Clark focused more on the Man of Steel's early adult years in Metropolis. With the unknowing help of Lois Lane, Clark Kent created Superman there in Metropolis after finding work at the world-famous Daily Planet newspaper, where he meets fellow reporter Lois Lane.",
        poster: "/1LbPs6i1h4BKjVUwK5S9GjPCydi.jpg",
        posterHorizontal: "/ebDi6FNKlDJqAzzaTtBxoX68Lbz.jpg",
        voteAverage: 7.104,
        type: "tv",
        videoUrl: "Uxiu29masIo",
      },
    ],
  },
  {
    id: 67915,
    title: "Goblin",
    overview:
      "In his quest for a bride to break his immortal curse, a 939-year-old guardian of souls meets a grim reaper and a sprightly student with a tragic past.",
    poster: "/c2gon6zbqzL73DOl8mPQMMUJXvE.jpg",
    posterHorizontal: "/smSbK5cd8T9XHcxEUcems23BDEF.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "8AcNEVUzV4o",
    similar: [
      {
        id: 5255,
        title: "Miss Guided",
        overview:
          "Having navigated the awkward and sometimes traumatic world of high school, Rebecca Freely returns to her alma mater as a guidance counselor, free of the insecurities and orthodontia of her school days. Amidst student behavioral problems and the persistent romantic advances of the male nurse, Gary, Rebecca is certain of one thing - she is interested in the hot auto-shop-turned-Spanish-teacher, Tim. However, much as in high school days of unexpected teenage angst, Lisa, a former cheerleader and nemesis of Rebecca's, returns as the new English teacher determined to make Rebecca relive her unpopular past, setting sights on Tim as well.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 7,
        type: "tv",
        videoUrl: "hKugP2McNGU",
      },
      {
        id: 5256,
        title: "The Mists of Avalon",
        overview:
          "The Mists of Avalon is a 2001 miniseries based on the novel of the same name by Marion Zimmer Bradley. It was produced by American cable channel TNT and directed by Uli Edel.",
        poster: "/iVEbAgsYBVwKH8goTkUVd59fIWB.jpg",
        posterHorizontal: "/qJUYXYijCL9Q8QkFhjvVBj6dvcM.jpg",
        voteAverage: 6.897,
        type: "tv",
        videoUrl: "NYEvkSc3Nk4",
      },
      {
        id: 5257,
        title: "Mortified",
        overview:
          "Mortified was an Australian children's television series, co-produced by the Australian Children's Television Foundation and Enjoy Entertainment for the Nine Network Australia, Disney Australia and the BBC. The series premiered on 30 June 2006 and ended on 11 April 2007 with two seasons and a total of 26 episodes. Currently, re-runs air on both ABC and the Disney Channel, in the U.S. on Starz Kids and Family, and in the UK on Pop Girl.",
        poster: "/w92ZGOCDqy5LAbxoXMFIVpIhJj1.jpg",
        posterHorizontal: "/q2NX3MZWo70HJqpfPZtkMlHfNWi.jpg",
        voteAverage: 7.9,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5279,
        title: "Princess Hours",
        overview:
          "Chae Gyeong is an ordinary high school student. One day, she receives some unexpected news. Because of her grandfathers will, she must marry the unendurable Crown Prince Lee Shin who also attends her high school. Chae Gyeong resists the proposal but reluctantly marries him to help her debt-ridden family. As she struggles to adapt herself to the proper manners and royal duties of palace life and to her disagreeable husband, Lee Shin's sentimental cousin and second-in-line to the throne, Yul, steps into her life.  She feels like she can rely on Yul to help her, but finds it difficult not to worry about her haughty, cold-hearted husband. To help bridge this gap, the senior members of the royal family take some special measures to get them to spend the night together.",
        poster: "/7l2aN9cT7CZ8QPUKknlRsiTAx0k.jpg",
        posterHorizontal: "/aYagJuQhXpeuq9PEc5ktrk9eukc.jpg",
        voteAverage: 7.893,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5300,
        title: "Love Thy Neighbour",
        overview:
          "Love Thy Neighbour is a British sitcom, which was transmitted from 13 April 1972 until 22 January 1976, spanning seven series. The sitcom was produced by Thames Television for the ITV network. The principal cast included Jack Smethurst, Rudolph Walker, Nina Baden-Semper and Kate Williams. In 1973, the series was adapted into a film of the same name, and a later sequel series was set in Australia.",
        poster: "/slpzNSCLkjAceAtaG82Kpkby8LN.jpg",
        posterHorizontal: "/gZ7MQAxRVGLwLx99ytaCF6rNob7.jpg",
        voteAverage: 8.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5315,
        title: "The New Adventures of Robin Hood",
        overview:
          "The New Adventures of Robin Hood is a 1997-1998 live action TV series on Turner Network Television. It was filmed in Vilnius, Lithuania and produced and distributed by Dune Productions, M6, and Warner Bros. International.\n\nThe tone of the series resembled its contemporaries Hercules: The Legendary Journeys and Xena: Warrior Princess. The premiere episode aired immediately after an episode of WCW Monday Nitro. A unique promotional effort took place between the two, with the Nitro main event -- Hulk Hogan vs The Giant—not beginning until two minutes before the show ended and then continuing and being broadcast in lieu of standard commercial breaks.",
        poster: "/t26XFa4fjm2T3By8ZO5Arlo8zt3.jpg",
        posterHorizontal: null,
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 31911,
    title: "Fullmetal Alchemist: Brotherhood",
    overview:
      "Edward and Alphonse Elric's reckless disregard for alchemy's fun­damental laws ripped half of Ed's limbs from his body and left Al's soul clinging to a cold suit of armor. To restore what was lost, the brothers scour a war-torn land for the Philosopher's Sto­ne, a fabled relic which grants the ability to perform alchemy in impossible ways.\n\nThe Elrics are not alone in their search; the corrupt State Military is also eager to harness the artifact's power. So too are the strange Homunculi and their shadowy creator. The mythical gem lures exotic alchemists from distant kingdoms, scarring some deeply enough to inspire murder. As the Elrics find their course altered by these enemies and allies, their purpose remains unchanged – and their bond unbreakable.",
    poster: "/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg",
    posterHorizontal: "/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "AYlksPeSXrs",
    similar: [
      {
        id: 5341,
        title: "Dogtanian and the Three Muskehounds",
        overview:
          "Dogtanian and the Three Muskehounds is an animated cartoon adaptation of the classic Alexandre Dumas story of d'Artagnan and The Three Musketeers. Most of the characters are anthropomorphizations of dogs, hence the title of the cartoon; although there are a few exceptions, most notably Dogtanian's two sidekicks Pip the mouse and Planchet the bear, among several others.",
        poster: "/ydPAimbFDUv7dbegtvUNsHVUPuZ.jpg",
        posterHorizontal: "/7VhSMvi8fs9lixvynlZ20XEBfWR.jpg",
        voteAverage: 7.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4507,
        title: "The Thick of It",
        overview:
          "Set in the corridors of power and spin, the Minister for Social Affairs is continually harassed by Number 10's policy enforcer and dependent on his not-so-reliable team of civil servants.",
        poster: "/xuOz95tUuXclfnlOID7ejtREYqf.jpg",
        posterHorizontal: "/7v4s25oKOkrMxlc1OHobnrFA8u4.jpg",
        voteAverage: 8.032,
        type: "tv",
        videoUrl: "RtJVXcuHssI",
      },
      {
        id: 4549,
        title: "Yes Minister",
        overview:
          "Satirical sitcom set in the office of a UK Cabinet minister, Jim Hacker MP, who struggles with Civil Service bureaucracy and political machinations as he tries to get on with government business.",
        poster: "/aHIlqouFwRJsQx0rfLSOO5cGrqj.jpg",
        posterHorizontal: "/erND13jVv79DZqDNIbaysTcGxq.jpg",
        voteAverage: 8.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4616,
        title: "Xena: Warrior Princess",
        overview:
          "Xena is an infamous warrior on a quest to seek redemption for her past sins against the innocent. Accompanied her comrade-in-arms Gabrielle, the campy couple use their formidable fighting skills to help those who are unable to defend themselves.",
        poster: "/qjUn6GVZVDifLHB7bvVrgZsOfzE.jpg",
        posterHorizontal: "/c9bwsqTNRr1r7HGKDAu4OfYlBAt.jpg",
        voteAverage: 7.591,
        type: "tv",
        videoUrl: "VvwtBohkgto",
      },
      {
        id: 4632,
        title: "Vanished",
        overview:
          "Sara Collins is gone. But before the FBI can solve the mystery of where she is, they first need to figure out who she really is. Nothing is as it seems. Everyone is a suspect. Everyone has a secret. And no one is safe. Sara is the beautiful young wife of prominent Georgia Senator Jeffrey Collins, and she has gone missing. Through the eyes of Senior FBI Agent Graham Kelton, ambitious reporter Judy Nash and the distraught members of the Collins family, viewers will journey inside a sensational, mysterious national soap opera.",
        poster: "/cHGJJTO4vidVD3CFEbb1YkPS6Ft.jpg",
        posterHorizontal: null,
        voteAverage: 6.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4269,
        title: "The Transformers",
        overview:
          "The Transformers is the first animated television series in the Transformers franchise. The series depicts a war among giant robots that can transform into vehicles and other objects.",
        poster: "/evcHcl8Q3hCRqEIiUHevrHj3B5p.jpg",
        posterHorizontal: "/tT6OSlLvHGM75z2Cvl51WEQ8txU.jpg",
        voteAverage: 7.9,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 85937,
    title: "Demon Slayer: Kimetsu no Yaiba",
    overview:
      "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.",
    poster: "/wrCVHdkBlBWdJUZPvnJWcBRuhSY.jpg",
    posterHorizontal: "/iBAtBLqCMON3NPIjyQ1wdMbpTAk.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "SWAMTXfqer0",
    similar: [
      {
        id: 1906,
        title: "Shameless",
        overview:
          "The story of a young group of siblings pretty much abandoned by their parents, surviving by their wits - and humor - on a rough Manchester council estate. Whilst they won't admit it, they need help and find it in Steve, a young middle class lad who falls for Fiona, the oldest sibling, and increasingly finds himself drawn to this unconventional and unique family. Anarchic family life seen through the eyes of an exceptionally bright fifteen year old, who struggles to come of age in the context of his belligerent father, closeted brother, psychotic sister and internet porn star neighbors.",
        poster: "/kE30UWJvJZ03KIIJMmL6m6YoG0l.jpg",
        posterHorizontal: "/1FWw7Q5gn74tYVsyLdo3AcO3LNR.jpg",
        voteAverage: 7.691,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2260,
        title: "H2O: Just Add Water",
        overview:
          "H2O: Just Add Water revolves around three teenage girls facing everyday teen problems with an added twist: they cope with the burden of growing a giant fin and transforming into mermaids whenever they come in contact with water.",
        poster: "/jSnemLaRSsmsinVRHDJKRb6pviW.jpg",
        posterHorizontal: "/d5jeHsiD9IUa1QL2VSizsEwjiBe.jpg",
        voteAverage: 7.8,
        type: "tv",
        videoUrl: "wqHED34TcwU",
      },
      {
        id: 1941,
        title: "GARO",
        overview:
          '"Where there is light, shadows lurk and fear reigns. But by the blade of Knights, Mankind was given hope."\n\nThe Makai fight a secret war against the demon forces known as Horrors, evil creatures that manifest themselves through darkness to devour Humanity. On the frontlines are the Makai Knights, given the task of watching over a district and eliminating any Horrors that manifest there.\n\nGARO follows the tales of the Knights bearing the title of ‘Golden Knight Garo’, and their duty to vanquish the Horrors and protect Humanity from the darkness.',
        poster: "/3IBGi1F4oRlykR0k9beIwygn8YM.jpg",
        posterHorizontal: "/mvi2YbFePpq68xaHEwezpmSEdsv.jpg",
        voteAverage: 8.412,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2297,
        title: "The Wayans Bros.",
        overview:
          "The Wayans Bros. is a situation comedy that aired from January 1995 to May 1999 on The WB. The series starred real-life brothers Shawn and Marlon Wayans. Both brothers were already well-known from the sketch comedy show In Living Color that aired from 1990 to 1994 on Fox. The series also starred John Witherspoon and Anna Maria Horsford.",
        poster: "/xmbV7HcX9hXvxSvd6WJDBg6GHtr.jpg",
        posterHorizontal: "/bvvkaMU3gYixjxicSHoy8V5Fmqd.jpg",
        voteAverage: 7.232,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2327,
        title: "Dawson's Creek",
        overview:
          "Dawson's Creek is an American teen drama that portrays the fictional lives of a close-knit group of teenagers through high school and college.",
        poster: "/arT93dBemanftfWTcf9I0JRIlxU.jpg",
        posterHorizontal: "/kmBTPt1uh3uTWyIsppQGaaVfRgn.jpg",
        voteAverage: 7.463,
        type: "tv",
        videoUrl: "ntxG68WJzuA",
      },
      {
        id: 2382,
        title: "Freaks and Geeks",
        overview:
          'High school mathlete Lindsay Weir rebels and begins hanging out with a crowd of burnouts (the "freaks"), while her brother Sam Weir navigates a different part of the social universe with his nerdy friends (the "geeks").',
        poster: "/tPqV63zcW6ZV0Hd48DMGb5UzQIG.jpg",
        posterHorizontal: "/1lOGkpGa9SjZ2uP1PxfxDkSXRNs.jpg",
        voteAverage: 8.081,
        type: "tv",
        videoUrl: "E0oJ-uYWakw",
      },
    ],
  },
  {
    id: 83121,
    title: "Kaguya-sama: Love Is War",
    overview:
      "Considered a genius due to having the highest grades in the country, Miyuki Shirogane leads the prestigious Shuchiin Academy's student council as its president, working alongside the beautiful and wealthy vice president Kaguya Shinomiya. The two are often regarded as the perfect couple by students despite them not being in any sort of romantic relationship.",
    poster: "/5khbC6AuNgnvnoDbjIMKCOhEtIc.jpg",
    posterHorizontal: "/dJ8yrSokdTMnhKJw06MllSfCegb.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "rZ95aZmQu_8",
    similar: [
      {
        id: 4457,
        title: "Degrassi High",
        overview:
          "Degrassi High is the third television show in the Degrassi series of teen dramas about the lives of a group of teenagers living on or near De Grassi Street in Toronto, Ontario, Canada. It first aired from 1989 to 1991 and followed the young people from The Kids of Degrassi Street and Degrassi Junior High through high school. The show was filmed in downtown Toronto and at Centennial College.\n\nMuch like its predecessor, Degrassi High dealt with controversial issues ranging from AIDS, abortion, abuse, alcoholism, cheating, sex, death and suicide, dating, depression, bullying, gay rights, homophobia, racism, the environment, drugs, and eating disorders.\n\nThe show's impact on Canadian identity is discussed in the September 2007 issue of u're Magazine.",
        poster: "/wfPUTTbH5zsB7Cupxb7TYtazWPw.jpg",
        posterHorizontal: "/tYaMGzC4vSUZB7hRAPIxcXwJlfG.jpg",
        voteAverage: 8.8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4482,
        title: "Bewitched",
        overview:
          "Samantha Stephens is a seemingly normal suburban housewife who also happens to be a genuine witch, with all the requisite magical powers. Her husband Darrin insists that Samantha keep her witchcraft under wraps, but situations invariably require her to indulge her powers while keeping her bothersome mother Endora at bay.",
        poster: "/7UZVO1SclbgVWM2ELrwWGaS7i94.jpg",
        posterHorizontal: "/xLziWzBx56vKQCwqP6vQy8Dv7Jv.jpg",
        voteAverage: 7.934,
        type: "tv",
        videoUrl: "0oT208N0Xd4",
      },
      {
        id: 4500,
        title: "The Wonder Years",
        overview:
          "The story of Kevin Arnold facing the trials and tribulations of youth while growing up during the 1960s and 70s. Told through narration from an adult Kevin, Kevin faces the difficulties of maintaining relationships and friendships on his enthralling journey into adulthood.",
        poster: "/tkaduqdhFrF1vp8L55OJfB5jw8Z.jpg",
        posterHorizontal: "/XuJi5lKkYLCFpJprfSUZveRof7.jpg",
        voteAverage: 8.378,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5178,
        title: "Stairway to Heaven",
        overview:
          "Song Ju and Jeong Seo who have lost a father and a mother respectively spend their childhood together like real siblings. Song Ju is there for Jeong Seo whenever she feels lonely and has a hard time, and Jeong Seo also relies a lot on Song Ju. However, after Jeong Seo's father gets married to Tae Mi Ra, Mi Ra and her daughter Yu Ri keep harassing Jeong Seo out of jealousy. Tae Hwa, Yu Ri's rough and wild older brother, has a crush on Jeong Seo who is pure and kind unlike him.",
        poster: "/o5hxzWnfIvBioeuLd8Io1Sg3EwG.jpg",
        posterHorizontal: "/mPS95pRUxJnTDXsDfnbXfHn4TaZ.jpg",
        voteAverage: 8.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5255,
        title: "Miss Guided",
        overview:
          "Having navigated the awkward and sometimes traumatic world of high school, Rebecca Freely returns to her alma mater as a guidance counselor, free of the insecurities and orthodontia of her school days. Amidst student behavioral problems and the persistent romantic advances of the male nurse, Gary, Rebecca is certain of one thing - she is interested in the hot auto-shop-turned-Spanish-teacher, Tim. However, much as in high school days of unexpected teenage angst, Lisa, a former cheerleader and nemesis of Rebecca's, returns as the new English teacher determined to make Rebecca relive her unpopular past, setting sights on Tim as well.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 7,
        type: "tv",
        videoUrl: "hKugP2McNGU",
      },
      {
        id: 5279,
        title: "Princess Hours",
        overview:
          "Chae Gyeong is an ordinary high school student. One day, she receives some unexpected news. Because of her grandfathers will, she must marry the unendurable Crown Prince Lee Shin who also attends her high school. Chae Gyeong resists the proposal but reluctantly marries him to help her debt-ridden family. As she struggles to adapt herself to the proper manners and royal duties of palace life and to her disagreeable husband, Lee Shin's sentimental cousin and second-in-line to the throne, Yul, steps into her life.  She feels like she can rely on Yul to help her, but finds it difficult not to worry about her haughty, cold-hearted husband. To help bridge this gap, the senior members of the royal family take some special measures to get them to spend the night together.",
        poster: "/7l2aN9cT7CZ8QPUKknlRsiTAx0k.jpg",
        posterHorizontal: "/aYagJuQhXpeuq9PEc5ktrk9eukc.jpg",
        voteAverage: 7.893,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 65930,
    title: "My Hero Academia",
    overview:
      "In a world where eighty percent of the population has some kind of super-powered Quirk, Izuku was unlucky enough to be born completely normal. But that won't stop him from enrolling in a prestigious hero academy. Now, he'll get his first taste of brutal rivalry from other schools as he braves the cutthroat, no-holds-barred provisional license exam.",
    poster: "/ivOLM47yJt90P19RH1NvJrAJz9F.jpg",
    posterHorizontal: "/3ILMlmC30QUnYkY3XEBOyJ82Dqu.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "EPVkcwyLQQ8",
    similar: [
      {
        id: 4360,
        title: "Iron Chef America",
        overview:
          'Iron Chef America: The Series is an American cooking show based on Fuji Television\'s Iron Chef, and is the second American adaptation of the series, following the failed Iron Chef USA. The show is produced by Food Network, which also carried a dubbed version of the original Iron Chef. Like the original Japanese program, the program is a culinary game show. In each episode, a new challenger chef competes against one of the resident "Iron Chefs" in a one-hour cooking competition based on a secret ingredient or ingredients, and sometimes theme.\n\nThe show is presented as a successor to the original Iron Chef, as opposed to being a remake. The Chairman is portrayed by actor and martial artist Mark Dacascos, who is introduced as the nephew of the original Japanese chairman Takeshi Kaga. The commentary is provided solely by Alton Brown, & Kevin Brauch is the floor reporter. The music is written by composer Craig Marks, who released the soundtrack titled "Iron Chef America & The Next Iron Chef" by the end of 2010. In addition, regular ICA judge and Chopped host Ted Allen provided additional floor commentary for two special battles: Battle First Thanksgiving and Battle White House Produce.',
        poster: "/qHTuJ9LvGlLImr7n8Rg0KaTxG9L.jpg",
        posterHorizontal: "/fzKVh8VDvasbzYUmRNnpV6CRdj.jpg",
        voteAverage: 6.1,
        type: "tv",
        videoUrl: "k6SXLiG2JVc",
      },
      {
        id: 4414,
        title: "Highlander: The Series",
        overview:
          "Duncan MacLeod cannot die -- he is a 400-year-old immortal, who has seen his share of humanity's history. Still, he risks his life in battle against other immortals and tries to save people from harm.",
        poster: "/vwoWfGx0ZYvpK7gTPeen64M0QS5.jpg",
        posterHorizontal: "/AqdGvFyZFi54uUHbIpaXQ7IWhXk.jpg",
        voteAverage: 7.5,
        type: "tv",
        videoUrl: "ypyvcfnu4Gg",
      },
      {
        id: 4418,
        title: "Treasure Hunters",
        overview:
          'Treasure Hunters is a reality television series on NBC and Global Television in which ten teams of three solve puzzles and complete challenges in hopes of solving the ultimate puzzle and winning the grand prize. Teams travel across the United States and Europe in search of seven "artifacts" which when assembled will "lead to the key. Find the key, and find the treasure." The challenges and puzzles are spliced with American history, and the ultimate goal is to find a hidden treasure, leading the show to be compared on various occasions to the film National Treasure. The value of the treasure in the series was revealed on the season finale to be $3,000,000.\n\nThe two-hour premiere episode aired on June 18, 2006 and beginning June 26 the series moved to its regular Monday night timeslot. The season finale was broadcast live on August 21, 2006.\n\nThe Hunt is similar in format to The Amazing Race. Key differences include:\n\n⁕Teams consist of three members as opposed to The Amazing Race\'s usual two\n\n⁕The start location of each leg is not necessarily the end point of the previous leg\n\n⁕Teams start each leg at the same time; Amazing Race teams have staggered starts based on previous leg finish order',
        poster: null,
        posterHorizontal: null,
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4426,
        title: "Ultraman Gaia",
        overview:
          "Ultraman Gaia is a Japanese tokusatsu TV show and is the 13th show in the Ultra Series. Created by Chiaki J. Konaka and produced by Tsuburaya Productions and Mainichi Broadcasting System, Ultraman Gaia was aired on JNN TV stations from September 5, 1998 until August 28, 1999, with a total of 51 episodes.",
        poster: "/88QyfGO9VbeOYNcAPpDeLKhnSya.jpg",
        posterHorizontal: "/uC8OXa2OzdlAgcptPr6GrtUzzDw.jpg",
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4435,
        title: "Grease: You're the One That I Want!",
        overview:
          'Grease: You\'re the One That I Want! was an NBC reality television series designed to cast the lead roles of Sandy Dumbrowski and Danny Zuko in a $10 million Broadway revival of the musical Grease to be directed and choreographed by two-time Tony Award-winner Kathleen Marshall. The Broadway production began previews at the Brooks Atkinson Theatre on July 24, 2007, and officially opened on August 19.\n\nThe TV show, from the producers of Dancing With the Stars, was patterned after an original format created by Andrew Lloyd Webber for the BBC series How Do You Solve a Problem Like Maria?, which selected the lead in the successful 2005 West End revival of The Sound of Music. The show\'s title was taken from the song "You\'re the One That I Want" from the 1978 screen adaptation of Grease. Although the song was not part of the original Broadway production, the revival will add the songs written for the film to those written for the original Broadway production.\n\nThe program generated so much interest in the upcoming Broadway revival that, as The New York Post reported on April 4, 2007, ticket sales had topped $9 million, although the TV show was a "ratings loser".',
        poster: "/duWYjiEK9ed7zmit9uy6ouSYcET.jpg",
        posterHorizontal: null,
        voteAverage: 10,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 5157,
        title: "Ultraman Leo",
        overview:
          "Ultraman Leo is an Ultra foreign to the Land of Light, instead hailing from the fallen Planet L77 of the Leo constellation, where he and his brother Astra were royalty. After his planet was destroyed by Alien Magma and his twin Giras kaiju, Leo traveled to Earth, intending to make it a second home. While there, he blended into human society as Gen Ohtori, and became a gym instructor at a fitness club for children. But, when the Alien Magma that destroyed L77 came to conquer Earth, he was forced to take action. Leo met Ultraseven during his initial fight against Alien Magma, and became the first Ultra Crusader of Earth to not hail from the Land of Light. Unlike most of the previous Ultras to visit Earth, Leo's fighting style specializes in martial arts giving him far greater physical abilities than any other known Ultras. Despite his foreign origins, he, along with Astra, were readily accepted into the pantheon of the Ultra Brothers. During his tenure on Earth, Leo and Seven became very close, and it was for this reason that Seven would eventually entrust the training of his son Ultraman Zero to Leo and Astra.",
        poster: "/mbkWC3HulFfJmkRiggnB1HX0zym.jpg",
        posterHorizontal: "/803olKCJcdCd4cLRXfD7wxAToqd.jpg",
        voteAverage: 7.2,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 80539,
    title: "Asobi Asobase - workshop of fun -",
    overview:
      'During recess, Olivia, a foreign transfer student who doesn\'t know English, plays a game of "look-the-other-way" with Hanako Honda, a loud-mouthed airhead. Their rowdy behavior spurs the ire of Kasumi Nomura, a deadpan loner constantly teased by her older sister for her tendency to lose games. Not willing to compete, Kasumi declines Olivia\'s offer to join the fun, but eventually gets involved anyway and dispenses her own brand of mischief. Soon, a strange friendship blossoms between the peculiar trio, and they decide to form the "Pastime Club," where they are free to resume their daily hijinks.\n\nWhether it be failing to learn English, trying desperately to become popular, or getting caught by teachers at the wrong time, school life will never be boring when these girls are up to their hilarious antics.',
    poster: "/zWE3bnCILcRpfQCsxBkMsgcEjOE.jpg",
    posterHorizontal: "/iLR6tKvMu67oSK0DIgDutkPBaiy.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 2305,
        title: "A Very Peculiar Practice",
        overview:
          "A young and idealistic Doctor Stephen Daker arrives at Lowlands University to work at the Health Centre, but has to cope with an eccentric set of colleagues.",
        poster: "/qQlHuzlQCqT5uSlf0NOeFPGl2ko.jpg",
        posterHorizontal: "/63uJPZFIJJ9SXvncrQqgkexmH4X.jpg",
        voteAverage: 8.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2345,
        title: "Kim Possible",
        overview:
          "If there's danger or trouble, Kim Possible is there on the double to save the world from villains... and still make it home in time for cheerleading practice! Luckily, Kim has her sidekick Ron Stoppable and his pet naked mole-rat Rufus by her side.",
        poster: "/qsDNX8DPwWydDn9oUIhe1WcTuUH.jpg",
        posterHorizontal: "/wCdCMP4RQ5kuEdk9zwZF4p4p7wg.jpg",
        voteAverage: 7.584,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 2349,
        title: "The League of Gentlemen",
        overview:
          "The League of Gentlemen is a British comedy television series that premiered on BBC Two in 1999. The show is set in Royston Vasey, a fictional town in Northern England based on Bacup, Lancashire. It follows the lives of dozens of bizarre townspeople, most of whom are played by three of the show's four writers—Mark Gatiss, Steve Pemberton, and Reece Shearsmith—who, along with Jeremy Dyson, formed the League of Gentlemen comedy troupe in 1995. The series originally aired for three series from 1999 until 2002 followed by a film in 2005. A three-part revival mini-series was broadcast in December 2017 to celebrate the group's 20th anniversary.",
        poster: "/oXe5YFf2b9kQJJmALNFdrGex3FU.jpg",
        posterHorizontal: "/zvthkKsjGM3wrT3Y1elU4pU05n6.jpg",
        voteAverage: 7.5,
        type: "tv",
        videoUrl: "U1sFYAI8nC4",
      },
      {
        id: 904,
        title: "Lincoln Heights",
        overview:
          "Eddie Sutton is a dedicated police officer, his wife Jenn, a devoted nurse, but their most important job is as parents to their three teenage children Cassie, Tay and Lizzie. They're your everyday American family living in the suburbs of Southern California, but the Suttons are thrown for a loop when Eddie decides to move his wife and three kids to the inner-city neighborhood where he grew up.",
        poster: "/sNhsM92gYftNFagus4aUIfj1iJU.jpg",
        posterHorizontal: "/5n2vRCaq06f9RGid9WUpZl0k9dp.jpg",
        voteAverage: 9.2,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 909,
        title: "15 Storeys High",
        overview:
          "15 Storeys High is a critically acclaimed British sitcom, set in a tower block. The main characters are Vince Clark, a misanthropic, cynical recluse played by Sean Lock, and Errol Spears, Vince's exact opposite and whipping boy, played by Benedict Wong.",
        poster: "/hsgp3xqZld98CKfwC47R7jmhDS.jpg",
        posterHorizontal: "/oQMnEPRaFFJFEFAPfr6b6bsM08O.jpg",
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 912,
        title: "Ah! My Goddess",
        overview:
          "Keiichi Morisato is looking forward to university life. But in reality, he has no luck in anything, and he has trouble with clubs, love, etc. The truth is that he has an unlucky star above his head. One day, Keiichi is stuck watching the dorm while his sempai are away, and has a mountain of chores to do to boot. But Keiichi is a good-natured person, and is set about doing his duties. As he is about to finish his final chore, he makes a phone call to his sempai. But the words that came through the receiver are, 'Goddess Help Line.' Shortly afterwards, a beautiful goddess named Belldandy appears in front of him from the mirror of his room.",
        poster: "/5sS5tAeGJNCcxaTSYZSrpEH5TUx.jpg",
        posterHorizontal: "/a75F7prY7RnACDonpUVjGTjoIKe.jpg",
        voteAverage: 7.6,
        type: "tv",
        videoUrl: "_j8HEe4tMDc",
      },
    ],
  },
  {
    id: 31132,
    title: "Regular Show",
    overview:
      "Two bored groundskeepers, Mordecai (a six-foot-tall blue jay) and Rigby (a hyperactive raccoon) are best friends who spend their days trying to entertain themselves by any means necessary, much to the displeasure of their boss. Their everyday pursuits often lead to things spiraling out of control and into the surreal.",
    poster: "/mS5SLxMYcKfUxA0utBSR5MOAWWr.jpg",
    posterHorizontal: "/2vbE9ajftJ7dkqUAyxDS0WFILx8.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "no-url",
    similar: [
      {
        id: 1878,
        title: "The Backyardigans",
        overview:
          "Meet five lively animal friends who love to sing, dance and use their imaginations to embark on outrageous adventures to magical places.",
        poster: "/qph2MAw82C2DTQcuzRQdaglo9eU.jpg",
        posterHorizontal: "/fLI3GFGDjYXIXO5ehdQkeE0zeS0.jpg",
        voteAverage: 8.1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1898,
        title: "Odyssey 5",
        overview:
          "Odyssey 5 is a Canadian science fiction series that first ran in 2002 on Showtime in the United States and on Space in Canada.\n\nOdyssey 5 is the brainchild of Manny Coto, who served as a script-writer and executive producer during the series run. Through his website and in interviews, Coto has expressed his interest in returning to the series at some point, either continuing it or giving it a conclusion.",
        poster: "/cFmvX3lFdBXRkSsTqS2eUoDTdC3.jpg",
        posterHorizontal: "/3wC5gpD417hMzHpgOX3ZV6LyN0V.jpg",
        voteAverage: 6.674,
        type: "tv",
        videoUrl: "SGrKdrUmXkA",
      },
      {
        id: 2304,
        title: "Thomas & Friends",
        overview:
          "Thomas & Friends is a British children's television series, which had its first broadcast on the ITV network on 4 September 1984. It is based on The Railway Series of books by the Reverend Wilbert Awdry and his son, Christopher Awdry. These books deal with the adventures of a group of anthropomorphised locomotives and road vehicles who live on the fictional Island of Sodor. The books were based on stories Wilbert told to entertain his son, Christopher during his recovery from measles. From Series one to four, many of the stories are based on events from Awdry's personal experience.",
        poster: "/s8RtAklJqHo6iMtKz1FIVBm92R2.jpg",
        posterHorizontal: "/wIe1HL7oMNwyltsqqx2sCPwNl4w.jpg",
        voteAverage: 6.428,
        type: "tv",
        videoUrl: "yFG15eydHog",
      },
      {
        id: 967,
        title: "The Huckleberry Hound Show",
        overview:
          "The Huckleberry Hound Show is a 1958 syndicated animated series and the second from Hanna-Barbera following The Ruff & Reddy Show, sponsored by Kellogg's. Three segments were included in the program: one featuring Huckleberry Hound; another starring Yogi Bear and his sidekick Boo Boo; and a third with Pixie and Dixie and Mr. Jinks, two mice who in each short found a new way to outwit the cat Mr. Jinks. The Yogi Bear segment of the show proved more popular than Huckleberry's; it spawned its own series in 1961. A segment featuring Hokey Wolf and Ding-A-Ling was added, replacing Yogi Bear during the 1960–61 season. In 1961, the series became the first animated program to be honored with an Emmy Award. The Huckleberry Hound Show contributed to making Hanna-Barbera a household name, and is often credited with legitimizing the concept of animation produced specifically for television.",
        poster: "/yN0hJ4vjckXkOZtEAXLWvofN2YG.jpg",
        posterHorizontal: "/1lTXCp8kMqBT5TQF3no2pjA3MZ2.jpg",
        voteAverage: 6.833,
        type: "tv",
        videoUrl: "IoaxvehimA0",
      },
      {
        id: 1026,
        title: "Amazing Stories",
        overview:
          "A truly amazing, fantastical, science fiction, funny and odd, and sometimes scary, sad and endearing anthology series presented by Steven Spielberg with guest appearances by many famous actors, actresses, and directors.",
        poster: "/66Utyft9WHPQJSU7f7MbEB72dkc.jpg",
        posterHorizontal: "/zWMLozh8EqIWaSXro59sanaf0mh.jpg",
        voteAverage: 7.535,
        type: "tv",
        videoUrl: "OZKISFPw0Rg",
      },
      {
        id: 788,
        title: "Prehistoric Park",
        overview:
          "Using his knowledge of today’s animal kingdom and the latest research, wildlife adventurer Nigel Marven uses a time portal to take him into the past, on a quest to rescue long lost prehistoric creatures.",
        poster: "/dKTzN99UMHCZIgH8otfSr5gzz9V.jpg",
        posterHorizontal: "/ppPXSqy9wB9vi1rZu6F7X6Xsutw.jpg",
        voteAverage: 7.9,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 246,
    title: "Avatar: The Last Airbender",
    overview:
      "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
    poster: "/cHFZA8Tlv03nKTGXhLOYOLtqoSm.jpg",
    posterHorizontal: "/nLKYAJCEi6OQVji1HJIxSQ74H9s.jpg",
    voteAverage: 8.7,
    type: "tv",
    videoUrl: "IyZ0xetSb9s",
    similar: [
      {
        id: 1714,
        title: "Common As Muck",
        overview:
          "Common As Muck is a gritty BBC comedy drama serial focusing on the lives of a crew of bin men and their management staff. It ran for two series. The first series was screened in 1994 and the second in 1997. Both were nominated for a BAFTA for Best Drama.",
        poster: "/kmuL86GJOCr4ausJeUvU59oIYTs.jpg",
        posterHorizontal: "/Rc9dR7rAKiBuFLNKLPRqKLFdhk.jpg",
        voteAverage: 7.6,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1727,
        title: "Tarzan: The Epic Adventures",
        overview:
          "Tarzan: The Epic Adventures is a syndicated series that aired for one season. It focuses on the character of Tarzan in his early years, after his first exposure to civilization, but before his marriage to Jane. The series uses much of the mythology of Edgar Rice Burroughs' books as background material.\n\nThis version of Tarzan was filmed in the Sun City resort in South Africa, making it one of the few Tarzan productions to actually film on that continent.\n\nThe character of Nicholas Rokoff, and the fact that Tarzan is not yet married, set this series in-between the two halves of The Return of Tarzan.\n\nR. A. Salvatore wrote an authorized Tarzan novel based on pilot script which was published as a trade-paperback in 1996, and a mass-market paperback in 1997.",
        poster: "/drs2sLhaezvxYfnD5ICGZCWcYUr.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1760,
        title: "As Told by Ginger",
        overview:
          "As Told by Ginger focuses on middle schooler Ginger Foutley who, with her friends, tries to become more than a social geek.",
        poster: "/ktwPaU4S7ni0YaMOhIEvLYARjbg.jpg",
        posterHorizontal: "/lXQpWlN24cxwBjNvqOUju2WouDg.jpg",
        voteAverage: 6.254,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1777,
        title: "Boy Meets World",
        overview:
          "The coming of age events and everyday life-lessons of Cory Matthews, a Philadelphian who grows up from a young boy to a married man.",
        poster: "/75a5z9zkh8Rg5lnmWlpEQ2V8rVT.jpg",
        posterHorizontal: "/ex7OI0gG6WeMa9wwRyIOnXgupRE.jpg",
        voteAverage: 8.367,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1786,
        title: "Perfect Strangers",
        overview:
          "The chronicles of the rocky coexistence of midwestern American Larry Appleton and his distant cousin from eastern Mediterranean Europe, Balki Bartokomous.",
        poster: "/wZ7RomWxcrdMwK63XzVeQGFK6Dy.jpg",
        posterHorizontal: "/e22UKY4x8ldlqPrMZTZXxVpsHyi.jpg",
        voteAverage: 6.9,
        type: "tv",
        videoUrl: "zUkEPo8XG4U",
      },
      {
        id: 1375,
        title: "A Step Into The Past",
        overview:
          "A Step into the Past is a 2001 Hong Kong television series produced by TVB and based on Huang Yi's novel of the same Chinese title. The series tells the story of a 21st-century Hong Kong VIPPU officer who travels back in time to the Warring States period of ancient China. He is involved in a number of important historical events that leads to the first unification of China under the Qin Dynasty. The series' first original broadcast ran from 15 October to 7 December 2001 on the TVB Jade network in Hong Kong.",
        poster: "/fVhXei9SNu9hnzRBTKNZzvaMb3x.jpg",
        posterHorizontal: "/sn6naPmfdyLhQVzUB83fpkULknL.jpg",
        voteAverage: 8,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
] as BrowserProps["topRatedTvShowsSimilar"];
