import { BrowserProps } from "pages/browse";

export default [
  {
    id: 772071,
    title: "Cuando Sea Joven",
    overview:
      '70-year-old Malena gets a second chance at life when she magically turns into her 22-year-old self. Now, posing as "Maria" to hide her true identity, she becomes the lead singer of her grandson\'s band and tries to recover her dream of singing, which she had to give up at some point.',
    poster: "/6gIJuFHh5Lj4dNaPG3TzIMl7L68.jpg",
    posterHorizontal: "/ejniJnlOdtSgtbh8D7u2RxT6Uli.jpg",
    voteAverage: 8.8,
    type: "movie",
    videoUrl: "4EXETqcw-k8",
    similar: null,
  },
  {
    id: 238,
    title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    poster: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    posterHorizontal: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    voteAverage: 8.7,
    type: "movie",
    videoUrl: "Ew9ngL1GZvs",
    similar: [
      {
        id: 103675,
        title: "Model by Day",
        overview:
          "Lady X is a woman who works during the day as a model but turns into a fighter for justice at night with the help of her karate master Chang.",
        poster: "/tljlsTmZhf6uHSuhH4gIvvCp4gg.jpg",
        posterHorizontal: "/gadF96nDIadabPpCMN2wIBAJLKj.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "mYCtQrsBgZk",
      },
      {
        id: 103752,
        title: "Here, Beneath the North Star",
        overview:
          "Täällä Pohjantähden alla is based on the book with the same title. It is a story of the little village. The movie starts in the 1890's and it ends to the Finnish civil war in 1918. Story concentrates around a tenant farmer family, although it gives us a good look at the society at whole. While the class struggle depends, people of the village are driven to bloody civil war.",
        poster: "/mKIRPsiK2ZZiF9kJZZe05Czw5kT.jpg",
        posterHorizontal: null,
        voteAverage: 6.6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 89011,
        title: "The Beheaded Rooster",
        overview:
          "A moving coming of age story in a time of extreme change: on August 23, 1944 in a small city in Romanian Transylvania, the 16 year old Felix Goldschmidt awaits his classmates for their traditional Exitus Party (school graduation). However, this very day the kingdom of Romania takes leave of its ally of many years - Nazi Germany - thus ending the 800 year old, highly successful story of ethnic German immigration at the feet of the Carpathian Mountains. It is a great story of young people's blindness to the rise of Fascism, the destruction of bourgeois values, a first love and shattered friendships.",
        poster: "/cFZsaNmTLFG7kRsbLUlqvl9F9ka.jpg",
        posterHorizontal: "/rnFLV66dpxUtzlJYJ3Xfw3YQytm.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "hUfKE9qacDg",
      },
      {
        id: 93911,
        title: "The Wild, Wild World of Jayne Mansfield",
        overview:
          "Jayne takes us on a review of her last world tour. She takes us through Rome, shares a fantasy about Roman athletes, and then is off to Cannes. She takes a trip to the nudist colony on the Isle of Levant, where she almost kind of joins in. Then it's off to Paris, where she gets a beauty treatment from Fernand Aubrey, and attends some racy dance revues. In New York and Los Angeles, she visits some topless clubs and listens to a topless all-girl pop band. The film wraps up with some posthumous footage of her family in mourning.",
        poster: "/Xf9LNvQcEMtcjvyaotQgR3mVDQ.jpg",
        posterHorizontal: "/hCitT24v12TvYb2lDiM66sJ4VdQ.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "Wf3Ix8273Vw",
      },
      {
        id: 94225,
        title: "Bless the Beasts & Children",
        overview:
          "A group of social misfits at a summer camp for boys run away to save penned-in buffaloes from a rifle club's slaughter.",
        poster: "/hOR4Y277BiEAkDd8rwaa87EBq1X.jpg",
        posterHorizontal: "/jrHEAGrVdBucR76OUoTZlg3orGb.jpg",
        voteAverage: 6.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 94341,
        title: "Don Quixote",
        overview:
          "The old hidalgo Don Alonso Quijano, maddened by the excessive reading of books on chivalry and determined to become a famous and heroic knight-errant, leaves his village and sets out on the road in search of adventure, accompanied by his faithful friend Sancho Panza.",
        poster: "/9FkLirPHKWqNkzk0loILXYZv7iJ.jpg",
        posterHorizontal: "/AtpAvH0fuXNonjHDN85jMiOIGrP.jpg",
        voteAverage: 5.1,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 278,
    title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    poster: "/hBcY0fE9pfXzvVaY4GKarweriG2.jpg",
    posterHorizontal: "/wPU78OPN4BYEgWYdXyg0phMee64.jpg",
    voteAverage: 8.7,
    type: "movie",
    videoUrl: "PLl99DlL6b4",
    similar: [
      {
        id: 199425,
        title: "Dog's Heads",
        overview:
          "Dog's Heads (Czech: Psohlavci) is a 1955 Czech drama film directed by Martin Frič, based on the novel of the same name by Alois Jirásek. It was entered into the 1955 Cannes Film Festival.",
        poster: "/vpXrdZeoeWdFUbHVpGpissGrOdq.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199483,
        title: "The Village",
        overview:
          "The Village (German: Sie fanden eine Heimat) is a 1953 Swiss drama film directed by Leopold Lindtberg.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 224251,
        title: "Hunger Point",
        overview:
          "A woman struggles with her self-image in a house run by a weight-obsessed mother, alongside a younger sister whose eating disorder has tragic coincidences.",
        poster: "/sNZNdOuDVqpYwfWr27BpmOxVl69.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 224260,
        title: "Vadh",
        overview:
          "A leading psychologist's much younger wife begins an extramarital affair with his close friend. When the doctor finds out, he plots revenge, which puts himself, his wife, his close friend and his brother in mortal danger.",
        poster: "/wkd1gkp8JIndTA2CNo1vJXobws4.jpg",
        posterHorizontal: null,
        voteAverage: 8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199960,
        title: "The Son of Tarzan",
        overview:
          "Tarzan's son Jack is kidnapped from England by his old enemy Paulovich. Jack escapes into the African jungle where he meets Meriem, a European girl held captive. Freeing her, he falls in love but she's sought by Paulovich. Then Tarzan arrives with Jane to save the day!",
        poster: "/6TJ78ttG3O7pNSN8xBmYBf4nIKm.jpg",
        posterHorizontal: "/vCnah8kXNogx3B9jtB59kMIum5W.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 197246,
        title: "The True Story of Killing Pablo",
        overview:
          "The career and death of notorious Colombian drug kingpin Pablo Escobar.",
        poster: "/lqqip2zXbVpI62ZfEsxLpIqa7t9.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 995133,
    title: "The Boy, the Mole, the Fox and the Horse",
    overview:
      "The unlikely friendship of a boy, a mole, a fox and a horse traveling together in the boy’s search for home.",
    poster: "/oQRgyQCzcyZvE6w5heM9ktVY0LT.jpg",
    posterHorizontal: "/wxaBkuqVIgImjRHEMJoxL9Lq6i8.jpg",
    voteAverage: 8.7,
    type: "movie",
    videoUrl: "609A7IGdoEc",
    similar: [
      {
        id: 223663,
        title: "Green Eyed",
        overview:
          "In the summer of 1980, a successful yuppie faces an existential crisis when a nosferatic ghoul joins his social circle and undermines his social status.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 223709,
        title: "Rhino Full Throttle",
        overview:
          "Bruno is making his way through the city searching for its soul. Driven by his curiosity, a challenging imagination and his wild reflection on reality he is lifting the old dusty curtain on the city's crusted perception.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "G080yTviGVY",
      },
      {
        id: 223734,
        title: "Morning",
        overview:
          "Lyrical debut film of avant-garde/structuralist filmmaker Ernie Gehr. Morning light streams through a window in Gehr's apartment. As Gehr changes the aperture from open to closed and back again, the light pulsates, in turns overwhelmingly bright and almost vanishing in darkness. A beautiful mediation on the essence of cinema and perception.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201003,
        title: "The Family and One More",
        overview:
          "The life of the family inordinate surveyor Carlos Alonso has undergone several changes over the course of the years: the birth of child number 16, little Maria, coincided with the death of the mother, who left behind a hollow refillable. The grandfather also died. The Godfather pastry married, and the boys have been growing rapidly ...",
        poster: "/8bz1FKL9bPbIvHBHl0DeudexUZN.jpg",
        posterHorizontal: "/4U353J7OxDEl9HxohOgJ63LSlH2.jpg",
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201004,
        title: "Self-Fashion Show",
        overview: "Self fashion show.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199414,
        title: "Joy Street",
        overview:
          "A nightmare of a woman depressed by the concrete world she lives in, and her journey from suicidal despair to personal renewal with the help of an unlikely spirit guide.",
        poster: "/Npfi9pqT3dKs24zdv6zVLUMdYy.jpg",
        posterHorizontal: "/kM96GO9jr35jRJWvFFmOhVgzUKV.jpg",
        voteAverage: 7,
        type: "movie",
        videoUrl: "6fPUJIHITrY",
      },
    ],
  },
  {
    id: 240,
    title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    poster: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    posterHorizontal: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "rcU6DUUUd7k",
    similar: [
      {
        id: 103675,
        title: "Model by Day",
        overview:
          "Lady X is a woman who works during the day as a model but turns into a fighter for justice at night with the help of her karate master Chang.",
        poster: "/tljlsTmZhf6uHSuhH4gIvvCp4gg.jpg",
        posterHorizontal: "/gadF96nDIadabPpCMN2wIBAJLKj.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "mYCtQrsBgZk",
      },
      {
        id: 103690,
        title: "Fasthand",
        overview:
          'Macedo, bloodthirsty leader of a gang of  Confederates shoots the captain of the Northerners, Jeff Mallighan, known as "Fast Hand", shattering his right hand. Jeff, wounded on the ground, could not see the face of the villain, but his silver spurs have stuck in his mind as well as his unique gun. Some time after this event Macedo continues with his misdeeds, however, a mysterious horseman dressed in black will stand in his way.',
        poster: "/fFf7gupwpT4KkVZk8IpoOtr1Jvp.jpg",
        posterHorizontal: "/wZYejgKwjdet2syu1vS24zB3dsg.jpg",
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 103794,
        title: "Serpent's Path",
        overview:
          "Miyashita, a former low-level yakuza member, has tracked down and kidnapped his daughter's murderer with help of his friend Nijima. But others are soon implicated in the death, leading the pair further down a violent path of revenge.",
        poster: "/kHUsXCAtjwQCcyCE8uLpksRt40M.jpg",
        posterHorizontal: "/wo4PrAv907tC2vIpft5XidTSEYS.jpg",
        voteAverage: 6.8,
        type: "movie",
        videoUrl: "RgkoNmmMApQ",
      },
      {
        id: 89072,
        title: "Ginger",
        overview:
          "The police suspect that a drug and forced-prostitution ring is behind the recent spate of kidnappings and disappearances, but so far they've been unable to infiltrate the suspects gang. To break the case, they recruit Ginger, a young woman from an upper-class family to act as bait for the kidnappers and hopefully lead the police to their hideout. It may sound like a foolproof plan to the police, but Ginger's the one who has to risk it all.",
        poster: "/dONQlfaIj0QfVNoBnjEEH0ok1gK.jpg",
        posterHorizontal: "/gPfCZr4ZC20EfbdcvU9DnyTfVqJ.jpg",
        voteAverage: 3.6,
        type: "movie",
        videoUrl: "zke7TSVo1mU",
      },
      {
        id: 93911,
        title: "The Wild, Wild World of Jayne Mansfield",
        overview:
          "Jayne takes us on a review of her last world tour. She takes us through Rome, shares a fantasy about Roman athletes, and then is off to Cannes. She takes a trip to the nudist colony on the Isle of Levant, where she almost kind of joins in. Then it's off to Paris, where she gets a beauty treatment from Fernand Aubrey, and attends some racy dance revues. In New York and Los Angeles, she visits some topless clubs and listens to a topless all-girl pop band. The film wraps up with some posthumous footage of her family in mourning.",
        poster: "/Xf9LNvQcEMtcjvyaotQgR3mVDQ.jpg",
        posterHorizontal: "/hCitT24v12TvYb2lDiM66sJ4VdQ.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "Wf3Ix8273Vw",
      },
      {
        id: 94005,
        title: "No Place To Hide",
        overview:
          "Detective Joe Garvey is called in to a mysterious case: a ballerina has been slayed on stage during a performance, it seems she didn't even fight. At her house Garvey finds her 14 years old precocious sister Tinsel. She's not very cooperative, so he arranges to have her sent to the orphanage -- until she's attacked too. He takes her under his wings, and soon both get the attention of a secret organization.",
        poster: "/xsgAsIvzNk761Xdyijiem6LlWl8.jpg",
        posterHorizontal: "/hPjfe7sgEeK6qagrl4Ldhaa3spf.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "0xN2dVE9yfs",
      },
    ],
  },
  {
    id: 424,
    title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    poster: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    posterHorizontal: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "mxphAlJID9U",
    similar: [
      {
        id: 103751,
        title: "Under the North Star II",
        overview:
          "Akseli Koskela returns from prison and tries to learn living again. He's not allowed to take part in politics anymore, but he sees a lot of injustice around him. He raises a family with his wife Elina while another war is around the corner...",
        poster: "/8YxOMgILu2mhBox1jmjgTC49Lfb.jpg",
        posterHorizontal: null,
        voteAverage: 6.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 103752,
        title: "Here, Beneath the North Star",
        overview:
          "Täällä Pohjantähden alla is based on the book with the same title. It is a story of the little village. The movie starts in the 1890's and it ends to the Finnish civil war in 1918. Story concentrates around a tenant farmer family, although it gives us a good look at the society at whole. While the class struggle depends, people of the village are driven to bloody civil war.",
        poster: "/mKIRPsiK2ZZiF9kJZZe05Czw5kT.jpg",
        posterHorizontal: null,
        voteAverage: 6.6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 89011,
        title: "The Beheaded Rooster",
        overview:
          "A moving coming of age story in a time of extreme change: on August 23, 1944 in a small city in Romanian Transylvania, the 16 year old Felix Goldschmidt awaits his classmates for their traditional Exitus Party (school graduation). However, this very day the kingdom of Romania takes leave of its ally of many years - Nazi Germany - thus ending the 800 year old, highly successful story of ethnic German immigration at the feet of the Carpathian Mountains. It is a great story of young people's blindness to the rise of Fascism, the destruction of bourgeois values, a first love and shattered friendships.",
        poster: "/cFZsaNmTLFG7kRsbLUlqvl9F9ka.jpg",
        posterHorizontal: "/rnFLV66dpxUtzlJYJ3Xfw3YQytm.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "hUfKE9qacDg",
      },
      {
        id: 94047,
        title: "My Way",
        overview:
          "During the invasion of Normandy the photograph of a slim Korean man in German uniform was found. It transpired that the man had served as a soldier in the Japanese, Russian and German armies. His incredible story inspired director Kang Je-Gyu to create this epic war drama.",
        poster: "/3moPqIC1EBFilLI3YJNa5Nfel3e.jpg",
        posterHorizontal: "/4QHF7kAYjIpZ5U8A0amvhRkHlZ1.jpg",
        voteAverage: 8,
        type: "movie",
        videoUrl: "d8wjl1jHzro",
      },
      {
        id: 94225,
        title: "Bless the Beasts & Children",
        overview:
          "A group of social misfits at a summer camp for boys run away to save penned-in buffaloes from a rifle club's slaughter.",
        poster: "/hOR4Y277BiEAkDd8rwaa87EBq1X.jpg",
        posterHorizontal: "/jrHEAGrVdBucR76OUoTZlg3orGb.jpg",
        voteAverage: 6.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 94241,
        title: "Sundown",
        overview:
          "Englishmen fighting Nazis in Africa discover an exotic mystery woman living among the natives and enlist her aid in overcoming the Germans.",
        poster: "/4R2c2fp9wULd5W57myi3hUy5mKi.jpg",
        posterHorizontal: "/mzmSRpqkPbdJdo3580WPDrf7Mog.jpg",
        voteAverage: 5.6,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 19404,
    title: "Dilwale Dulhania Le Jayenge",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    poster: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    posterHorizontal: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "oIZ4U21DRlM",
    similar: [
      {
        id: 199484,
        title: "The Three Perfect Married",
        overview:
          "Three married couples gather to celebrate the eighteenth anniversary of their marriage mourning the absence of a friend who was best man at all three weddings.",
        poster: "/jYM5SgfHES9XY1N9bKncSjyyaCx.jpg",
        posterHorizontal: "/uVxrx8j6G8OGESFN27Oatx5MSQg.jpg",
        voteAverage: 4.4,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201644,
        title: "Sweet Music",
        overview:
          "A midwest band leader and his lead singer share a love-hate relationship as they try for success in New York.",
        poster: "/9QzGmZCTtL1GsbINGgxbUc9nO59.jpg",
        posterHorizontal: "/bb38hyPymAMo3p87sP7rw1Uhx06.jpg",
        voteAverage: 4.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 193321,
        title: "The Deep Blue Sea",
        overview:
          "A woman is unhappy in her marriage to a boring, stiff judge, so she takes up with a wild-living RAF pilot, who ends up being more than she can handle. (TCM.com)",
        poster: "/98TFnJ8GZlbBnbCZ6v8IIcdCPsP.jpg",
        posterHorizontal: "/AbfXLaKxVZhmcY0pKXAeHdaL8fF.jpg",
        voteAverage: 5.1,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 192236,
        title: "Tales from the Vienna Woods",
        overview:
          "Based on a popular 1931 play, the film tells the fate of a naive young woman named Marianne, who breaks off her reluctant engagement with Oskar the butcher after falling in love with a fop named Alfred who, however, has no serious interest in returning her love. For this error, she must pay bitterly.",
        poster: "/CSix0kzvnDsbXOExTWlnzVtLlW.jpg",
        posterHorizontal: null,
        voteAverage: 6.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 193473,
        title: "A Family of Three",
        overview:
          "When novelist Andrea Dewenter dies in a car accident, the lives of her husband Christian, grown-up son Lars, and adolescent daughter Elaine go off the rails. For all three, the few days between Andrea's sudden death and her funeral turn into an emotional roller coaster that eventually shows them the virtue of being a family.",
        poster: "/ud9KufAFU2JNwROiPBZvWEieORV.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "RWV_hUhhNrQ",
      },
      {
        id: 184955,
        title: "I Take This Woman",
        overview:
          "On return from Europe Dr. Decker foils glamour girl Georgi  from jumping overboard.  At Decker's suggestion to  keep busy, she assists at his clinic in the slums.",
        poster: "/iZmc2DmfAIi4D1A1t34qrrTFH3U.jpg",
        posterHorizontal: "/pwBPTlocYMu90vFZFSbRvFfL62q.jpg",
        voteAverage: 7.6,
        type: "movie",
        videoUrl: "JXNbmlK4rUU",
      },
    ],
  },
  {
    id: 129,
    title: "Spirited Away",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    poster: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    posterHorizontal: "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "ByXuk9QqQkk",
    similar: [
      {
        id: 223780,
        title: "13 Witches",
        overview:
          "13 Witches is a fantasy horror story where 13 sisters who practiced paganism, centuries ago, were wrongfully accused of being witches. They were tortured, punished and burned alive by those they loved. Only one of the sisters escaped: Nemsis  A deal is struck between Nemesis and the devil can centuries later, the sisters have been reincarnated seek revenge on the ones who stole their lives.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "3HrFj5K_i6s",
      },
      {
        id: 199470,
        title: "Modern People",
        overview:
          "A section chief at the Bureau of Construction is in a shady relationship with a construction company. Then a new, young and honest subordinate is assigned to work under the section chief. Once he learns about the shady relationship, however, the new subordinate skillfully conceals the corruption and joins the corrupt, shady relationship.",
        poster: "/2fZCRNSycJbgZAbBetd6phbSkyg.jpg",
        posterHorizontal: null,
        voteAverage: 4,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 224328,
        title: "The Cemetery",
        overview:
          "Deep in the Pennsylvania hills, a cemetery for those who died during exorcism remains a dark secret for the church. In 1671, hundreds of men, women, and children suffered in bloody, torturous rituals at the hands of priests unable to contain the evil of the possessed. Were these possessions real, or is the story a hoax to cover up the sins of the deranged priests thirsty for human blood? Bill and his team of cynical paranormal investigators plan to find out the truth.  Armed with the church's historical record, they set out into the wilderness to uncover this series of forgotten atrocities. Alternately gut-punching hilarious and brutally violent, The Cemetery takes the best elements of the old-school slasher film and pushes them to the edge.",
        poster: "/mVAsW6zKNEwFK3itCjZ7znok3Ru.jpg",
        posterHorizontal: null,
        voteAverage: 4.7,
        type: "movie",
        videoUrl: "60NPZYwxHas",
      },
      {
        id: 201989,
        title: "Bottles",
        overview:
          "A dark and stormy night in a drugstore. The druggist mixes a potion and falls asleep. The skull-and-crossbones on the bottle comes to life and drips the potion on the druggist.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201676,
        title: "My Little Pony: Equestria Girls",
        overview:
          "Via a magic mirror, Twilight Sparkle travels into an alternate universe in order to recover a crown that was stolen from the Crystal Empire. Upon her arrival she is horrified to learn that she has turned into a human.",
        poster: "/zT92hPXA5X6ppKjnjf9VfU51aR8.jpg",
        posterHorizontal: "/pORRrfflRb1nOpqlVxeyPntdqn3.jpg",
        voteAverage: 7.3,
        type: "movie",
        videoUrl: "c3hBtBibN_M",
      },
      {
        id: 197249,
        title: "Andre omgang",
        overview:
          "Andre omgang is the story of a father and his two sons trying to adjust to life's later summers; the father becomes a member of a singles' club, Sverre joins a swingers club, and Erik finds a new woman to live with. The three of them are passionate supporters of Skeid Football Club.",
        poster: "/9ShIMSqa2Oev1HO8Ws26NArs36J.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 389,
    title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    poster: "/ppd84D2i9W8jXmsyInGyihiSyqz.jpg",
    posterHorizontal: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "TEN-2uTi2c0",
    similar: [
      {
        id: 75318,
        title: "Hood of the Living Dead",
        overview:
          "Death is only the beginning for the young victim of a drive-by shooting. Devastated at the loss of his younger brother Jermaine, scientific older sibling Ricky uses the situation as an opportunity to test an experimental serum designed to breathe new life into dead cells. Though Ricky's reanimation serum does indeed help to get his previously deceased younger brother back on his feet, Jermaine's insatiable hunger for human flesh soon spreads like wildfire throughout the neighborhood, leaving his older brother to find a way to halt the epidemic before the army of flesh-eaters become too powerful to be contained.",
        poster: "/dAcvrETlNAkw2ClkAvAPx5o4c6X.jpg",
        posterHorizontal: null,
        voteAverage: 4,
        type: "movie",
        videoUrl: "rpbzsSj-ubQ",
      },
      {
        id: 80279,
        title: "Blind Alley",
        overview:
          "A serial killer traps and taunts a young dancer inside a laundromat that located down an isolated alley.",
        poster: "/57ZbYBtXomPjqv3fYmdIu7Fh4GD.jpg",
        posterHorizontal: "/nQ57n55bwt2fL5w9b5VqVzCVGX8.jpg",
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "IDgIqk1rsrg",
      },
      {
        id: 83726,
        title: "Beyond Therapy",
        overview:
          "Manhattanites Bruce and Prudence are each looking for a meaningful romantic relationship and have been encouraged by their psychiatrists to find someone through the personal ads. Their first meeting is disastrous, but they begin to hit it off during their second date. However, Bruce's bisexual, live-in lover does not want to share Bruce and is willing to do whatever it takes to keep him to himself.",
        poster: "/Vxze4bRPNlEH2rysi3cl5zYyA8.jpg",
        posterHorizontal: "/ta82slt4Cv729dvD54TyAiFQJXV.jpg",
        voteAverage: 3.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83786,
        title: "Machete",
        overview:
          'This 1959 film noir take on "Othello," filmed in Puerto Rico, stars Mari Blanchard as flirtatious Jean, who marries an older man, plantation owner Don Luis (Albert Dekker), for financial security and finds herself falling for his virile foster son, Carlos (Carlos Rivas). Fearing that Jean will inherit Luis\'s money, his greedy cousin, Miguel (Lee Van Cleef), poisons the bridegroom against his new wife, informing him about her passion for another.',
        poster: null,
        posterHorizontal: null,
        voteAverage: 6.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83801,
        title: "Guilty",
        overview:
          "Investigates the corrupt judicial system under which Alain Mar'caux and his wife Edith were arrested on accusations of pedophilia horrific acts they never committed- and the years he spent fighting to get out of prison, clear his name and keep his family.",
        poster: "/yCXkchvR7mol5GuHnGv9P98hfbV.jpg",
        posterHorizontal: "/eF8xdU1zbaCpD7W19bK6zl76Krn.jpg",
        voteAverage: 7.3,
        type: "movie",
        videoUrl: "MckK5rnpo-s",
      },
      {
        id: 94680,
        title: "One Night In Lisbon",
        overview:
          "Saucy screwball comedy wherein lovely Madeleine falls in love with flier Fred despite interference from her fiancee and his ex.",
        poster: "/9ilCSS1xaZGFaWbfKjCRFtPPxo1.jpg",
        posterHorizontal: "/9QraoQyLJ0EtftOdhUMU1xoe6xM.jpg",
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 372058,
    title: "Your Name.",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    poster: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    posterHorizontal: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "o4-URMnBOPU",
    similar: [
      {
        id: 201088,
        title: "Blackhat",
        overview:
          "Nicholas Hathaway, a furloughed convict, and his American and Chinese partners as hunt a high-level cybercrime network from Chicago to Los Angeles to Hong Kong to Jakarta. As Hathaway closes in, the stakes become personal as he discovers that the attack on a Chinese nuclear power plant was just the beginning.",
        poster: "/7zu6HPnKPjNA7NuR4DGRdaH0PdX.jpg",
        posterHorizontal: "/1u7TuvR5mSUz2xRQhz01i75IwdT.jpg",
        voteAverage: 5.471,
        type: "movie",
        videoUrl: "-CA95Bzpy7s",
      },
      {
        id: 199436,
        title: "Flesh and the Woman",
        overview:
          "In this romance, a jilted lawyer joins the French Foreign Legion to help him forget his faithless love. While in the desert he espies a village beauty who is the exact double of his true-love.",
        poster: "/4HnRL1WckVuRL6VFvoLnDbjNb3R.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 196801,
        title: "Yamudiki Mogudu",
        overview:
          "Yamudiki Mogudu: Ee Nela Thakkuvodu is a 2012 released Telugu socio-fantasy and comedy film directed by E. Satti Babu.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 196892,
        title: "Meeting Place",
        overview:
          "During the excavation of ancient Roman ruins, an old archaeology professor accidentally opens the gate between our world and the world of the dead.",
        poster: "/3NGsL5l8YRbdo7HGXNvxc1oj85i.jpg",
        posterHorizontal: "/erWQG6yXhLRHBp82Aprn8IhayAR.jpg",
        voteAverage: 7.3,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 195771,
        title: "Masani",
        overview:
          "The brother of a rich landlord falls in love with a lower caste girl but his haughty sister-in-law murders him. The girl, who is pregnant with his child, is made an outcast and dies during childbirth only to return as a ghost and haunt the village.",
        poster: "/kOgf1D7XprZ0Om88CIfHF2M0Qts.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "cQ1da95I6So",
      },
      {
        id: 195810,
        title: "Penrod and Sam",
        overview:
          "Best pals Penrod and Sam are leaders of a super-secret neighborhood society, the In-Or-In Boys Club. Troubles arise when a pompous prig tries to join the club and when the boys lose their clubhouse in a land sale. But there’s also plenty of time to play pranks, put on a carnival, experience the pangs of first love, and romp with Duke, the world’s best dog.",
        poster: "/fsgVJLlxcLcqkINnkCiT8ofREAF.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 496243,
    title: "Parasite",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    posterHorizontal: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "tBfgTZsBeFM",
    similar: [
      {
        id: 72900,
        title: "Manolito Four Eyes",
        overview:
          "The usually absent father of a chubby kid shows up to take him on a road trip.",
        poster: "/sMpadtIgnuAaT7GknqOH8lgrVkS.jpg",
        posterHorizontal: "/7CkzrRSshO6sOjxSSzSu7gsshLD.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "pH7NocxK324",
      },
      {
        id: 80327,
        title: "I Am I",
        overview:
          "I AM I is the story of a young woman, Rachael, who meets the father she never knew, Gene, at her mother's funeral. She discovers that her father is completely delusional and believes her to be her dead mother. After Rachael visits Gene in an assisted living home, she learns that he suffers from a disease called Korsakov's Syndrome, a form of retrograde amnesia and that her mother had placed him in this facility for treatment a year earlier. He does not remember anything past the age of thirty-three, and believes that he is still a young man. Unable to convince him of who she really is, Rachael decides to go along with her father's delusions by pretending to be her mother and discovers that under this guise, she and Gene can have \"normal\" conversations. Before long, Rachael is visiting Gene everyday, finding new ways to bring elements from his past into their present relationship.",
        poster: "/z1RwTKQ0wvkdVmQoWqAW5Vcy8Ag.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "hOExdPW474k",
      },
      {
        id: 80624,
        title: "The Godsend",
        overview:
          "An English family of six takes in a pregnant woman who disappears shortly after giving birth. They raise the baby girl as their own, but over the years the strange deaths of their children make them consider whether the little girl is more than she appears.",
        poster: "/hOTrOQ8pXTQhydtEDyRFI9Dn3w4.jpg",
        posterHorizontal: "/mLdkXarWPOV1wVbea2n4294rfve.jpg",
        voteAverage: 5.4,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 90511,
        title: "Welfare",
        overview:
          "WELFARE shows the nature and complexity of the welfare system in sequences illustrating the staggering diversity of problems that constitute welfare: housing, unemployment, divorce, medical and psychiatric problems, abandoned and abused children, and the elderly. These issues are presented in a context where welfare workers as well as clients struggle to cope with and interpret the laws and regulations that govern their work and life.",
        poster: "/1eFgNI93rRSOFZZ9cajF3tMmGPc.jpg",
        posterHorizontal: "/krXItN3hWp5bFQjEPV1Ei0Q0CcE.jpg",
        voteAverage: 6.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83715,
        title: "Sweethearts",
        overview:
          "A man finds himself wondering just what he wants from a relationship after his personal ad gets a very unexpected response in Sweethearts.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 2.7,
        type: "movie",
        videoUrl: "b7MgC6pAcTI",
      },
      {
        id: 83802,
        title: "The Gong Show Movie",
        overview:
          'A week in the life of "The Gong Show" host and creator Chuck Barris.',
        poster: "/nXiyk4IBxHgUR6yri5BB1OtSgI7.jpg",
        posterHorizontal: null,
        voteAverage: 4.2,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 497,
    title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    poster: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    posterHorizontal: "/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "Bg7epsq0OIQ",
    similar: [
      {
        id: 72774,
        title: "Once You Kiss a Stranger...",
        overview:
          "Jerry, a Southern California golf pro is the target for Diana a disturbed young woman who desires the death of her shrink, who alone realizes her psychotic potential and seeks to have her committed. She suggests to Jerry that they \"swap\" murders - she'll kill his golf rival and he'll reciprocate by killing her psychiatrist. When she holds up her half of the bargain, she expects him to follow through with his end.",
        poster: "/4nSPrnV2ejc9LepfojZjCu7MTa1.jpg",
        posterHorizontal: "/wb89qZ7hKLWPxx4sNk3J5DA9tOK.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 72819,
        title: "Ward No. 6",
        overview:
          "Simultaneously nihilistic and heartening, Ward No. 6 is based on a story by Chekov, in which a psychiatric doctor becomes a patient in his own asylum. Updated to contemporary Russia, the film is a cocktail of anxieties and riddles, showcasing how easy it is to become what we fear most.",
        poster: "/oPkay3Up3iPcRiWHsnjwQldgaJ0.jpg",
        posterHorizontal: "/shKRjIX2OgzPLRCcbp6zHcdYwlZ.jpg",
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 72831,
        title: "Les lutteurs immobiles",
        overview:
          "The consumer society is dead. Welcome to the preservation society! As of their first school year, children are taught to love objects, which most of them do. But not all citizens. To remedy the problem, The security forces crack down on vandals, bands of protesters and other iconoclasts. And for greater efficiency the States uses the services of Kief, a mad scientist who operates on prisoners so as to pair them with totem-objects. Which is why Judith gets wrinkles when her clothes are creased. Which is why the skin of librarian Mikoski gets pierced with holes whenever rats gnaw at his books.",
        poster: "/peSGNxQwD0TuyLGLVEh4AfltPU1.jpg",
        posterHorizontal: null,
        voteAverage: 8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 72881,
        title: "I Walk the Line",
        overview:
          "Henry Tawes, a middle-aged sheriff in a rural Tennessee town, is usually the first man to criticize others for their bad behavior. Miserable in his marriage, Henry falls in love with teenage seductress Alma, who is the daughter of local criminal and moonshiner Carl McCain. Henry's moral character comes further into question when he is tempted to conceal Carl's crimes in order to prolong his relationship with Alma.",
        poster: "/slwnnOlNcCpgUEQHZXx6FYDYkRJ.jpg",
        posterHorizontal: "/1egcm5poKE8ucuo1uetX07FaAtr.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "4uhv3uR6ZYc",
      },
      {
        id: 72900,
        title: "Manolito Four Eyes",
        overview:
          "The usually absent father of a chubby kid shows up to take him on a road trip.",
        poster: "/sMpadtIgnuAaT7GknqOH8lgrVkS.jpg",
        posterHorizontal: "/7CkzrRSshO6sOjxSSzSu7gsshLD.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "pH7NocxK324",
      },
      {
        id: 75042,
        title: "Convicts 4",
        overview:
          "After his death sentence is commuted to life in prison, John Resko is transferred from Sing-Sing to Dannemora where, with the help of a humane prison guard, he becomes a rehabilitated man and a successful painter.",
        poster: "/vuo3Nmli0SZtAc7kYnZxG6aqhAv.jpg",
        posterHorizontal: "/1SDBqVlL6Tg6D2rTBKCKZzTqO1S.jpg",
        voteAverage: 5.2,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 155,
    title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    poster: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    posterHorizontal: "/pbEkjhdfP7yuDcMB78YEZwgD4IN.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "kmJLuwP3MbY",
    similar: [
      {
        id: 2395,
        title: "Astérix at the Olympic Games",
        overview:
          "Astérix and Obélix have to win the Olympic Games in order to help their friend Alafolix marry Princess Irina. Brutus uses every trick in the book to have his own team win the game, and get rid of his father Julius Caesar in the process.",
        poster: "/eNB2SrqmTJLByRDq3akDzA6Z9rC.jpg",
        posterHorizontal: "/2PuEmuXQF3XQZp8Ki2mGJXUGEOd.jpg",
        voteAverage: 5.185,
        type: "movie",
        videoUrl: "I4IwYe5N1o0",
      },
      {
        id: 103675,
        title: "Model by Day",
        overview:
          "Lady X is a woman who works during the day as a model but turns into a fighter for justice at night with the help of her karate master Chang.",
        poster: "/tljlsTmZhf6uHSuhH4gIvvCp4gg.jpg",
        posterHorizontal: "/gadF96nDIadabPpCMN2wIBAJLKj.jpg",
        voteAverage: 3,
        type: "movie",
        videoUrl: "mYCtQrsBgZk",
      },
      {
        id: 103782,
        title: "Snoopy: The Musical",
        overview:
          'The animated adaption of the second stage musical based on the "Peanuts" comics strip, focusing on Snoopy.',
        poster: "/2yWCJkXkd9NWs68aYUiyf9ppiFJ.jpg",
        posterHorizontal: null,
        voteAverage: 6.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 89098,
        title: "Union City",
        overview:
          "A 1950s accountant with a restless wife grows paranoid after hiding a milk thief's corpse next door.",
        poster: "/qhZ4O5ujhnfeGEfGJZpHTyZysIM.jpg",
        posterHorizontal: "/nhUwUwQtnSXCWGdu358poTTih8D.jpg",
        voteAverage: 4.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 104308,
        title: "The Spider Labyrinth",
        overview:
          "A young professor travels to Budapest to locate a lost colleague. Once there, he gets tangled up in a supernatural mystery.",
        poster: "/AbkpVmqWQcbifw0Push788KGI45.jpg",
        posterHorizontal: "/rXJG45RN9sPd3AcRHb1nofjJYzf.jpg",
        voteAverage: 6.4,
        type: "movie",
        videoUrl: "O0Coq2XrwmE",
      },
      {
        id: 89651,
        title: "Loaded Guns",
        overview:
          "An air hostess gets involved in Naples, against her will, in the in-fighting amongst rival gangs.",
        poster: "/1YVYYj0PwjD1Iwf3zervQABWcaf.jpg",
        posterHorizontal: "/ee4Rpm82UQx8vDhk6Epax7eVzcV.jpg",
        voteAverage: 4.6,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/tGwO4xcBjhXC0p5qlkw37TrH6S6.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 72762,
        title: "Jack and the Beanstalk",
        overview:
          "A retelling of the popular fairy tale that mixes live action and animation.",
        poster: "/prD4GSmkzW8XbZKhZpW4wQ9dI3Q.jpg",
        posterHorizontal: "/qtMMIqLhk5SVJMRuoKgHcM6G3PC.jpg",
        voteAverage: 7.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 75098,
        title: "Lotte Reiniger: The Fairy Tale Films",
        overview:
          "Lotte Reiniger was one of the twentieth century’s major animation artists, pioneering a distinctive style of black and white silhouette animation in her interpretations of classic myths and fairy tales. Reiniger began her career in Germany, making The Adventures of Prince Achmed, one of the first and most ingenious full-length animated films in the history of cinema. After the war, she moved to Britain with her husband Carl Koch and made short films for the GPO and later, in collaboration with Primrose Productions, an extensive series of famous fairy tale short films. This is a DVD collection of her work.",
        poster: "/vsjDHSXs80FJGGUD7qzijMn7NSD.jpg",
        posterHorizontal: "/pz3TXUZOJkws4wp2weW1yo4zUeW.jpg",
        voteAverage: 9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80304,
        title: "Casa De Mi Padre",
        overview:
          "Scheming of a way to save their father's ranch, the Alvarez brothers find themselves in a war with Mexico's most feared drug lord.",
        poster: "/kVCc7xwTAlckBofazrwIz8x1TXC.jpg",
        posterHorizontal: "/bTy0LQEXValfIemrLvE5dMJobE4.jpg",
        voteAverage: 5.38,
        type: "movie",
        videoUrl: "01IYDy2Gdk4",
      },
      {
        id: 90512,
        title: "The Frog Princess",
        overview:
          "A prince discovers an enchanted beauty turned into a frog by Koschei the Immortal. After Koschei steals her again, the prince goes on a dangerous quest to free the land of the evil.",
        poster: "/qa6gtK1T1wMebluGMv5c7KANK90.jpg",
        posterHorizontal: "/3UaeEyh0yJEYGxtPqRu9TwaWz4i.jpg",
        voteAverage: 7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83811,
        title: "The Daydreamer",
        overview:
          "In this hybrid of live-action and stop-motion animation, a young Hans Christian Andersen goes in search of knowledge in the Garden of Paradise in order to make his studies easier. Each time he falls asleep, he experiences in his dreams the different characters he would later write about in fairy tales including The Little Mermaid, Thumbelina and The Emperor's New Clothes.",
        poster: "/k7RiyeB5NccB2NgXtVFJXFiwe6Z.jpg",
        posterHorizontal: "/1D05GkR8sJDzGuQirq26q1tIQgX.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 82990,
        title: "Paranormal Activity 4",
        overview:
          "It has been five years since the disappearance of Katie and Hunter, and a suburban family witness strange events in their neighborhood when a woman and a mysterious child move in.",
        poster: "/na5tAslm1kGNcft083AIXMTOsYR.jpg",
        posterHorizontal: "/eq68gWGBtumauGYFV1FCJ20kXFU.jpg",
        voteAverage: 5.418,
        type: "movie",
        videoUrl: "P1wbwf0wayk",
      },
    ],
  },
  {
    id: 680,
    title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    poster: "/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg",
    posterHorizontal: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "tGpTpVyI_OQ",
    similar: [
      {
        id: 201085,
        title: "Crimson Peak",
        overview:
          "In the aftermath of a family tragedy, an aspiring author is torn between love for her childhood friend and the temptation of a mysterious outsider. Trying to escape the ghosts of her past, she is swept away to a house that breathes, bleeds… and remembers.",
        poster: "/s6cFBCAlfFBwBKVgJOme3JpjZLo.jpg",
        posterHorizontal: "/cXfFzGNpVu07sROfyTuIU2SadoO.jpg",
        voteAverage: 6.64,
        type: "movie",
        videoUrl: "oquZifON8Eg",
      },
      {
        id: 224354,
        title: "Anna's Struggle",
        overview:
          "Anna is a woman who sells flowers at the local market and whose only hope and joy in her life is her only son Amaurys. Raul, Amaurys' best friend, involves him in a drug deal which results in his death.",
        poster: "/wQyvkz4H0FouBMoyjNejwqahlca.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 200085,
        title: "The Flu",
        overview:
          "A case of the flu quickly morphs into a pandemic. As the death toll mounts and the living panic, the government plans extreme measures to contain it.",
        poster: "/mvTXhTddHIZbOU9pmrcPODI1kRx.jpg",
        posterHorizontal: "/uFwnUQ3ZwE5EbBEDBzs1bRPlOx8.jpg",
        voteAverage: 7.526,
        type: "movie",
        videoUrl: "1BvKZMg2LjU",
      },
      {
        id: 197155,
        title: "Los Angeles: 'Wonder City of the West'",
        overview:
          "This Traveltalk series short visits Los Angeles, California. In one of the highlights of the film, narrator James FitzPatrick visits the Disney cartoon studio and shakes hands with Walt Disney.",
        poster: "/ibIQhLPcKXgHJjAALJoTGpbGNjd.jpg",
        posterHorizontal: null,
        voteAverage: 4,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 195837,
        title: "The House Across the Street",
        overview:
          "The small coastal town of Roquesas de Mar (village invented by the author) is shocked by the disappearance of one of her neighbors sixteen years of age. When days later found the girl's body, horribly maimed in the back of the house of one of the most famous residents of the village, all Alsina Alvaro suspect as the perpetrator.",
        poster: "/9EW9rCmMd6HiQp0iMfwmChOAOye.jpg",
        posterHorizontal: null,
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "1Mb5A69G2ZE",
      },
      {
        id: 204362,
        title: "Frank Zappa: A Token Of His Extreme",
        overview:
          "Frank Zappa: A Token of his Extreme is the 1974 television special recorded at Kcet in Hollywood that was produced by Zappa and aired only in France and Switzerland.  The program, as thoroughly tweezed and produced by Zappa for his own Honker Home Video label, includes the following musical performances by Zappa and his band: T”he Dog Breath Variations/ Uncle Meat,” “Montana,” “Florentine Pogen,” “Stink-Foot,” “Pygmy Twylyte,” “Room Service,” “Inca Roads,” “Oh No,” Son of Orange County,” “More Trouble Every Day” and “A Token of My Extreme.”  In the words of Zappa himself as he said it on The Mike Douglas Show in 1976, “This is  put together with my own money and my own time and it’s been offered to television networks and to syndication and it has been steadfastly rejected by the American television industry.",
        poster: "/cYzSS8RjsBx3PL5UVs3RMLBgRKi.jpg",
        posterHorizontal: null,
        voteAverage: 9.5,
        type: "movie",
        videoUrl: "HrmtAQvmfN8",
      },
    ],
  },
  {
    id: 429,
    title: "The Good, the Bad and the Ugly",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    poster: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    posterHorizontal: "/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "IFNUGzCOQoI",
    similar: [
      {
        id: 201088,
        title: "Blackhat",
        overview:
          "Nicholas Hathaway, a furloughed convict, and his American and Chinese partners as hunt a high-level cybercrime network from Chicago to Los Angeles to Hong Kong to Jakarta. As Hathaway closes in, the stakes become personal as he discovers that the attack on a Chinese nuclear power plant was just the beginning.",
        poster: "/7zu6HPnKPjNA7NuR4DGRdaH0PdX.jpg",
        posterHorizontal: "/1u7TuvR5mSUz2xRQhz01i75IwdT.jpg",
        voteAverage: 5.472,
        type: "movie",
        videoUrl: "-CA95Bzpy7s",
      },
      {
        id: 199458,
        title: "As Long as You're Near Me",
        overview:
          "As Long as You're Near Me (German: Solange Du da bist) is a 1953 West German drama film directed by Harald Braun. It was entered into the 1954 Cannes Film Festival.",
        poster: "/gi1RD8dyMMpnpoGsa2814GaKUWI.jpg",
        posterHorizontal: null,
        voteAverage: 5.1,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 196852,
        title: "Asambhav",
        overview:
          'When the President of India is kidnapped by Kashmiri terrorists in Locarno, Switzerland, an Indian secret agent is sent to find him and set him free. With the help of an Indian singer he will make the "Impossible" to complete the mission.',
        poster: "/tc6dAT5FJ0P17NAVwAD7yqFWG5R.jpg",
        posterHorizontal: "/lIEicw6VnL7sguoPq3Z7xUwYHA8.jpg",
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 197750,
        title: "Two Violent Men",
        overview: "Two violent men bent on revenge in the old west.",
        poster: "/f9PXttiagML7EKhPFSoBoLrmXUg.jpg",
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "OPCTOK89U2I",
      },
      {
        id: 204342,
        title: "HK: Forbidden Super Hero",
        overview:
          "High school student Kyosuke Shikijo is the most talented member of the school's martial arts of the fist club. His late father was detective and Kyosuke share his father's strong sense of justice. Kyosuke also has a secret. Kyosuke likes to wear female underwear and transforms himself into the alter ego \"Hentai Kamen,\" wearing female underwear and gaining superhuman powers. This unusual interest also comes from his parents, with his father a masochist and his mother a sadist. By chance, Kyosuke gets the underwear of female high school student Aiko Himeno. With her underwear, he gains various pervert techniques and attempts to protect Aiko from a dirty and heinous teacher.",
        poster: "/o5ENtNf4uNACilr90RNTIhd2CtU.jpg",
        posterHorizontal: "/tQklCtE5JSmK9SecEHi5dqBfe5G.jpg",
        voteAverage: 6.2,
        type: "movie",
        videoUrl: "c0vF0CBKKEc",
      },
      {
        id: 227359,
        title: "Force of Execution",
        overview:
          "Seagal stars as mob kingpin Mr. Alexander, an old-school boss who rules his criminal empire with both nobility and brutality. For a simple prison hit, he sends his best enforcer and protégé Roman Hurst (Foster). When the hit goes wrong, Hurst is forced to pay the price of his failure: banishment in the city that he almost once ruled. But a war is brewing for the soul of the city between Alexander, a cold-blooded gangster known as 'The Iceman\" (Rhames) and a merciless Mexican cartel. Hurst, with the help of an ex-con restaurant owner (Trejo) who has a few hidden moves of his own, will rediscover his own will to survive the coming conflict and to wreak vengeance on those who have wronged him.",
        poster: "/hivQJRCtsMwwj9rdeSCQcXmVrph.jpg",
        posterHorizontal: "/nEuLKnO5GaiefmDy3gOSdXlVas8.jpg",
        voteAverage: 4.831,
        type: "movie",
        videoUrl: "L6D7YGDd8No",
      },
    ],
  },
  {
    id: 13,
    title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    poster: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    posterHorizontal: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "76WeEuR0qk4",
    similar: [
      {
        id: 223658,
        title: "Waiting for the Moon",
        overview:
          "Fictionalized portrait of one of history's great literary couples: Stein & Toklas. Summer 1930s France, Alice tends to ailing Gertrude; they visit Fernande Olivier, Guillaume Apollinaire, others; and Hemingway pops in.",
        poster: "/9nvZabS1QpAxUr0q7qBvb1uf7cH.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "ayxJRcSlFvc",
      },
      {
        id: 223722,
        title: "Nelson Gonçalves",
        overview:
          "Fiction/documentary about great Brazilian singer Nelson Gonçalves, where interviews about him are mixed with dramatization of episodes in his life. The film tell us about Nelson's childhood, the time when he tried his luck as a professional boxer, his career as a radio singer in the 1950s, the decadence caused by his cocaine addiction and his comeback.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 223771,
        title: "Midnight Tease II",
        overview:
          "Jennifer Brennan gets a job at a strip club to try and find out who killed her sister. She works with undercover cop John Donnelly and befriends other strippers some of whom also get murdered by a very unhappy murdering murderer.",
        poster: "/k3rx8D7e8sDbelEM3IBkmymP13V.jpg",
        posterHorizontal: null,
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199425,
        title: "Dog's Heads",
        overview:
          "Dog's Heads (Czech: Psohlavci) is a 1955 Czech drama film directed by Martin Frič, based on the novel of the same name by Alois Jirásek. It was entered into the 1955 Cannes Film Festival.",
        poster: "/vpXrdZeoeWdFUbHVpGpissGrOdq.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199470,
        title: "Modern People",
        overview:
          "A section chief at the Bureau of Construction is in a shady relationship with a construction company. Then a new, young and honest subordinate is assigned to work under the section chief. Once he learns about the shady relationship, however, the new subordinate skillfully conceals the corruption and joins the corrupt, shady relationship.",
        poster: "/2fZCRNSycJbgZAbBetd6phbSkyg.jpg",
        posterHorizontal: null,
        voteAverage: 4,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199483,
        title: "The Village",
        overview:
          "The Village (German: Sie fanden eine Heimat) is a 1953 Swiss drama film directed by Leopold Lindtberg.",
        poster: null,
        posterHorizontal: null,
        voteAverage: 0,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 372754,
    title: "Dou kyu sei – Classmates",
    overview:
      "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
    poster: "/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
    posterHorizontal: "/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "wFQTncSyukA",
    similar: [
      {
        id: 72842,
        title: "Albatross",
        overview:
          "Beth, a bookish teenager, befriends Emilia, an aspiring novelist who has just arrived in town. Emilia soon begins an affair with Beth's father that threatens to have devastating consequences.",
        poster: "/ocB3vHqqJwLVQg0jaWLgLlEeSr7.jpg",
        posterHorizontal: "/atPa3FCFIyJtJNeQUU12xGyP9Sz.jpg",
        voteAverage: 6.2,
        type: "movie",
        videoUrl: "Eaq03LQ-KMw",
      },
      {
        id: 75090,
        title: "Beware the Gonzo",
        overview:
          "Eddie \"Gonzo\" Gilman is starting a revolution. When the wild-eyed rebel journalist is ousted from his prep school's newspaper by its über-popular editor, Eddie fronts an underground movement to give a voice to all the misfits, outcasts, and nerds. Soon the power of the press is in Eddie's hands... but will he use it wisely?",
        poster: "/8HBvgkYWRtEtaKiqWeRaFEBFYqj.jpg",
        posterHorizontal: "/aZeOKKcFl2g48ioDk4wZrY6rwpZ.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "wu3kpPkgvwk",
      },
      {
        id: 80271,
        title: "LOL",
        overview:
          "In a world connected by YouTube, iTunes, and Facebook, Lola and her friends navigate the peer pressures of high school romance and friendship while dodging their sometimes overbearing and confused parents. When Lola's mom, Anne, \"accidentally\" reads her teenage daughter's racy journal, she realizes just how wide their communication gap has grown.",
        poster: "/AlnBUoKzzPnczrzzxuh0SYwDa3Z.jpg",
        posterHorizontal: "/6SOpmxAsu5IjGNqZVjjtQl83lkd.jpg",
        voteAverage: 6.135,
        type: "movie",
        videoUrl: "4P6mXZzY9nc",
      },
      {
        id: 80295,
        title: "14 and Under",
        overview:
          "This episodic film is a close relative of Wolf Hartwig's schoolgirl report movies, made by the same people, in a similar style, around similar topics. However, this one specifically focuses on the coming-of-age aspects, to an extent that it also touches on delicate issues such as paedophilia.",
        poster: "/gN8wIVtqNcbud4utOSCZr0dQzU1.jpg",
        posterHorizontal: "/eEdGWMYGf1USdF3SlDn0l80wM1W.jpg",
        voteAverage: 5.6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80310,
        title: "Children's Island",
        overview:
          "Reine is supposed to go to a summer camp called Children's Island but decides to remain in Stockholm over the summer while his mother is working at a hospital. She thinks he is at the camp, and he tells her he is. We then follow him around Stockholm that summer and see what he encounters on the path of life.",
        poster: "/w3KurV2pxSbysfpfH43esdBNf1G.jpg",
        posterHorizontal: "/sLssAEHIOTYgikJpJWnhjcGBTAM.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83704,
        title: "491",
        overview:
          "A study in forgiveness as oppression and goodness as provocation. Six youth criminals are chosen to participate in a social experiment where they are assigned to live together in a rundown apartment in the heart of Stockholm, Sweden. The six boys are being supervised by two forgiving and uneasy social workers. Their need to continue to commit petty crimes escalates out of boredom with the situation. One night they run into a young girl in trouble.",
        poster: "/8eOGkaNjcFtLcVoiL4fnEqW0ZYz.jpg",
        posterHorizontal: "/vDmf1ARA6K8P9juq8jLHCOx8ZjW.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
] as BrowserProps["topRatedMoviesSimilar"];
