import { BrowserProps } from "pages/browse";

export default [
  {
    id: 640146,
    title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    posterHorizontal: "/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg",
    voteAverage: 7.082,
    type: "movie",
    videoUrl: "5WfTEZJnv_8",
    similar: [
      {
        id: 201003,
        title: "The Family and One More",
        overview:
          "The life of the family inordinate surveyor Carlos Alonso has undergone several changes over the course of the years: the birth of child number 16, little Maria, coincided with the death of the mother, who left behind a hollow refillable. The grandfather also died. The Godfather pastry married, and the boys have been growing rapidly ...",
        poster: "/8bz1FKL9bPbIvHBHl0DeudexUZN.jpg",
        posterHorizontal: "/4U353J7OxDEl9HxohOgJ63LSlH2.jpg",
        voteAverage: 6.375,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199374,
        title: "My Sister's Kids in Africa",
        overview:
          "This time our already familiar family moves to Africa in order to save endangered wildlife.",
        poster: "/rwr2WiwR4St2eq21NEixEV56RE0.jpg",
        posterHorizontal: "/e2P8nGCJRgi04UPR0hhcWhoB42H.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201937,
        title: "Prehysteria! 2",
        overview:
          'A rich boy desperate for attention makes friends with the dinosaurs of "Prehysteria!". Prehysteria! 2',
        poster: "/oFvNCkKjYfSSGOjaEerp4XjJrcI.jpg",
        posterHorizontal: "/4ZLYAgNd7SLJJ9ZAjxTAJnVTDU5.jpg",
        voteAverage: 4.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201938,
        title: "Prehysteria! 3",
        overview:
          "The dinosaurs help young Ella and her family save their mini-putt business.",
        poster: "/nBTW3ME6IQuzuq6puvOhN0IQpQn.jpg",
        posterHorizontal: "/sp0Eg1Sd48OVIhFm4TPrAZJxhsx.jpg",
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199960,
        title: "The Son of Tarzan",
        overview:
          "Tarzan's son Jack is kidnapped from England by his old enemy Paulovich. Jack escapes into the African jungle where he meets Meriem, a European girl held captive. Freeing her, he falls in love but she's sought by Paulovich. Then Tarzan arrives with Jane to save the day!",
        poster: "/6TJ78ttG3O7pNSN8xBmYBf4nIKm.jpg",
        posterHorizontal: "/vCnah8kXNogx3B9jtB59kMIum5W.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 200050,
        title: "A Família do Barulho",
        overview:
          "A dysfunctional family, composed of a prostitute and two gays, one strong and the other fragile and stupid, lives a routine life in Rio de Janeiro. When the slut threatens the other two to stop supporting them, they decide to find an odalisque as an alternative to keep their easy life.",
        poster: "/aLWRs7kYi2hNztg71AsvKEiPoZ4.jpg",
        posterHorizontal: "/humTzo1aBtF1XWW4jQuahEJR8Pj.jpg",
        voteAverage: 4.5,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 667216,
    title: "Infinity Pool",
    overview:
      "While staying at an isolated island resort, James and Em are enjoying a perfect vacation of pristine beaches, exceptional staff, and soaking up the sun. But guided by the seductive and mysterious Gabi, they venture outside the resort grounds and find themselves in a culture filled with violence, hedonism, and untold horror.",
    poster: "/5DNRr2juXdwtvktwXxwuk9Usk8O.jpg",
    posterHorizontal: "/gmBJmDJd8Lz44FApFOpqn1tNDnd.jpg",
    voteAverage: 6.652,
    type: "movie",
    videoUrl: "W5mfHz-5dx8",
    similar: [
      {
        id: 201126,
        title: "El soplagaitas",
        overview:
          "Ramiro is a good man. He is a musician, but unemployment is so great that it has had to put Scottish bagpipes playing a Scotch Pub also married. One night coming home from work encountered in a corner, with Julian; believes has stolen his wallet and to take back what is theirs thinks Julian attacks is municipal councilor in the city. The theft of this portfolio will complicate the life of Ramiro, that of Julian and the many characters ...",
        poster: "/kwCgHfoiJoIfLtnjninF5SybP5B.jpg",
        posterHorizontal: "/7UQHJ5tVoNIhGXG0WtgHz7jZshJ.jpg",
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199374,
        title: "My Sister's Kids in Africa",
        overview:
          "This time our already familiar family moves to Africa in order to save endangered wildlife.",
        poster: "/rwr2WiwR4St2eq21NEixEV56RE0.jpg",
        posterHorizontal: "/e2P8nGCJRgi04UPR0hhcWhoB42H.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201604,
        title: "Necropolis",
        overview:
          "A surreal and disturbing distillation of Western Civilization, Necropolis is the unhinged vision of Italian director Franco Brocani.  Pierre Clémenti is Attila the Hun, naked and on horseback, while Warhol superstar Viva is a drunken and abusive Countess Bathory.  A pop pastiche for the psychedelic generation, Necropolis features a soundtrack by Gavin Bryars.",
        poster: "/2SlthS3VMpPBxCJvf2L52VlYu2V.jpg",
        posterHorizontal: "/rTW7naDxYHBEmkysp4iowFtcafN.jpg",
        voteAverage: 4.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 197796,
        title: "Beauty and the Beast",
        overview:
          "Forced to face the cruel side of life, a devastated, bankrupt merchant chances upon the enchanted castle of a hideous creature, the mere sight of it chills the bone to the marrow. There, a fate worse than death awaits the poor father-of-six, who, after plucking a sweet-scented rose from the repulsive master's verdant garden, must do the impossible: permit his compassionate daughter, Belle, to take his place and pay for the sins of her parent. Now, an impenetrable mystery shrouds the haunted mansion, and, as repugnance gradually turns into affection, only true love could break the spell.",
        poster: "/8bErT2koHXAUSW5PdLQqgL5gEEe.jpg",
        posterHorizontal: "/92Uceuy7HaiiHFgW48gNyxhx17d.jpg",
        voteAverage: 6.113,
        type: "movie",
        videoUrl: "grLYbcAOW4E",
      },
      {
        id: 219501,
        title: "Streamlined Greta Green",
        overview:
          "In the world of this cartoon, cars act like humans. Junior wants to grow up to be a taxi, but mom wants him to be a nice, respectable touring car (taxi dancers are literally taxis). What mom doesn't know is that junior has been sneaking into town to play in traffic, drink hi-test gas, and race trains. He runs out of gas at a particularly bad time and gets towed to the garage.",
        poster: "/nYlGOjPO6KhCatuhIHbhtjXzikS.jpg",
        posterHorizontal: "/m0N4QD0XCqap6E054ov63iT2hUt.jpg",
        voteAverage: 6.3,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 219546,
        title: "Dog Daze",
        overview:
          "A series of gags at a dog show, including a stage revue. A dog gets into a trunk of roller skates and crashes through the stage show.",
        poster: "/4kyT7r3GkOhxRL4qKHzHh5uze1B.jpg",
        posterHorizontal: "/tQRmI2spaR2kAJocbGfBxzCtQGp.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 100088,
    title: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    posterHorizontal: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    voteAverage: 8.814,
    type: "tv",
    videoUrl: "uLtkt8BonwM",
    similar: [
      {
        id: 19,
        title: "Planet of the Apes",
        overview:
          "Two astronauts and a sympathetic chimp friend are fugitives in a future Earth dominated by a civilization of humanoid apes. \n\nBased on the 1968 Planet of the Apes film and its sequels, which were inspired by the novel of the same name by Pierre Boulle.",
        poster: "/zxo5Vrd0oXgm9ZCz4r7Q3L8veWg.jpg",
        posterHorizontal: "/JrBiUtR2CwxZR5GMK5Z9dU7Wr4.jpg",
        voteAverage: 6.929,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 44,
        title: "Adventures of Sonic the Hedgehog",
        overview:
          "Follow the adventures of Sonic the Hedgehog, and his sidekick Tails, as they attempt to stop Dr. Robotnik and his array of robots from taking over the planet Mobius.",
        poster: "/xjhZhermBwZtWiPA7xT7Rli2tmD.jpg",
        posterHorizontal: "/da5qFYz4JT1d4kTwbU1Gf15TRBD.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "yTc5HNKNKBY",
      },
      {
        id: 547,
        title: "Medical Investigation",
        overview:
          'Medical Investigation was an American medical drama television series that began September 9, 2004, on NBC. It ran for 20 one-hour episodes before being cancelled in 2005. The series was co-produced by Paramount Network Television and NBC Universal Television Studio The former controls North American distribution rights, while the latter distributes outside North America.\n\nThe series featured the cases of an elite team of medical experts of the National Institutes of Health who investigate unusual public-health crises, such as sudden outbreaks of serious and mysterious diseases. In actuality, medical investigative duties in the United States are normally the responsibility of the Centers for Disease Control and Prevention and local health departments, while the NIH is primarily a disease-research and -theory organization.\n\nThe series existed in the same television universe as Third Watch and, by extension ER. A special two-part crossover event aired on February 18, 2005, establishing the television-universe connection by featuring the Third Watch and Medical Investigation teams working together in MI\'s Episode 17: "Half Life" and Third Watch\'s Episode 16 of the sixth season: "In the Family Way". The story was about a series of Marburg virus cases in New York.',
        poster: "/3bTy80VccV3suS9ywXryGakdG5y.jpg",
        posterHorizontal: null,
        voteAverage: 6.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 574,
        title: "Thunderstone",
        overview:
          "The year is 2020. Fifteen-year-old Noah lives with his family in the futuristic underground community of North Col. The world above is a frozen wasteland after a massive comet strike destroyed all other life in the world including the animals. One night, he accidentally time travels to the future and finds himself trapped in the year 2085 in a desolate desert place called Haven with a group of children, the Nomads, led by Arushka.",
        poster: "/QjNZcyIxRVTvx2vhsfP3rMcp1o.jpg",
        posterHorizontal: "/gXZtfUyhp68COVoPVCqc2Pa1nQB.jpg",
        voteAverage: 6.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1571,
        title: "The Legend of Zelda",
        overview:
          "The young adventurer Link and Princess Zelda protect Hyrule from the forces of Ganon, an evil wizard who desires the kingdom's treasured Triforce of Wisdom.",
        poster: "/oddre5aHiXSMnTMtMBPyv12rjbC.jpg",
        posterHorizontal: "/gyZRUabOxDnf2XKeCg4S8KGNmRl.jpg",
        voteAverage: 5.4,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 1402,
        title: "The Walking Dead",
        overview:
          "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
        poster: "/xf9wuDcqlUPWABZNeDKPbZUjWx0.jpg",
        posterHorizontal: "/zaulpwl355dlKkvtAiSBE5LaoWA.jpg",
        voteAverage: 8.113,
        type: "tv",
        videoUrl: "BXqUmob-nfg",
      },
    ],
  },
  {
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    poster: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    posterHorizontal: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    voteAverage: 7.5,
    type: "movie",
    videoUrl: "_Z3QKkl1WyM",
    similar: [
      {
        id: 201003,
        title: "The Family and One More",
        overview:
          "The life of the family inordinate surveyor Carlos Alonso has undergone several changes over the course of the years: the birth of child number 16, little Maria, coincided with the death of the mother, who left behind a hollow refillable. The grandfather also died. The Godfather pastry married, and the boys have been growing rapidly ...",
        poster: "/8bz1FKL9bPbIvHBHl0DeudexUZN.jpg",
        posterHorizontal: "/4U353J7OxDEl9HxohOgJ63LSlH2.jpg",
        voteAverage: 6.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199374,
        title: "My Sister's Kids in Africa",
        overview:
          "This time our already familiar family moves to Africa in order to save endangered wildlife.",
        poster: "/rwr2WiwR4St2eq21NEixEV56RE0.jpg",
        posterHorizontal: "/e2P8nGCJRgi04UPR0hhcWhoB42H.jpg",
        voteAverage: 5.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199420,
        title: "Pawn Shop Chronicles",
        overview:
          "The stories of a missing wife, a couple of meth heads and an Elvis impersonator are connected by the items found in a small town's pawn shop.",
        poster: "/1jQUcZ2uWUe2jIxa5efNuMhdhts.jpg",
        posterHorizontal: "/pt4QcQmVhi5bAyEJvk87E7W1kcQ.jpg",
        voteAverage: 5.76,
        type: "movie",
        videoUrl: "bMA0bukvXsI",
      },
      {
        id: 201937,
        title: "Prehysteria! 2",
        overview:
          'A rich boy desperate for attention makes friends with the dinosaurs of "Prehysteria!". Prehysteria! 2',
        poster: "/oFvNCkKjYfSSGOjaEerp4XjJrcI.jpg",
        posterHorizontal: "/4ZLYAgNd7SLJJ9ZAjxTAJnVTDU5.jpg",
        voteAverage: 4.2,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201938,
        title: "Prehysteria! 3",
        overview:
          "The dinosaurs help young Ella and her family save their mini-putt business.",
        poster: "/nBTW3ME6IQuzuq6puvOhN0IQpQn.jpg",
        posterHorizontal: "/sp0Eg1Sd48OVIhFm4TPrAZJxhsx.jpg",
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 199960,
        title: "The Son of Tarzan",
        overview:
          "Tarzan's son Jack is kidnapped from England by his old enemy Paulovich. Jack escapes into the African jungle where he meets Meriem, a European girl held captive. Freeing her, he falls in love but she's sought by Paulovich. Then Tarzan arrives with Jane to save the day!",
        poster: "/6TJ78ttG3O7pNSN8xBmYBf4nIKm.jpg",
        posterHorizontal: "/vCnah8kXNogx3B9jtB59kMIum5W.jpg",
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 991814,
    title: "Re/Member",
    overview:
      "Six high schoolers stuck in a murderous time loop must find the scattered remains of an unknown victim to break the curse and finally see another day.",
    poster: "/cCTmZ93aBZ1FwHntiDpa2Lj92zs.jpg",
    posterHorizontal: "/uhAU3MI8YsUue7qqjFrpRQDpgvd.jpg",
    voteAverage: 7.3,
    type: "movie",
    videoUrl: "Y8yvXoyLPvM",
    similar: [
      {
        id: 81788,
        title: "Bus Stop",
        overview:
          "A thirty-two year old man falls in love with a seventeen year-old highschool student whom he sees at the bus stop everyday.",
        poster: "/jHXQc8jhCsAv0hKNp0WoR9ETdbb.jpg",
        posterHorizontal: "/hF9nPndAvKt0tPeolMFBKWWJiKu.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 97605,
        title: "Extracted",
        overview:
          "Thomas Jacobs invents a way to watch people's memories from the inside. Going against his morals, he accepts an offer to enter a heroin addict's memories to literally see if he committed a crime. However,a malfunction causes his consciousness to become trapped inside the criminal's mind. He remains a prisoner in the addict's memories for more than four years until he discovers the possibility of escape.",
        poster: "/ciuOIA66tZuCJRfRjfG9coiqjWm.jpg",
        posterHorizontal: "/WvmaStQ8bInvgFeViOgIBPTDM0.jpg",
        voteAverage: 6.2,
        type: "movie",
        videoUrl: "hcFwqwmV38o",
      },
      {
        id: 107308,
        title: "The Golden Bat",
        overview:
          "A teenage boy discovers that the planet Icarus is on a collision course with Earth by gazing through his telescope. Scoffed at by the scientific establishment, the boy is kidnapped and brought to a secret UN base in the Japan alps. He is immediately inducted into the secret program whose mission is to finish the Super-Destruction Beam cannon and destroy Icarus. The cannon is missing a special mineral for the lens. The team heads for a mysterious island in the middle of the Pacific. There they find ancient ruins of Atlantis but they are suddenly attacked by a strange drill shaped metal squid spaceship. It's commanded by the evil being Nazu who has engineered the collision with Icarus! He doesn't want to share the universe with humans and he really doesn't want the cannon finished. The action is on and the team discovers the Golden Bat who has been asleep for over 10,000 years awaiting this very moment to save the earth!",
        poster: "/i0WMLKscnHbp4xDG7foQISmRQYV.jpg",
        posterHorizontal: "/e0vKgvFbgIzp5sEpwvWHzvD5RnN.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "EDwvLZrYWgc",
      },
      {
        id: 71700,
        title: "Repeaters",
        overview:
          "A gritty mind-bending thriller about three twenty-somethings who find themselves in an impossible time labyrinth, where each day they awaken to the same terrifying day as the preceding one.",
        poster: "/9nQuL87o5AcUayeZM3cOXw1VbIv.jpg",
        posterHorizontal: "/5HMmzpWnH6b9gV3WQ3LscPRoCJn.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "WA4TT6A-4IU",
      },
      {
        id: 74135,
        title: "Gantz: Perfect Answer",
        overview:
          "Perfect Answer begins several months after the events of the first film. Kurono is still fighting aliens under the order of Gantz, a mysterious giant black orb, and he is close to reaching the score he needs to resurrect his friend Kato. Outside his night time missions, Kurono continues to live his normal life, spending time with his new girlfriend Tae. Meanwhile, young pop star Eriko  is being secretly ordered by Gantz to carry out assassinations, and cop Shigeta inches closer towards finding out the truth about the Gantz missions. As the missions begin to get increasingly dangerous for both the alien fighters and the general public, Kurono discovers that the endgame for Gantz is quickly approaching.",
        poster: "/ir6QhKXU3zDYaOnJ0ISpu3nkE7O.jpg",
        posterHorizontal: "/f9ofAmrpmtlX622I0f7mPYiCSRF.jpg",
        voteAverage: 6.8,
        type: "movie",
        videoUrl: "bcSThPonFgs",
      },
      {
        id: 83389,
        title: "From Up on Poppy Hill",
        overview:
          "Two high schoolers find hope as they fight to save an old wartime era clubhouse from destruction during the preparations for the 1964 Tokyo Olympics.",
        poster: "/pLPvpMwD4fkLs3mki87NxTP1Yjc.jpg",
        posterHorizontal: "/v3bVN8SjeA9O0nUBtMfRcE0fJpR.jpg",
        voteAverage: 7.538,
        type: "movie",
        videoUrl: "k-vfzhfq5JA",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/tGwO4xcBjhXC0p5qlkw37TrH6S6.jpg",
    voteAverage: 8.5,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 72762,
        title: "Jack and the Beanstalk",
        overview:
          "A retelling of the popular fairy tale that mixes live action and animation.",
        poster: "/prD4GSmkzW8XbZKhZpW4wQ9dI3Q.jpg",
        posterHorizontal: "/qtMMIqLhk5SVJMRuoKgHcM6G3PC.jpg",
        voteAverage: 7.9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 75098,
        title: "Lotte Reiniger: The Fairy Tale Films",
        overview:
          "Lotte Reiniger was one of the twentieth century’s major animation artists, pioneering a distinctive style of black and white silhouette animation in her interpretations of classic myths and fairy tales. Reiniger began her career in Germany, making The Adventures of Prince Achmed, one of the first and most ingenious full-length animated films in the history of cinema. After the war, she moved to Britain with her husband Carl Koch and made short films for the GPO and later, in collaboration with Primrose Productions, an extensive series of famous fairy tale short films. This is a DVD collection of her work.",
        poster: "/vsjDHSXs80FJGGUD7qzijMn7NSD.jpg",
        posterHorizontal: "/pz3TXUZOJkws4wp2weW1yo4zUeW.jpg",
        voteAverage: 9,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 80304,
        title: "Casa De Mi Padre",
        overview:
          "Scheming of a way to save their father's ranch, the Alvarez brothers find themselves in a war with Mexico's most feared drug lord.",
        poster: "/kVCc7xwTAlckBofazrwIz8x1TXC.jpg",
        posterHorizontal: "/bTy0LQEXValfIemrLvE5dMJobE4.jpg",
        voteAverage: 5.38,
        type: "movie",
        videoUrl: "01IYDy2Gdk4",
      },
      {
        id: 90512,
        title: "The Frog Princess",
        overview:
          "A prince discovers an enchanted beauty turned into a frog by Koschei the Immortal. After Koschei steals her again, the prince goes on a dangerous quest to free the land of the evil.",
        poster: "/qa6gtK1T1wMebluGMv5c7KANK90.jpg",
        posterHorizontal: "/3UaeEyh0yJEYGxtPqRu9TwaWz4i.jpg",
        voteAverage: 7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 83811,
        title: "The Daydreamer",
        overview:
          "In this hybrid of live-action and stop-motion animation, a young Hans Christian Andersen goes in search of knowledge in the Garden of Paradise in order to make his studies easier. Each time he falls asleep, he experiences in his dreams the different characters he would later write about in fairy tales including The Little Mermaid, Thumbelina and The Emperor's New Clothes.",
        poster: "/k7RiyeB5NccB2NgXtVFJXFiwe6Z.jpg",
        posterHorizontal: "/1D05GkR8sJDzGuQirq26q1tIQgX.jpg",
        voteAverage: 5.8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 82990,
        title: "Paranormal Activity 4",
        overview:
          "It has been five years since the disappearance of Katie and Hunter, and a suburban family witness strange events in their neighborhood when a woman and a mysterious child move in.",
        poster: "/na5tAslm1kGNcft083AIXMTOsYR.jpg",
        posterHorizontal: "/eq68gWGBtumauGYFV1FCJ20kXFU.jpg",
        voteAverage: 5.418,
        type: "movie",
        videoUrl: "P1wbwf0wayk",
      },
    ],
  },
  {
    id: 207878,
    title: "Red Rose",
    overview:
      "When one of a group of friends downloads the mysterious Red Rose app, plans change. What starts innocently as a game of admiration rapidly descends into something much darker.",
    poster: "/jS8mOKloyEzqQKrne0w4Upu1pnv.jpg",
    posterHorizontal: "/8u6btHEx6knRmtaHQtcytiM6XHd.jpg",
    voteAverage: 5.8,
    type: "tv",
    videoUrl: "onU5dR1B0uY",
    similar: [
      {
        id: 37774,
        title: "Marchlands",
        overview:
          "The gripping story of three different families living in the same house in the 1960’s, 1980’s and present day. The families are linked by the spirit of a young girl – the 1960’s family’s daughter who died in mysterious circumstances.",
        poster: "/lf7eAFbaXrQTFlXPW5SDVL9wUGK.jpg",
        posterHorizontal: "/7S648KGW2iW2JEyWnaKj73WeCSL.jpg",
        voteAverage: 7.7,
        type: "tv",
        videoUrl: "IMRCsoNxljw",
      },
      {
        id: 37618,
        title: "Bedlam",
        overview:
          "Welcome to Bedlam Heights. Converted from an imposing former lunatic asylum, this apartment building offers the ultimate in stylish 21st century urban living. But little do its new residents suspect that behind the luxury fittings lay unimaginable horrors.",
        poster: "/b39xZdSXuXVzk2wB7F3snflNDpU.jpg",
        posterHorizontal: "/cwB3dkRW0fn4EubyiVHnSUIMwsg.jpg",
        voteAverage: 5.8,
        type: "tv",
        videoUrl: "MmB6mkexPuE",
      },
      {
        id: 11183,
        title: "Poltergeist: The Legacy",
        overview:
          "The adventures of the members of a secret society known as the Legacy and their efforts to protect humankind from occult dangers.",
        poster: "/dewrEVHQmFdHUnBUD83BLjs2ZVs.jpg",
        posterHorizontal: "/ydWtwIDY7MGMQDAo5vZYEI4OO8R.jpg",
        voteAverage: 6.8,
        type: "tv",
        videoUrl: "L0rZLPVSddg",
      },
      {
        id: 39758,
        title: "Bag of Bones",
        overview:
          "Bestselling novelist Mike Noonan, unable to cope after his wife's sudden death, returns to the couple's lakeside retreat in Maine, where he becomes involved in a custody battle between a young widow and her child's enormously wealthy grandfather. Mike inexplicably receives mysterious ghostly visitations, escalating nightmares and the realization that his late wife still has something to tell him.",
        poster: "/ziIOygc0X8rOSRw3AIGzDJdq7F.jpg",
        posterHorizontal: "/vgEwiWX66tO6tTfKrOhCSm0YBnX.jpg",
        voteAverage: 6,
        type: "tv",
        videoUrl: "Y57K6IoAj7Y",
      },
      {
        id: 1413,
        title: "American Horror Story",
        overview:
          "An anthology horror drama series centering on different characters and locations, including a house with a murderous past, an asylum, a witch coven, a freak show, a hotel, a farmhouse in Roanoke, a cult, the apocalypse and a summer camp.",
        poster: "/tiuzjuzalHj377XER1sfq7XQEIT.jpg",
        posterHorizontal: "/8kBhAP03JpPcTklJp5idCNJhRqE.jpg",
        voteAverage: 8.151,
        type: "tv",
        videoUrl: "-9KZr2Vn7CQ",
      },
      {
        id: 66732,
        title: "Stranger Things",
        overview:
          "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
        poster: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        posterHorizontal: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        voteAverage: 8.637,
        type: "tv",
        videoUrl: "mnd7sFt5c3A",
      },
    ],
  },
  {
    id: 218896,
    title: "The Law According to Lidia Poët",
    overview:
      "In late 19th-century Turin, the young Lidia Poët, fights against everything and everyone to get what is rightfully hers: to be enrolled in the official register of lawyers. A profession, at the time, reserved exclusively for men. Nevertheless, nothing could stop her dream of becoming the first female lawyer in Italy.",
    poster: "/9k8cA7T8hOwjoKZLEgFvvAVHP6l.jpg",
    posterHorizontal: "/gLWIHKaiLMtoAnc1iajVUDjePf9.jpg",
    voteAverage: 6.25,
    type: "tv",
    videoUrl: "KyIeHa0zvXM",
    similar: [
      {
        id: 4808,
        title: "Father Murphy",
        overview:
          "A good-hearted frontiersman poses as a priest to start an orphanage for a group of kids whose homes have been destroyed by an evil mining manager.",
        poster: "/jKhpdyrWJr1kYZGNIKgKJkm8gTT.jpg",
        posterHorizontal: null,
        voteAverage: 7.5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4205,
        title: "Kavanagh Q.C.",
        overview:
          "James Kavanagh QC is one of the top flight barristers in Britain. Each episode has him handling challenging cases and defendants which put his skills to the test regularly.",
        poster: "/qIXHr4lgRmlBOlBTj1aJdHPPE8r.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4324,
        title: "Dr. Quinn, Medicine Woman",
        overview:
          "Dr. Michaela Quinn journeys to Colorado Springs to be the town's physician after her father's death in 1868.",
        poster: "/rF32uo83bzezkEUQ8VGarbCJi32.jpg",
        posterHorizontal: "/tXJf6radpACrCQPYIU0ARFsVV7z.jpg",
        voteAverage: 7.611,
        type: "tv",
        videoUrl: "lNXvsza9new",
      },
      {
        id: 3806,
        title: "When Rules Turn Loose",
        overview:
          'Suen Man-Yee is a highly regarded lawyer in the "legal world". Due to unforeseen circumstances, she is temporarily appointed to be a judge.',
        poster: "/MJMzsEJedpQxri9v3ot71lVaLU.jpg",
        posterHorizontal: null,
        voteAverage: 1,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4376,
        title: "JAG",
        overview:
          'Harmon "Harm" Rabb Jr. is a former pilot turned lawyer working for the military\'s JAG (Judge Advocate General) division, the elite legal wing of officers that prosecutes and defends those accused of military-related crimes. He works closely with Lt. Col. Sarah Mackenzie, and together they do what needs to be done to find the truth.',
        poster: "/zPyHpkJZ5O08lbgrQQIROXtb3xz.jpg",
        posterHorizontal: "/4JNqR8YBAK8cvi595z5RDUzC26M.jpg",
        voteAverage: 7.3,
        type: "tv",
        videoUrl: "no-url",
      },
      {
        id: 4391,
        title: "First Monday",
        overview:
          "A newcomer to the Supreme Court finds himself a pivotal force on an often deadlocked bench, frequently at odds over hot-button cases in this earnest but brief legal drama. ",
        poster: "/sfPFFNlLPvn24nfWHjmy0YwlOqT.jpg",
        posterHorizontal: "/eavFlzVKC5IUSctOAmmdHJXAVRc.jpg",
        voteAverage: 6,
        type: "tv",
        videoUrl: "no-url",
      },
    ],
  },
  {
    id: 703451,
    title: "Your Place or Mine",
    overview:
      "When best friends and total opposites Debbie and Peter swap homes for a week, they get a peek into each other's lives that could open the door to love.",
    poster: "/ApkSeqfIPRCxOtfjXYYE6Ji7jVU.jpg",
    posterHorizontal: "/kMLZeN8YsMSuPp2fpyh4X526Vg6.jpg",
    voteAverage: 6.472,
    type: "movie",
    videoUrl: "5JyfgkPMXk0",
    similar: [
      {
        id: 200038,
        title: "The Golden Girls",
        overview:
          "A screenwriter gets involved with two actresses who are trying to succeed in the 1960s Hong Kong film industry.",
        poster: "/oNIOIa4RgN9W4etlqZgm6Hr36Bp.jpg",
        posterHorizontal: null,
        voteAverage: 7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 201765,
        title: "Three Many Weddings",
        overview:
          "Ruth, a young researcher at a college, is invited to the weddings of three of her exes. She enlists the help of her assistant to find a companion for each wedding; will one of them turn out to be her soulmate?",
        poster: "/zLZT2B8ioGJyuU3UmCXiY0fa5Fd.jpg",
        posterHorizontal: "/ogKkr5YOyKB0gY5lNTB9Rx6ZI95.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 227961,
        title: "S.O.S.: Women to the Sea",
        overview:
          "Recently divorced Adriana tries to get revenge on the woman who took her husband away from her by going on a European cruze along with them.",
        poster: "/3cB6m75oYbbuRI9K1Tgi2DBKhw9.jpg",
        posterHorizontal: "/aSb8UvibFfN2xG53dRkJabjALYF.jpg",
        voteAverage: 6.7,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 205610,
        title: "Julie's Pants",
        overview: "",
        poster: "/k41zfxv9coGjUbG9PVhrQW0Eln6.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 214129,
        title: "Why Your Crush Doesn't Have a Crush on You?",
        overview: "An ugly ducking attempts to become desirable.",
        poster: "/d2mk6f1sGlmyODGnzMNmBzTrJIg.jpg",
        posterHorizontal: "/9by62xqLDr9TS2D2ut1xfBH5f7v.jpg",
        voteAverage: 5.5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 194722,
        title: "At Middleton",
        overview:
          "Two parents fall in love over the course of a single day while playing hooky from their children's college tour.",
        poster: "/k7JOxvTL9oOAalE7FC9xuHYcu6h.jpg",
        posterHorizontal: "/dNd1oB77NPNarrTs7hWAWh5EYzk.jpg",
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "aGKtJ0ZffLY",
      },
    ],
  },
  {
    id: 615777,
    title: "Babylon",
    overview:
      "A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood's transition from silent films and to sound films in the late 1920s.",
    poster: "/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
    posterHorizontal: "/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg",
    voteAverage: 7.7,
    type: "movie",
    videoUrl: "OumYv1aE1VI",
    similar: [
      {
        id: 199419,
        title: "The Drinker",
        overview:
          'Hans Fallada tells in his published after the war novel "The drinker" the story of the agricultural wholesaler Erwin Sommer, who flees from his narrow bourgeois relations under the burdens of the new times in the kingdom of the king alcohol, whose liberty and independence promises prove a lie - the only truth of the alcohol. On behalf of the WDR television play Ulrich Plenzdorf has adapted Fallada\'s 1944/45 novel for a film adaptation by Tom Toelle with Harald Juhnke in the main role of Erwin Sommer.',
        poster: "/lTvR6FHoA5iAsASX2OkDXsWHvCD.jpg",
        posterHorizontal: null,
        voteAverage: 7.5,
        type: "movie",
        videoUrl: "5tsvYSioRek",
      },
      {
        id: 201984,
        title: "Little Swee'pea",
        overview:
          "Popeye takes Swee'pea to the zoo and spends most of his time rescuing the tot from the various animals.",
        poster: "/xrK962QOnVWXx4brX58E36mwDbq.jpg",
        posterHorizontal: null,
        voteAverage: 6.1,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 200034,
        title: "Bheemili Kabaddi Jattu",
        overview:
          "The entire story unfolds in a remote village near Vizag called Bheemli. What begins as a soft romance between a poor lad Suri (Nani) and a young girl (Saranya Mohan) who comes to the village soon takes a turn. Suri, along with his childhood friends, yearns to win a Kabaddi tournament. They're known for never managing to win a tournament.  They manage to find themselves by chance in a State-level tournament, expected to be knocked out in the very first round. But the bunch of young men who share different thoughts and ideas, with the help of a professional kabbadi coach, emerge as winners. As they proceed, many difficulties are encountered such as Suri having a shoulder dislocation during a match. However, they win all their remaining games and progress to the final. However, during this time, gangsters are searching for Suri.",
        poster: "/e7jcMszTi8W7eKHXLpBf89Hrf2z.jpg",
        posterHorizontal: "/nJdhQnrCV83fAHgwVa4nDpOMOhw.jpg",
        voteAverage: 8,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 197246,
        title: "The True Story of Killing Pablo",
        overview:
          "The career and death of notorious Colombian drug kingpin Pablo Escobar.",
        poster: "/lqqip2zXbVpI62ZfEsxLpIqa7t9.jpg",
        posterHorizontal: null,
        voteAverage: 6,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 195751,
        title: "Toughlove",
        overview:
          'The Charters family falls into despair over their drug-addicted son Gary. They discuss his problems through the "Toughlove" program in searching for answers.',
        poster: "/e70l836YOO2JsMCmnQjf7ZuNoUW.jpg",
        posterHorizontal: null,
        voteAverage: 5,
        type: "movie",
        videoUrl: "no-url",
      },
      {
        id: 195834,
        title: "Defenders of Riga",
        overview:
          "The film dramatizes November 11, 1919- a crucial date in the battle for Latvian independence. A year after the end of the official hostilities of WWI, a renegade German general and troops remain outside the Latvian capital. Latvian riflemen, most of them inexperienced volunteers, somehow managed to defeat a larger, better-armed force of German and Russian mercenaries.",
        poster: "/iHXjxW1pCcU52F6TAm0WyKRkaKB.jpg",
        posterHorizontal: "/z6jtevUdXzZyNGHDhFyUYtqEq7M.jpg",
        voteAverage: 5.4,
        type: "movie",
        videoUrl: "no-url",
      },
    ],
  },
] as BrowserProps["trendingTvShowsFiltered"];
